refactor: Scenemanagement corrections from the feedback of the 2nd assginment
Horizons-Games/Axolotl-Engine pull request #148
Opened 2023-02-14 18:25 UTC by markmeliaa

2023-02-14 20:14 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +	childTransform->UpdateTransformMatrices();
Is this call to `UpdateTransformMatrices` necessary? If I didn't misread the code, this method is called whenever theses matrices are requested, so as an outsider it feels like calling it here is redundant

2023-02-14 20:15 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +	childTransform->UpdateTransformMatrices();
The same thing happens in `Scene.cpp`, which probably means I'm wrong and this is useful, but no harm in asking :P

2023-02-14 20:21 UTC, gerard-queralt commented
If I recall correctly, most of your feedback ~~that wasn't my fault~~ was about not using Quaternions outside of transform and try to minimize computations of global matrices, right? You seem to have tackled all those issues, great job! Thank you very much for your effort!

2023-02-14 20:35 UTC, markmeliaa commented on Source/DataModels/GameObject/GameObject.cpp
> +	childTransform->UpdateTransformMatrices();
What `UpdateTransformMatrices` does is updating the transform of a gameobject and the transform of their children only when needed (another thing that they told us in the feedback is that updating that every frame is excessive), so we added UpdateTransformMatrices() to the places where the transform can be modified:

- When the transform is moved through its ImGui (I just changed this in a commit because I used the wrong function)
- When the transform is created (a gameobject could be created as a child of another gameobject and if that gameobject is in any position, that new transform of the new gameobject should be updated to that position)
- When a gameobject is moved using the drag and drop in the hierarchy.

This are the only cases that come to my mind, and they are there instead of just in the getters because the little axis transform is drawn every frame, so the transform should be updated not only when required by a getter, but at the time they are changed.

Regardless of that, I do not see that having them in the getters is bad (????), yes it may be redundant, but we would be sure that when the pos, rot, sca is retrieved in any other part of the code it would always be updated? I want to know your take on this one.

2023-02-14 23:27 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +	childTransform->UpdateTransformMatrices();
Oh okay, I see what you mean, it makes total sense! I thought they might only be needed when the getters of those methods were called, but I see how that's not the case. Thank you very much for your in-depth explanation!!
Regarding the redundancy, I see how that could be an issue. In general I agree with you that redundancy is good as it makes our code more robust, but as much as it pains me to say it performance should come first. I don't know how expensive those calculations are, though, so it might not hurt, but if they really are redundant and the matrices are updated when they need to be, it's good to keep them in mind; it's a good candidate for optimization down the line.

2023-02-15 11:12 UTC, markmeliaa commented on Source/DataModels/GameObject/GameObject.cpp
> +	childTransform->UpdateTransformMatrices();
`UpdateTransformMatrices` is a recursive function, and it goes as deep as how many children a gameobject has, so in some cases it could, in fact, hinder a little the performance of the engine.

What I've done is comment the `UpdateTransformMatrices` of the getters instead of deleting them so if we have any problem in the future we could just uncomment those and see what to do and where to relocate the calls to `UpdateTransformMatrices`, but for now it works fine without them (and maybe if no problems arise in the future we can delete the completely (?)).

2023-02-15 17:09 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +	childTransform->UpdateTransformMatrices();
Sounds great, thank you! Let me try to run the engine in my machine and I'll approve the pull reques :)

2023-02-15 17:51 UTC, markmeliaa commented
Done! It was trivial 😮‍💨

2023-02-15 22:31 UTC, gerard-queralt submitted a review, later dismissed
Sorry for the delay. Everything seems to run fine, thank you again for your work!

2023-02-21 18:15 UTC, markmeliaa commented
Closing this because something about the transforms is not working correctly when a new scene is loaded, I'll take a look at it.

2023-03-06 12:52 UTC, markmeliaa commented
Fixed, opening this again!

2023-03-06 16:15 UTC, gerard-queralt approved these changes
Thank you again!

2023-03-06 23:15 UTC, gerard-queralt approved these changes

2023-03-06 23:39 UTC, PaablooCH requested changes
Good job, just a few things

2023-03-06 23:39 UTC, PaablooCH commented on Source/DataModels/Components/ComponentTransform.cpp
> +	return globalPos;
have you considered making this function inline?

2023-03-06 23:39 UTC, PaablooCH commented on Source/DataModels/GameObject/GameObject.cpp
> +		(this->GetComponent(ComponentType::TRANSFORM));
this `this` is redundant

2023-03-07 12:26 UTC, markmeliaa commented on Source/DataModels/GameObject/GameObject.cpp
> +		(this->GetComponent(ComponentType::TRANSFORM));
q si pesao

2023-03-07 12:28 UTC, PaablooCH commented on Source/DataModels/GameObject/GameObject.cpp
> +		(this->GetComponent(ComponentType::TRANSFORM));
estos ataques hacia mi persona no hacen falta, btw no esta corregido

2023-03-07 12:33 UTC, PaablooCH submitted a review, later dismissed
finally well done

2023-03-07 12:38 UTC, markmeliaa commented on Source/DataModels/GameObject/GameObject.cpp
> +		(this->GetComponent(ComponentType::TRANSFORM));
ya está, contento?

2023-03-07 12:40 UTC, PaablooCH submitted a review, later dismissed
🇺🇸 : thank you marc
🇪🇸 : ya era hora macho

2023-03-07 13:13 UTC, PaablooCH approved these changes
🇬🇧 : nice changes with the warnings, seems all work fine
🇪🇸 : otra review más te busco y te encuentro

2023-03-07 13:14 UTC, markmeliaa commented
🇬🇧 : thanks for your words Pablo, and thank you for reviewing this multiple times
🇪🇸 : eres un puto pesao, dejame en paz, buscate una vida

2023-03-07 18:25 UTC, PaablooCH approved these changes
🇬🇧 : 😄
🇪🇸 : te avisé, estoy de camino a tu casa

2023-03-07 18:28 UTC, markmeliaa commented
🇬🇧 :  Thx for your patience.
🇪🇸 : Soy un pesado lo siento uwu

2023-03-10 18:49 UTC, gerard-queralt approved these changes
I feel like I'm going to put you in danger if I don't merge this...

2023-03-10 18:49 UTC, merged