fix[Quadtree]: task #865bubdbk
Horizons-Games/Axolotl-Engine pull request #164
Opened 2023-02-27 19:12 UTC by Dedado3000

Refactored Quadtree Remove and SmartRemove in order to fix some recursive problems

2023-02-27 19:12 UTC, PaablooCH commented
Task linked: [CU-865bubdbk Quadtree problems](https://app.clickup.com/t/865bubdbk)

2023-02-28 00:38 UTC, gerard-queralt requested changes

2023-02-28 00:38 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +	if (!components.empty())
As I said in the ticket, this could not have been the cause of the bug, since iterator loops don't require a previous check, like all other loops. You can try it yourself: removing the `if` clause still allows for GameObject to be deleted from the hierarchy. I think it's better if we remove this `if`.

2023-02-28 00:46 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +	if (!components.empty())
I've detected another bug while testing, but it's a different one from the one reported by the ticket. I'll create an issue.

2023-02-28 13:43 UTC, OriolSors commented on Source/DataStructures/Quadtree.cpp
>  		ResetChildren();
The splice method or the ResetChildren?

2023-02-28 13:46 UTC, Dedado3000 commented on Source/DataStructures/Quadtree.cpp
>  		ResetChildren();
Fuck, that was a comment of gerard that i forget to remove

2023-02-28 13:46 UTC, OriolSors commented on Source/DataStructures/Quadtree.cpp
>  		ResetChildren();
Okey jajajajaja

2023-02-28 13:54 UTC, OriolSors commented on Source/DataStructures/Quadtree.cpp
>  	}
We no longer need the OptimizeParentObjects() function.

2023-02-28 13:56 UTC, OriolSors requested changes
If you agree we can delete the function I commented @Dedado3000

2023-02-28 14:03 UTC, gerard-queralt approved these changes
Everything looks good to me, resolve Oriol's request and we can merge.

2023-02-28 16:53 UTC, merged