fix: problem with GetComponent
Horizons-Games/Axolotl-Engine pull request #170
Opened 2023-02-28 14:05 UTC by PaablooCH

when creating the scene all gameobjects go to vector sceneCamera provoking that when we search for objects inside camera we take those objects as cameras

2023-02-28 14:06 UTC, PaablooCH commented
Task linked: [CU-865bubdex Problem with GetComponent](https://app.clickup.com/t/865bubdex)

2023-02-28 15:01 UTC, gerard-queralt submitted a review, later dismissed
Nice catch, this will certainly help improve the performance of the Engine. I have to say, though, that this does not solve the bug you found. The only reason it doesn't happen anymore is because there no longer are any cameras in the scene, so the loop where the crash occurs is never accessed. If you do a quick modification to `WindowInspector` to be able to add a Camera Component to an object, you can easily still trigger the bug: just add one camera to a parent and its child and then remove the parent. This looks like it's related to either #166 or #167, or both.

2023-02-28 15:02 UTC, gerard-queralt commented
This is the addition I did, in case you want to try it in you machine:
![image](https://user-images.githubusercontent.com/79362519/221892781-40c369be-5d6d-481b-9c02-61799757d715.png)
For easy copy-pase:
```
if (ImGui::MenuItem("REMOVE: Add camera"))
{
	App->scene->GetSelectedGameObject()->CreateComponent(ComponentType::CAMERA);
	auto debug = App->scene->GetLoadedScene()->GetSceneCameras();
	debug.push_back(App->scene->GetSelectedGameObject());
	App->scene->GetLoadedScene()->SetSceneCameras(debug);
}
```

2023-02-28 16:13 UTC, gerard-queralt commented
This has nothing to do with memory leaks, this is an issue of the timing of GameObjects and Components deletition, which ends up causing code to run on garbage memory. Also, please report whatever bug you found so we can all be up to date. And this MR is perfectly fine as is, you fixed an error with scene deserialization, so no need to close it.

2023-02-28 16:25 UTC, PaablooCH commented
I insist, the problem with the memory leak affects also this scope what you are talking (GameObjects and Components deletition) i dont want to push something that solves half of the problem, so this pr will be closed until i found a solution that could be solf the whole problem. Thanks you for your comprehension
P.S.: later on i will write about the memory leak problem

2023-03-01 15:20 UTC, PaablooCH commented
See issue #169 for what is solved

2023-03-02 12:34 UTC, markmeliaa requested changes
Tried deleting a parent when I have a child selected, and the engine still breaks:
![image](https://user-images.githubusercontent.com/82601780/222427310-9e43711d-c57c-4212-845e-7925117ddaf0.png)

It is trying to call the BoundingBox of a deleted GameObject:
![image](https://user-images.githubusercontent.com/82601780/222427561-4f8d4f99-4560-4472-9e24-5e2530af9457.png)

I don't remember if this is what this pull request was trying to fix but I think that it enters in the scope of `problems deleting gameobjects with children` so I guess it should be addressed here too.

Also, when deleting a parent gameobjects, their children are still not correctly deleted, check out, after deleting anything from `mini_lights` scene:
![image](https://user-images.githubusercontent.com/82601780/222429219-c4e27dd5-7d2b-48d5-889f-cf6b5b89d93c.png)

And this is the result when I delete the wall (with Wall_0 and Wall_1 as children):
![image](https://user-images.githubusercontent.com/82601780/222429518-fba54687-f49a-484e-871a-443204f5d974.png)

The children of Wall remain like this in the vector:
![image](https://user-images.githubusercontent.com/82601780/222429873-2e340e18-e937-4c44-bd91-a4a5f5bdde23.png)

So the functions created in this pull request that remove the children from the parent are not working somehow...

I see the other issues addressed in #169 correctly resolved.

2023-03-02 12:34 UTC, markmeliaa commented on Source/DataModels/Scene/Scene.cpp
> +	RemoveFromCamera(father);
When a GameObject is deleted, you don't chech if it's a camera or not before removing it from cameras, why that?

2023-03-02 12:54 UTC, markmeliaa commented
Wait, nevermind the first error that I reported, forgot that we fixed it in #172.

2023-03-02 13:00 UTC, gerard-queralt commented
If this were the cause of this issue it would crash everytime we delete something, as it stands it seems to crash randomly on develop. We certainly need to clear the various collections in the engine when deleting, but again, I seriously doubt this is what's causing that. Regardless, I think a better way of doing this would be to exploit the deleters of smart pointers. What you did here would need to be replicated in the Quadtree, and also do a similar thing for Components and Resources. Hopefully you see why I don't consider this the best approach. I talked a bit about this in #166

2023-03-02 14:07 UTC, markmeliaa commented on Source/DataModels/Scene/Scene.cpp
> +	RemoveFromCamera(father);
There isn't a flag per se, but if a GameObject is a camera, it has a `CameraComponent` attached to it, so that is how you could differentiate them. Just search if the GameObject has a `ComponentCamera` before removing, if it does, delete that GameObject from the camera vector too, if it does not, do nothing.

2023-03-02 15:19 UTC, PaablooCH commented on Source/DataModels/Scene/Scene.cpp
> +	RemoveFromCamera(father);
Good catch, but while i was implementing it i saw that if we delete the component Camera we no longer can track by this solution, because the camera will remain inside cameraScene but we can not ensure that the gameobject is a camera

2023-03-02 17:57 UTC, markmeliaa approved these changes

2023-03-02 18:09 UTC, PaablooCH commented
> > Good catch, but while i was implementing it i saw that if we delete the component Camera we no longer can track by this solution, because the camera will remain inside cameraScene but we can not ensure that the gameobject is a camera
> 
> Wait, `ComponentCamera` should not have the option to be removed, its `canBeRemoved` variable is set to `false`, so the Remove Comp. button should not appear in the ImGui.

Seems that something happens, because the button is available to delete the component
![image](https://user-images.githubusercontent.com/62140600/222513845-7174d86b-33b8-4e42-9606-7574afb0981a.png)

2023-03-02 18:14 UTC, markmeliaa commented
Okay, looks like when the component windows were decoupled from the Component::Draw() the `canBeRemoved` functionality was not taken into account, let me open an issue for this.

2023-03-02 18:17 UTC, markmeliaa commented
Done, addressed in #176

2023-03-02 19:41 UTC, PaablooCH commented
> If this were the cause of this issue it would crash everytime we delete something, as it stands it seems to crash randomly on develop. We certainly need to clear the various collections in the engine when deleting, but again, I seriously doubt this is what's causing that. Regardless, I think a better way of doing this would be to exploit the deleters of smart pointers. What you did here would need to be replicated in the Quadtree, and also do a similar thing for Components and Resources. Hopefully you see why I don't consider this the best approach. I talked a bit about this in #166

it's true that crash randomly but only in the last scene, if you load the first one it happens on every father that you want to delete (forget floor it crashes always but for different reasons). I don't see why using the deleters of smart pointers would improve the solutions, having in mind that the problem was that we not clear the vectors, what is the solution that you propose?

2023-03-02 21:52 UTC, gerard-queralt commented
Thank you for pointing out another way to force the crash, the more information we have the better. And sorry if I didn't explain myself properly, I'll try to lay out my idea. I'll try to keep it short.
The definition of a smart pointer like `std::unique_ptr<A>()` is actually hiding another template argument that the class has. If you hover over it, you will notice that it's setting an argument with type [std::default_delete\<A\>](https://en.cppreference.com/w/cpp/memory/default_delete). In the documentation, you can see that this is basically a class that calls `delete a` internally.
![image](https://user-images.githubusercontent.com/79362519/222561440-ce7302f6-d7d2-406c-9dd5-0529800e066c.png)
What I would like to do is to actually set the deleter that we want to use, and use a struct that we define. That is were we would call the removal from the collections. By doing it this way, our solution would be more modular - as I said, what you did here is perfectly correct, but would need to be replicated in Quadtree, and potentially other places, and the same thing will need to happen with other classes like Resource, which will remain in the map inside ModuleResources. Another advantatge is that we would de-couple the objects from the classes that contain them: a GameObject won't need to know in which Quadtrees it's present, or whether it's in ModuleRender's `renderList`, etc., which is related to the fact that it would be more modular.
To give you an idea of what I have in mind, this is a small prototype that I came up with a few weeks ago:
```
template<typename P>
class CollectionAwareDeleter
{
public:
	CollectionAwareDeleter(std::vector<P*>& collectionToManage) : collectionToManage(collectionToManage)
	{
	}
	~CollectionAwareDeleter() = default;

	void operator() (P* p)
	{
		collectionToManage.erase(std::remove(std::begin(collectionToManage), std::end(collectionToManage), p));
		delete p;
	}

private:
	std::vector<P*>& collectionToManage;
};
```
And this is how it could be used:
```
unique_ptr<A, CollectionAwareDeleter<A>> ptrA = unique_ptr<A, CollectionAwareDeleter<A>>(new A(), CollectionAwareDeleter<A>(rawPtrVector));
```
This sort of thing is already used in [ModuleScene](https://github.com/Horizons-Games/Axolotl-Engine/blob/develop/Source/Modules/ModuleWindow.h#L58) and [ModuleInput](https://github.com/Horizons-Games/Axolotl-Engine/blob/develop/Source/Modules/ModuleInput.h#L77), where we have unique pointers to SDL structs that need to be deleted in a particular way.
Hopefully I explained myself properly. Again, it's not that your solution is bad by any means, but hopefully you see why I think this would be easier to use in the long term.

2023-03-06 12:51 UTC, markmeliaa submitted a review, later dismissed

2023-03-06 12:59 UTC, markmeliaa approved these changes
Nice last change, good job! (Basta ya, estoy harto de esta pr...)

2023-03-06 16:16 UTC, gerard-queralt approved these changes

2023-03-06 16:17 UTC, merged