fix[WindowsHierarchy]: task #865buw83b
Horizons-Games/Axolotl-Engine pull request #172
Opened 2023-02-28 15:44 UTC by markmeliaa

ClickUp task: https://app.clickup.com/t/865buw83b

2023-02-28 15:44 UTC, PaablooCH commented
Task linked: [CU-865buw83b Bug: Destruction of a Father of selected GameObject](https://app.clickup.com/t/865buw83b)

2023-02-28 16:24 UTC, gerard-queralt requested changes
Also, the items in the Hierarchy can't be minimized now, please take a look

2023-02-28 16:24 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +    if (ImGui::IsItemClicked() || ImGui::IsItemClicked(1) || (ImGui::IsMouseClicked(1) && ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup)))
Several things regarding this line:
- I'm not sure what the last condition (`MouseClicked` && `ItemHovered`) does, I tried removing it and didn't notice anything. Could you explain why it's necessary?
- Try to use `ImGuiMouseButton` enum instead of integers, so it's easier to read what's actually being checked
- The line is more than 120 columns long, so try to split it please

2023-03-03 20:25 UTC, DADSILVER commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +    if (ImGui::IsItemClicked() || ImGui::IsItemClicked(1) || (ImGui::IsMouseClicked(1) && ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup)))
The flag ImGuiHoveredFlags_AllowWhenBlockedByPopup for ItemHovered is necessary to update de popup state when you press in otherobject with the right click.

2023-03-03 23:14 UTC, gerard-queralt approved these changes

2023-03-05 17:25 UTC, AuxPort66 approved these changes

2023-03-05 17:25 UTC, merged