feat [mouse_pickgin]: Imguizmo implemented
Horizons-Games/Axolotl-Engine pull request #174
Opened 2023-03-01 22:34 UTC by MacXxs

Functionalities added:
- Hability to modify transforms directly with the gizmo
- Being able to use snapping and change its values in the x, y, and z axis
- Changing between Local and World modes to apply transformations
- Added a viewManipulator on the top right corner of the scene to snap directly on the axis selected from the manipulator (relative to where the camera is pointing)

2023-03-02 13:08 UTC, markmeliaa requested changes
I already told you but nice work with the ImGuizmo Miki!

The only "complain" that I have is that the ImGuizmo section is too long to fit in the screen (at least in mine), so we could remove the Mouse Coords of there if they are not really needed so everything fits alright even in small screens, what do you say?

![image](https://user-images.githubusercontent.com/82601780/222435185-258bab86-275a-417e-ad9c-47bb25f09b66.png)

Oh, and I just found a bug trying this branch out, it is the same bug that it was reported for the 'scenemanagement' branch in the ClickUp (https://app.clickup.com/t/865bujq80), it seems to happen when a new scene is loaded after changing how the matrices work in the `ComponentTransform` files, so maybe that bug should be fixed before merging this.

2023-03-02 15:40 UTC, PaablooCH requested changes
Good job Miki, one thing apart the code, if you move something with the arrows or the "squares" while there is something behind, the mousepicking selects that object, losing the first

2023-03-02 15:40 UTC, PaablooCH commented on Source/Modules/ModuleEngineCamera.cpp
> +	return &this->frustum;
"this" is not necessary

2023-03-02 15:40 UTC, PaablooCH commented on Source/Modules/ModuleEngineCamera.cpp
> +			return false;
the else is not necessary, you can put the return outside and will execute

2023-03-02 17:37 UTC, MacXxs commented on Source/Modules/ModuleEngineCamera.cpp
> +	return &this->frustum;
yeah true, I have the bad habit of using it, i'll remove it!

2023-03-02 17:37 UTC, MacXxs commented on Source/Modules/ModuleEngineCamera.cpp
> +			return false;
true!

2023-03-04 16:47 UTC, PaablooCH approved these changes
I see all good, nice work

2023-03-05 17:10 UTC, gerard-queralt approved these changes
Thank you Miki, looks awesome!

2023-03-05 18:12 UTC, PaablooCH approved these changes

2023-03-06 12:09 UTC, markmeliaa approved these changes
Nice Miki, good job!

2023-03-06 12:09 UTC, merged