Light Intensity capped at 8 in order create over bright lights
Horizons-Games/Axolotl-Engine pull request #183
Opened 2023-03-03 22:55 UTC by sncarbo

2023-03-03 23:15 UTC, AlexisDieu approved these changes

2023-03-04 14:32 UTC, OriolSors commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
> +
Good! Without this conditional we could modify the value by typing!

2023-03-04 14:32 UTC, OriolSors approved these changes
Fine change Santi! Thanks!

2023-03-04 16:54 UTC, PaablooCH requested changes
Nice catch, especially with the ifs as oriol says, just one thing:

2023-03-04 16:54 UTC, PaablooCH commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
> +				if (intensity > 8.0f)
All the ifs must be with {}, following the programming rules

2023-03-04 17:00 UTC, sncarbo commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
> +
Exactly! `DragFloat` does not allow to set a minimum and maximum limit if you enter the text by hand, which I think they should change!

2023-03-04 17:02 UTC, sncarbo commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
> +				if (intensity > 8.0f)
Absolutely right! I'll change it immediately. I also take this as an opportunity to set the limit to zero and avoid negative numbers in the light intensity.

2023-03-04 17:05 UTC, PaablooCH commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
> +				if (intensity > 8.0f)
Perf

2023-03-04 17:12 UTC, PaablooCH approved these changes

2023-03-04 17:12 UTC, sncarbo commented
I applied the requested changes! Thanks @OriolSors and @PaablooCH for being helpful!

2023-03-04 17:46 UTC, OriolSors reviewed
Great!

2023-03-05 12:45 UTC, OriolSors submitted a review, later dismissed

2023-03-05 16:02 UTC, MacXxs commented
Hi Santi, everything looks fine, but i wouldn't put such a low cap on the light intensity. For example unity has no cap (it can be infinit), and it actually makes sense 'cause only close objects to the light will look burnt on higher intensities, but if the light is enough far away, even at a 100 intenisity the scene can look alright, so actually i would move to cap from 8 to 500 per example, or even 5000!

On top of that, maybe we should add this top cap as a #default value in the ComponentLight class, so we can change it from there instead having to change it manually from every function on the windowComponent classes.

![image](https://user-images.githubusercontent.com/18547655/222971394-02e1fc6d-a4f6-4434-b4a4-65156f0c504d.png)

2023-03-05 16:04 UTC, MacXxs requested changes

2023-03-05 16:04 UTC, MacXxs commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
Hi Santi, everything looks fine, but i wouldn't put such a low cap on the light intensity. For example unity has no cap (it can be infinit), and it actually makes sense 'cause only close objects to the light will look burnt on higher intensities, but if the light is enough far away, even at a 100 intenisity the scene can look alright, so actually i would move to cap from 8 to 500 per example, or even 5000!

On top of that, maybe we should add this top cap as a #default value in the ComponentLight class, so we can change it from there instead having to change it manually from every function on the windowComponent classes.

![image](https://user-images.githubusercontent.com/18547655/222971394-02e1fc6d-a4f6-4434-b4a4-65156f0c504d.png)

2023-03-05 16:27 UTC, sncarbo commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
Perfect! I'm going to change it. I will add a `protected` `const static float` in `WindowComponentLight` so that its children can access it.

2023-03-05 16:35 UTC, sncarbo commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
I just saw that there is no inheritance between WindowComponentPointLight, WindowComponentDirLight and WindowComponentSpotLight with WindowComponentLight, so I will do it another way, although I think that should have inheritance.

2023-03-05 16:42 UTC, MacXxs commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
Hi, adding the define on the ComponentLight class should be enough. Like this:

![image](https://user-images.githubusercontent.com/18547655/222973773-f31991ed-a930-4195-9c17-fb2387e45794.png)

2023-03-05 16:47 UTC, MacXxs commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
Then you should be able to call it normally on the WindowComponent for each light, 'cause it's a value stablished on the parent of the lights, and each of its child classes are imported on the window.

![image](https://user-images.githubusercontent.com/18547655/222974098-f9ae5aa2-9832-4a92-b361-6e5564237cef.png)

2023-03-05 17:02 UTC, sncarbo commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
I am not a big fan of using macros for this particular case because a macro does not respect any kind of scope. Also, macros are very dependent on the compiler configuration. It is fine to use them if they are macros used throughout the system, but some members, as in this case, must be encapsulated.

2023-03-05 17:11 UTC, MacXxs commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPointLight.cpp
> +			if (ImGui::DragFloat("##Intensity", &intensity, 0.01f, 0.0f, 8.0f))
Okey, if it's better, for me it's okey adding inheritance, as long as adding the extra includes isn't worse than simply using the macro, it's fine by me!

2023-03-05 17:11 UTC, MacXxs submitted a review, later dismissed

2023-03-05 17:16 UTC, PaablooCH submitted a review, later dismissed

2023-03-05 17:32 UTC, sncarbo commented
I made one last change to replace 'const' with 'constexpr' to avoid reserving memory. @PaablooCH @MacXxs @OriolSors @AlexisDieu

2023-03-05 17:53 UTC, MacXxs approved these changes

2023-03-05 18:25 UTC, merged