Efficient rendering program corrections
Horizons-Games/Axolotl-Engine pull request #201
Opened 2023-03-12 20:20 UTC by DADSILVER

Modified how the rendering program is managed so that it works as the rest.

2023-03-13 12:53 UTC, PaablooCH approved these changes
works fine!!

2023-03-13 21:51 UTC, gerard-queralt requested changes
Commented a few small things, but otherwise great changes!

2023-03-13 21:51 UTC, gerard-queralt commented on Source/Modules/ModuleProgram.h
> +	void UpdateProgram(std::string& vtxShaderFileName, std::string& frgShaderFileName, int programType,
This parameters can probably be const references

2023-03-13 21:51 UTC, gerard-queralt commented on Source/Modules/ModuleProgram.h
> +		return programs[static_cast<int>(type)].get();
Should probably check the recieved type is not PROGRAM_TYPE_SIZE

2023-03-13 21:51 UTC, gerard-queralt commented on Source/DataModels/Program/Program.cpp
> +void Program::Desactivate()
"Desactivate" is not a word, should be "Deactivate". Sorry to be picky :P

2023-03-14 16:11 UTC, DADSILVER commented on Source/DataModels/Program/Program.cpp
> +void Program::Desactivate()
Oky

2023-03-14 17:51 UTC, gerard-queralt approved these changes
Thank you David!

2023-03-17 17:15 UTC, PaablooCH approved these changes

2023-03-17 17:16 UTC, merged