feat[Undo-Redo]
Horizons-Games/Axolotl-Engine pull request #202
Opened 2023-03-13 19:33 UTC by DGMC117

This initial implementation of the functionality has a new module (ModuleCommand) and the implementation of the undo command for DrawEnableComponent.

2023-03-17 12:22 UTC, markmeliaa requested changes
First of all, this should be updated with develop asap, as there are some things that have changed (and with this I mean bring develop to this branch, not just fixing the conflicts that this pr has).

Everything else is correct, I've checked the functionality and works as intended when enabling and disabling components, great job!

2023-03-17 12:22 UTC, markmeliaa commented on Source/DataModels/Commands/CommandComponentEnabled.h
> +{}
If, in the future, `ComandComponentEnabled` requires a .cpp, this constructor and destructor should be moved to the .cpp, as that is what the programming rules say.

2023-03-17 12:22 UTC, markmeliaa commented on Source/Modules/ModuleCommand.h
> +void ModuleCommand::CreateAndExecuteCommand(Args&& ...args)
Shouldn't this function be in the .cpp instead of in the .h?

2023-03-19 19:23 UTC, PaablooCH requested changes
I dont find any problem, just one thing:

2023-03-19 19:23 UTC, PaablooCH commented on Source/Engine.vcxproj.user
> +    <ShowAllFiles>true</ShowAllFiles>
before merge change that variable to false again, you only have to push but deactivating 
this -> ![image](https://user-images.githubusercontent.com/62140600/226203341-a1eb0a0d-74e9-48c9-b287-314b7dc08ff9.png)

2023-03-19 22:28 UTC, gerard-queralt commented on Source/Modules/ModuleCommand.h
> +void ModuleCommand::CreateAndExecuteCommand(Args&& ...args)
Template functions can't be in the .cpp file, unfortunately.

2023-03-19 22:32 UTC, gerard-queralt commented on Source/Engine.vcxproj.user
> +    <ShowAllFiles>true</ShowAllFiles>
This file should be in the `.gitignore`, not sure why it was tracked anyway.

2023-03-19 22:44 UTC, gerard-queralt reviewed
Left a couple questions, but overall great job! This will be a great addition to the engine :)

2023-03-19 22:44 UTC, gerard-queralt commented on Source/DataModels/Commands/CommandComponentEnabled.h
> +	bool desiredValue;
What's the difference between `enable` and `desiredValue`, and why is the first one a pointer to a boolean?

2023-03-19 22:44 UTC, gerard-queralt commented on Source/DataModels/Commands/CommandComponentEnabled.h
> +std::unique_ptr<Command> CommandComponentEnabled::Execute()
Wouldn't it be easier to do
```
if (...)
else ...
std::unique_ptr<CommandComponentEnabled> reverse = std::make_unique<CommandComponentEnabled>(comp, enable, !desiredValue);
return reverse;
```

2023-03-20 11:39 UTC, markmeliaa commented on Source/Modules/ModuleCommand.h
> +void ModuleCommand::CreateAndExecuteCommand(Args&& ...args)
rip, alright then.

2023-04-15 16:53 UTC, PaablooCH approved these changes

2023-04-15 18:09 UTC, gerard-queralt commented on Source/DataModels/Commands/CommandComponentEnabled.h
> +	delete comp;
This will cause a double deletition of the pointer, since this Component is managed by a unique pointer somewhere else. I could be wrong, but I'm pretty sure this will cause an error when running it.

2023-04-15 19:39 UTC, PaablooCH approved these changes

2023-04-16 16:06 UTC, PaablooCH approved these changes

2023-04-16 16:07 UTC, DGMC117 commented on Source/DataModels/Commands/CommandComponentEnabled.h
> +	bool desiredValue;
This has been fixed. After discussing we saw that the pointer was incorrect.

2023-04-16 18:17 UTC, markmeliaa approved these changes

2023-04-16 18:19 UTC, merged