Static/Player Camera
Horizons-Games/Axolotl-Engine pull request #207
Opened 2023-03-16 13:45 UTC by Dedado3000

All implementation of player camera basic.

Full implementation of Static Player.

How it works:
When you open in game mode it will search for a player to the game to spawn.
To have a player you need to give an object the componentPlayer and add a child that is a camera.
Controls: 
WASD: move player (only when camera player asigned)
Mouse: Rotate left-right
1: previous camera
2: next camera
3: select camera player
4: select god camera

2023-03-16 19:31 UTC, OriolSors commented on Source/Modules/ModuleCamera.cpp
> +							-1
Cambiame esto por favor es muy ilegible xddddd repite la declaración segun el if jajjajajaj

2023-03-16 19:33 UTC, OriolSors commented on Source/Application.cpp
> +#ifndef ENGINE
Por que no has puesto directamente ifdef GAME? @Dedado3000

2023-03-16 19:44 UTC, OriolSors commented on Source/Modules/ModulePlayer.cpp
> +			cameraPlayer = (static_cast<ComponentCamera*>(camera->GetComponent(ComponentType::CAMERA)))->GetCamera();
```suggestion
			cameraPlayer = static_cast<ComponentCamera*>(camera->GetComponent(ComponentType::CAMERA))->GetCamera();
```

2023-03-16 20:13 UTC, OriolSors submitted a review, later dismissed
Good camera refactor and new Player module! If you can check the details I commented @Dedado3000

2023-03-16 23:16 UTC, Dedado3000 commented on Source/Application.cpp
> +#ifndef ENGINE
Porque solo tenemos jugador si el engine no esta definido

2023-03-16 23:26 UTC, Dedado3000 commented on Source/Modules/ModuleCamera.cpp
> +							-1
no me dejais expresar de la manera mas bizarra posible, estáis atentando contra mi creatividad

2023-03-17 12:53 UTC, markmeliaa requested changes
Nice changes, good job.

PD: is it normal that the textures flicker a bit when moving the player around the scenary?

2023-03-17 12:53 UTC, markmeliaa commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPlayer.cpp
> +	DrawEnableAndDeleteComponent();
Idk why but, when drawing the `PlayerComponent` Subwindow in the inspector, the `ImGui::Separator()`that is supposed to appear at the end of each component, in this case appears at the beginning, please take a look as it appears strange in the inspector window with all the other components.

2023-03-17 12:53 UTC, markmeliaa commented on Source/Modules/ModulePlayer.cpp
> +		trans->SetRotation( newRot);
```suggestion
		trans->SetRotation(newRot);
```

2023-03-17 12:53 UTC, markmeliaa commented on Source/Modules/ModulePlayer.cpp
> +	//Left
```suggestion

	//Left
```

2023-03-17 14:43 UTC, OriolSors commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPlayer.cpp
> +	DrawEnableAndDeleteComponent();
Nice catch, now I can see this too. It appears at the end of the Header but not in the end of the Component Window content.

2023-03-17 14:50 UTC, OriolSors commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPlayer.cpp
> +	DrawEnableAndDeleteComponent();
I realize what it happens. It is because the `DrawEnableAndDeleteComponent()` method uses the `SameLine()` and then there isn't more content to show in this `WindowComponentPlayer`. So, the `ImGui::Separator()` is displayed at same line. For avoiding this, you can use the follow code suggestion:
```suggestion
	DrawEnableAndDeleteComponent();
	ImGui::Text("");
```

2023-03-18 22:00 UTC, OriolSors approved these changes

2023-03-18 23:28 UTC, markmeliaa approved these changes

2023-03-18 23:28 UTC, merged