fix: Camera Focus movement and rotation not aligned
Horizons-Games/Axolotl-Engine pull request #213
Opened 2023-03-19 17:52 UTC by OriolSors

Now that the Camera refactor is finally done, I solved this bug which appeared during the Concept Discovery.

- The problem was that the Focus stops at the frame when the final rotation is achieved. This has been aligned also with position and its Lerp.
- I modified the Slerp algorithm for not needing the current rotation and only use the current front direction.
- The speed has been adjusted too.

2023-03-19 18:25 UTC, AlexisDieu submitted a review, later dismissed
The focus is working correctly now good job ! the speed also look more interesting like that and i don't find any trouble !

2023-03-19 18:44 UTC, PaablooCH requested changes
Very smooth, i found just one thing:
if you rotate focusing an object sometimes the camera does a jump and rotate like 180º
![camera-rotation](https://user-images.githubusercontent.com/62140600/226199674-9a374433-5a33-4fb9-9d80-82b5b7c44221.gif)

2023-03-19 18:44 UTC, PaablooCH commented on Source/DataModels/Camera/Camera.h
> +	void SetLookAt(const float3& lookAt, bool& isSameRotation);
like the float is not necessary to pass the bool by reference

2023-03-19 18:44 UTC, PaablooCH commented on Source/DataModels/Camera/CameraEngine.cpp
> +	if (isSamePosition && isSameRotation) isFocusing = false;
following the programming rules that must be between {}

2023-03-19 18:55 UTC, AlexisDieu commented
> Very smooth, i found just one thing:
> if you rotate focusing an object sometimes the camera does a jump and rotate like 180º
> ![camera-rotation](https://user-images.githubusercontent.com/62140600/226199674-9a374433-5a33-4fb9-9d80-82b5b7c44221.gif)

For this issue it’s maybe more an issue with the mouse wrap so I am gonna look at it because this bug is kinda rare tbh I tried to re try it and it never happened again

2023-03-19 19:00 UTC, OriolSors commented
> Very smooth, i found just one thing: if you rotate focusing an object sometimes the camera does a jump and rotate like 180º ![camera-rotation](https://user-images.githubusercontent.com/62140600/226199674-9a374433-5a33-4fb9-9d80-82b5b7c44221.gif) [ ![camera-rotation](https://user-images.githubusercontent.com/62140600/226199674-9a374433-5a33-4fb9-9d80-82b5b7c44221.gif) ](https://user-images.githubusercontent.com/62140600/226199674-9a374433-5a33-4fb9-9d80-82b5b7c44221.gif) [ ](https://user-images.githubusercontent.com/62140600/226199674-9a374433-5a33-4fb9-9d80-82b5b7c44221.gif)

As @AlexisDieu has said, this is due to the Mouse Warp and it's out of this scope

2023-03-19 19:02 UTC, OriolSors commented on Source/DataModels/Camera/Camera.h
> +	void SetLookAt(const float3& lookAt, bool& isSameRotation);
I pass by reference because I modify the variable inside, not for efficiency

2023-03-19 19:03 UTC, OriolSors commented on Source/DataModels/Camera/CameraEngine.cpp
> +	if (isSamePosition && isSameRotation) isFocusing = false;
Done

2023-03-19 22:35 UTC, PaablooCH commented
> As @AlexisDieu has said, this is due to the Mouse Warp and it's out of this scope

Okey 👍, so all good

2023-03-19 22:36 UTC, PaablooCH approved these changes

2023-03-20 17:35 UTC, MacXxs approved these changes
Everything looks fine!

2023-03-20 18:04 UTC, merged