feat: added state to windows through meta's files
Horizons-Games/Axolotl-Engine pull request #215
Opened 2023-03-19 21:15 UTC by elbuho12Jesus

The metafiles were created to read when the engine starts with the previous window states and to write when the engine closes the last window states.

2023-03-19 22:23 UTC, gerard-queralt requested changes
Left some comments regarding coding style and general engine workflow considerations. Also, I can't run this branch on my computer because it's trying to read non-existant meta files. If you delete your local `Lib` folder you'll be able to reproduce it. Left a suggestion on what the issue might be.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/EditorWindow.cpp
> +		size_t i = buffer.find("State");
You can probably do `enabled = json["State"]` instead of all of this.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/EditorWindow.cpp
> +		json["Type"] = "Window";
Why do we need a `UID` and `Type` fields if we are not using them in de-serialization?

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/SubWindow.cpp
> +	enabled = defaultEnabled;
With your changed, the `defaultEnabled` variable can be removed. It was only used as a default parameter for these classes `Draw` method, but now the method doesn't have a parameter.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/Window.h
> +	bool enabled;
Class members should be private and accessed with getter and setter functions.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +	enabled = defaultEnabled;
As said above, `defaultEnabled` is not needed

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +		enabled = !showAbout;
This looks wrong, though I cannot test it because I can't run your branch. To me, this reads like you are enabling/disabling the entire main menu when the "About" button is pressed, which is not the intended behaviour.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.h
> +	void SetWindowEnabled(int windowIndex, bool &enabled);
Not sure if this is needed anymore, since now we keep a reference instead of a regular value

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.h
> +	windowNamesAndEnabled[windowIndex].second.get() = &enabled;
If this method ends up being necessary, this is wrong. Should be
```
windowNamesAndEnabled[windowIndex].second = enabled;
```
I'm not sure what your code is doing exactly in terms of the `referece_wrapper`, but it's modifying it instead of setting a new one, which might have side-effects. Better to use it as is intended.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Resources/Resource.h
> +	Window,
You have declared a new type of ResourceType, but not actually created a Resource class, which most likely means a new type of Resource is not needed. Resources should be something used by the game, like textures and meshes.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/FileSystem/ModuleResources.cpp
> +		return "StateWindow";
As said in an earlier comment, resources should be things used by the game, which the windows are not. Your config files should not be placed in Assets and Lib. I think it'd be better to create a new Config folder inside Game for that, but maybe there's a better option.

2023-03-19 22:23 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.cpp
> +	for (int i = 0; i < windows.size(); ++i) {
Bracket should be in the line below

2023-03-19 22:23 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.cpp
> +	for (int i = 0; i < windows.size(); ++i) {
Bracket should be in the line below

2023-03-19 22:23 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/EditorWindow.cpp
> +	if (App->fileSystem->Load(lib.c_str(), binaryBuffer) > 0) {
This doesn't seem to detect if the file was read. Use `ModuleFileSystem::Exists` instead

2023-03-19 23:13 UTC, gerard-queralt commented
Thinking more about this, wouldn't it be easier to serialize and store the dictionary in `WindowMainMenu`? And you could pass that Json as a constructor parameter instead of the current vector of windows, and then save it in `ModuleEditor::CleanUp`. This would require almost no changes to the current structure, though it might have some downsides that I'm not thinking of.

2023-03-20 19:28 UTC, elbuho12Jesus commented on Source/DataModels/Windows/EditorWindows/EditorWindow.cpp
> +		json["Type"] = "Window";
> Thinking more about this, wouldn't it be easier to serialize and store the dictionary in `WindowMainMenu`? And you could pass that Json as a constructor parameter instead of the current vector of windows, and then save it in `ModuleEditor::CleanUp`. This would require almost no changes to the current structure, though it might have some downsides that I'm not thinking of.

I don't quite understand what you mean, do you suggest that I don't load WINDOWS in `WindowMainManu.cpp` but JSONS?

2023-03-31 02:10 UTC, closed without merging