Adding Wireframe mode and other options to debug mode
Horizons-Games/Axolotl-Engine pull request #216
Opened 2023-03-20 13:07 UTC by totisama

2023-03-21 16:39 UTC, AuxPort66 submitted a review, later dismissed

2023-03-25 20:49 UTC, gerard-queralt requested changes
Left some comments regarding the use of unique pointers,

2023-03-25 20:49 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.h
> +	const std::unique_ptr<WindowDebug>* GetDebugOptions() const;
This is a pointer to a unique pointer, which doesn't make sense. 
```suggestion
const std::unique_ptr<WindowDebug> GetDebugOptions() const;
```
All the calls to `get()` can be removed as well. So, instead of doing `App->editor->GetDebugOptions()->get()->...` you should do `App->editor->GetDebugOptions()->...`

2023-03-25 20:49 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.h
> +	return &debugOptions;
Once you change the member, this should be
```suggestion
return debugOptions.get();
```
And update the method signature to return a raw pointer.

2023-03-26 14:38 UTC, gerard-queralt approved these changes

2023-03-26 15:39 UTC, AuxPort66 approved these changes

2023-03-26 15:40 UTC, merged