Feat Engine Utility ctrl_c, ctrl_v, ctrl_d and ctrl_x
Horizons-Games/Axolotl-Engine pull request #218
Opened 2023-03-20 20:32 UTC by DADSILVER

Copy, paste, cut and duplicate functions are added. Right now they can only be done with a single GameObject.

2023-03-21 12:52 UTC, markmeliaa requested changes
Some issues that I had while trying out this branch:
- The Ambient Light and the Directional Light should not be duplicated or deleted, as they are (for now), unique to each scene.
- When a GameObject with children is duplicated (either with CtrlD or CtrlV) when one of the child is selected, this same child is selected in all the GameObjects that were duplicated (and deleting that child breaks the engine).
- When closing the engine after having duplicated some objects, the engine breaks when shutting down.

Everything else worked correctly as far as I tried (sorry for this exhaustive review).

2023-03-21 12:52 UTC, markmeliaa commented on Source/DataModels/Scene/Scene.cpp
> +GameObject* Scene::CreateGameObject(const char* name, GameObject* newObject, GameObject* parent)
```suggestion
GameObject* Scene::DuplicateGameObject(const char* name, GameObject* newObject, GameObject* parent)
```

2023-03-21 12:52 UTC, markmeliaa commented on Source/DataModels/Scene/Scene.cpp
> +GameObject* Scene::CreateGameObject(const char* name, GameObject* newObject, GameObject* parent)
Naming this function the same as the one that we already have that creates empty GameObjects may be a bit misleading, as this does not create a GameObject but rather duplicates one that already exists.

2023-03-21 12:52 UTC, markmeliaa commented on Source/Modules/ModuleEditor.cpp
> +				CreateGameObject(copyObject->GetName(), copyObject, App->scene->GetLoadedScene()->GetRoot());
```suggestion
				DuplicateGameObject(copyObject->GetName(), copyObject, App->scene->GetLoadedScene()->GetRoot());
```

2023-03-21 12:52 UTC, markmeliaa commented on Source/Modules/ModuleEditor.cpp
> +
Here wouldn't be interesting to add an else, so when the user does CtrlC in the root or any of the unique lights, any past copied objects are erased? If not if could feel a bit weird to CtrlC and object, then CtrlC several times the root (for whatever reason), and when the pressing CtrlV the pasted object would be GameObject selected before the root was tried to be copied, it's just a suggestion.

2023-03-21 12:52 UTC, markmeliaa commented on Source/Modules/ModuleEditor.cpp
> +			CreateGameObject(App->scene->GetSelectedGameObject()->GetName()
```suggestion
			DuplicateGameObject(App->scene->GetSelectedGameObject()->GetName()
```

2023-03-21 19:05 UTC, gerard-queralt requested changes
Added a few comments on top of what Mark already said. Thanks for your work David!

2023-03-21 19:05 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.h
> +	GameObject* copyObject;
Why not make the copy object a unique pointer?

2023-03-23 18:07 UTC, DADSILVER commented on Source/DataModels/Scene/Scene.h
> +	GameObject* CreateGameObject(const char* name, GameObject*, GameObject* parent);
Done thx

2023-03-23 18:07 UTC, DADSILVER commented on Source/Modules/ModuleEditor.cpp
> +				CreateGameObject(copyObject->GetName(), copyObject, App->scene->GetSelectedGameObject());
Done thx

2023-03-23 18:07 UTC, DADSILVER commented on Source/Modules/ModuleEditor.cpp
> +				CreateGameObject(copyObject->GetName(), copyObject, App->scene->GetLoadedScene()->GetRoot());
Done thx

2023-03-23 18:09 UTC, DADSILVER commented on Source/Modules/ModuleEditor.cpp
> +	if (App->scene->GetSelectedGameObject() != App->scene->GetLoadedScene()->GetRoot())
Oky, i was not sure if directional light could be copy.

2023-03-23 18:09 UTC, DADSILVER commented on Source/Modules/ModuleEditor.cpp
> +
Done thx

2023-03-23 18:09 UTC, DADSILVER commented on Source/Modules/ModuleEditor.cpp
> +			CreateGameObject(App->scene->GetSelectedGameObject()->GetName()
Done thx

2023-03-23 18:29 UTC, DADSILVER commented on Source/DataModels/Components/ComponentAmbient.cpp
> +ComponentAmbient::ComponentAmbient(ComponentAmbient& componentAmbient):
Its not and ambient lights not need a copy

2023-03-23 18:30 UTC, markmeliaa commented on Source/Modules/ModuleEditor.cpp
> +	if (App->scene->GetSelectedGameObject() != App->scene->GetLoadedScene()->GetRoot())
Well, IMO we should have multiple directional lights in the future, but for now it is unique.

2023-03-23 18:50 UTC, DADSILVER commented on Source/Modules/ModuleEditor.h
> +	GameObject* copyObject;
I think it is better for memory management of something that is going to be created and deleted all the time.

2023-03-23 19:59 UTC, AuxPort66 approved these changes
Ole!

2023-03-23 20:01 UTC, gerard-queralt approved these changes

2023-03-23 20:01 UTC, merged