feat: Create new scene
Horizons-Games/Axolotl-Engine pull request #219
Opened 2023-03-20 23:11 UTC by MarcGonzalezMoratona

2023-03-21 20:34 UTC, Piterga12 commented
When creating a new scene without any previous save of the current one, and we click on save scene, it creates the new one first and saves the new created one as the one we had.

And second, when doing the same with a big scene such as final.axolotl, it freezes

2023-03-21 20:59 UTC, gerard-queralt requested changes

2023-03-21 20:59 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +				App->scene->SaveSceneToJson(filePathName + ".axolotl");
```suggestion
App->scene->SaveSceneToJson(filePathName + SCENE_EXTENSION);
```

Prefer using the global `SCENE_EXTENSION` instead of `".axolotl"`.

2023-03-21 20:59 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +			if (filePathName != "New Scene")
This is a bit picky, but I don't like having this type of conventions in fields that the user can modify. With this checks, we are arbitrarily preventing the user from having "New Scene" as a scene name. For now it's probably fine, but we should look into a better way of achieving this.

2023-03-21 20:59 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +		if (ImGui::Button("Close without saving", ImVec2(240, 0)))
Everything inside this `if` block is repeated code from the previous button's `if` block. We could probably encapsulate most of it.

2023-03-21 20:59 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.h
> +enum class Actions
I think it's better if we either scope the enum inside the class body (so, put it inside the class declaration) so the signature becomes `WindowMainMenu::Actions` or rename it to something more specific.

2023-03-21 22:44 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +			if (filePathName != "New Scene")
It has been done this way because we don't have a way to check that the scene has never been saved before. Maybe in the future we can solve it

2023-03-22 23:42 UTC, gerard-queralt approved these changes
Everything looks OK, thank you for your work Marc!

2023-03-23 00:37 UTC, Piterga12 approved these changes
Everything works fine, good job.

2023-03-23 18:27 UTC, merged