Save shortcut + Vsync
Horizons-Games/Axolotl-Engine pull request #222
Opened 2023-03-21 15:01 UTC by diegusmejia117

Created feature CTRL S : You can now save with the combination of ctrl + s, it works as standard first save as Save As, subsequent saves will work as should.

Created feature VSYNC toogle: this toggle activates/deactivates the VSYNC functionality.

2023-03-21 17:57 UTC, markmeliaa requested changes
Nice work, this is a good feature, but just a couple simple changes:

2023-03-21 17:57 UTC, markmeliaa commented on Source/DataModels/Windows/EditorWindows/WindowAbout.cpp
> +	ImGui::TextWrapped("Description: Axolotl Engine is a game development tool developed by a group of students at the UPC SCHOOL");
```suggestion
	ImGui::TextWrapped("Description: Axolotl Engine is a game building tool developed by a group of students at the UPC School");
```

2023-03-21 21:33 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowAbout.cpp
> +	ImGui::TextWrapped("Description: Axolotl Engine is a game development tool developed by a group of students at the UPC SCHOOL");
If you don't mind, I think it sounds better the other way around. "... game development tool built by..."

2023-03-21 21:37 UTC, gerard-queralt commented
This was branched from [create-new-scene-v2](https://github.com/Horizons-Games/Axolotl-Engine/tree/create-new-scene-v2), if I'm not mistaken, so we at least need to merge #219 before merging this.

2023-03-21 23:01 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/EditorWindows/WindowAbout.cpp
> +	ImGui::TextWrapped("Description: Axolotl Engine is a game development tool developed by a group of students at the UPC SCHOOL");
resolved because I have already changed it in [#219]

2023-03-23 18:06 UTC, gerard-queralt requested changes

2023-03-23 22:01 UTC, gerard-queralt submitted a review, later dismissed

2023-03-30 11:38 UTC, markmeliaa approved these changes
All good, thanks!

2023-03-30 21:12 UTC, gerard-queralt submitted a review, later dismissed

2023-03-31 10:50 UTC, markmeliaa commented
Unfortunately, there seems to be a couple conflicts that need to be fixed before merging this.

2023-04-04 18:49 UTC, AuxPort66 submitted a review, later dismissed

2023-04-08 00:18 UTC, markmeliaa approved these changes

2023-04-08 14:52 UTC, PaablooCH requested changes
Before merging a notice some changes with the style

2023-04-08 14:52 UTC, PaablooCH commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +	if (filePathName != "New Scene") App->scene->SaveSceneToJson(filePathName + SCENE_EXTENSION);
if and else don't follow the programming rules, they need the {}

2023-04-08 14:52 UTC, PaablooCH commented on Source/Modules/ModuleInput.cpp
> +        App->editor->GetMainMenu()->ShortcutSave();
doesn't follow the programming rules, should be between {}

2023-04-08 14:52 UTC, PaablooCH commented on Source/Modules/ModuleEditor.h
> +}
add a space between functions

2023-04-08 14:52 UTC, PaablooCH commented on Source/Modules/ModuleInput.cpp
> +
too much spaces between lines of code

2023-04-08 14:52 UTC, PaablooCH commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +
you can delete the spaces between code and }

2023-04-09 14:59 UTC, PaablooCH approved these changes

2023-04-10 13:24 UTC, markmeliaa approved these changes

2023-04-10 13:24 UTC, merged