Filesystem import loading icon
Horizons-Games/Axolotl-Engine pull request #233
Opened 2023-03-23 19:39 UTC by Piterga12

2023-03-25 20:50 UTC, gerard-queralt approved these changes

2023-03-27 22:57 UTC, gerard-queralt submitted a review, later dismissed

2023-04-16 20:26 UTC, AuxPort66 requested changes
As I already told you in class, editor scene windows like MaterialInput should keep the request instead of the Import. I leave here the change request just so it doesn't merge

2023-04-30 14:19 UTC, AuxPort66 approved these changes

2023-04-30 15:17 UTC, gerard-queralt approved these changes

2023-04-30 15:17 UTC, merged