Transparency to materials
Horizons-Games/Axolotl-Engine pull request #235
Opened 2023-03-25 20:47 UTC by UriMurcia

Now we can create materials that have transparency on them. To do so, create a material or select an existing one (in an object inspector) and change the Render Mode between Opaque and Transparency. Once the material has the Render Mode on Transparent you can change the Alpha of it to make it more or less transparent. Once finished, click Apply and see the changes.

2023-03-27 15:35 UTC, sncarbo commented
It renders some objects in the wrong order, I don't know if it should, but I'd rather ask you guys hahaha @UriMurcia @xavi1111 

<img width="553" alt="Captura de pantalla 2023-03-27 172859" src="https://user-images.githubusercontent.com/116657602/227989846-4e1f874d-69e3-428d-a1e7-67e3a950c503.png">

2023-03-27 21:54 UTC, UriMurcia commented
> It renders some objects in the wrong order, I don't know if it should, but I'd rather ask you guys hahaha @UriMurcia @xavi1111
> 
> <img alt="Captura de pantalla 2023-03-27 172859" width="553" src="https://user-images.githubusercontent.com/116657602/227989846-4e1f874d-69e3-428d-a1e7-67e3a950c503.png">

True! Forgot to try it with objects with texture. Now it should be fixed. Thank you Santi!

2023-03-29 19:35 UTC, MacXxs commented on Source/DataModels/Resources/ResourceMaterial.h
> +	return this->isTransparent;
Remove the "this->" please, teachers only  want us to use it when necessary

2023-03-29 19:38 UTC, MacXxs commented on Source/Modules/ModuleRender.cpp
> +							static_cast<ComponentTransform*>(gameObject->GetComponent(ComponentType::TRANSFORM));
remove the tab jeje

2023-03-29 19:41 UTC, MacXxs requested changes
Everything looks alright! Just remove the this-> i commented and for me it's OK to merge!

2023-03-30 17:25 UTC, UriMurcia commented on Source/DataModels/Resources/ResourceMaterial.h
> +	return this->isTransparent;
Removed! Thanks Miki!

2023-04-01 17:24 UTC, AuxPort66 submitted a review, later dismissed

2023-04-01 17:47 UTC, gerard-queralt requested changes
Thank you both for your work!

2023-04-01 17:47 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceMaterial.h
> +	const bool& GetTransparent();
We shouldn't return references to primitive types. This allows the caller of the function to modify the value of the member without calling the setter, which ends up being the same thing as having the variables public. Same for the methods above.

2023-04-01 17:47 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceTexture.cpp
> +	if (loadOptions.mipMap) glGenerateMipmap(GL_TEXTURE_2D);
Better to put it in a separate line.

```suggestion
	if (loadOptions.mipMap)
	{
		glGenerateMipmap(GL_TEXTURE_2D);
	}
```

2023-04-01 17:47 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMaterial.cpp
> +			const char* renderModes[2] = { "Opaque", "Transparent" };
Why not use a vector of strings?

2023-04-01 17:47 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMaterial.cpp
> +			const char* renderModes[2] = { "Opaque", "Transparent" };
And this can probably be a static member of the class.

2023-04-01 17:47 UTC, gerard-queralt commented on Source/Modules/ModuleRender.cpp
> +						while (transparentGOToDraw[dist] != nullptr) { //If an object is at the same position as another one
Curly bracket should go on the line below.

2023-04-01 18:10 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceMaterial.h
> +	const bool& GetTransparent();
@AuxPort66 will take care of this since it has an impact on the binaries, resolving it here.

2023-04-01 18:15 UTC, gerard-queralt approved these changes

2023-04-01 18:17 UTC, AuxPort66 approved these changes
👍

2023-04-02 09:50 UTC, MacXxs approved these changes
Perfect!

2023-04-02 09:51 UTC, merged