Refactor Window hierarchy
Horizons-Games/Axolotl-Engine pull request #237
Opened 2023-03-26 15:13 UTC by DADSILVER

To improve the efficiency of the hierarchy, there have been three changes:

1. Add to a GameObject the state of ChildSelected. To avoid searching in the children's vector.
2. **In the function GetChildren uses reserve() to avoid the that when we do a pushback(), the vector created doesn't need a resize.**
3. Create a vector of children to avoid using the GetChildren() function if unnecessary.

2023-03-26 17:03 UTC, markmeliaa submitted a review, later dismissed
I've tried moving around some objects around in an empty scene and everything seems to work properly, good job and nice improvement of performance!

2023-03-27 19:26 UTC, gerard-queralt requested changes
Left a few minor comments, overall great job on your improvements to the hierarchy!

2023-03-27 19:26 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.h
> +inline const bool GameObject::IsChildSelected()
This method doesn't seem to be used, unless VisualStudio is lying to me. Also, I'm not sure a getter should have side-effects like changing the state of selection. I'd prefer to use more descriptive names, but that's just me, feel free to ignore me.

2023-03-27 19:26 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +        else
Empty else block.

2023-03-27 19:26 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +void WindowHierarchy::DrawRecursiveHierarchy(GameObject* gameObject, bool isRoot)
Why add a boolean to the signature? Don't think the comparisson is expensive enough to have any benefits in removing it, and in my opinion it makes the method less intuitive to use.

2023-03-28 00:15 UTC, PaablooCH approved these changes
Nice job friend 👍 just one thing

2023-03-28 00:15 UTC, PaablooCH commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +void WindowHierarchy::DrawRecursiveHierarchy(GameObject* gameObject, bool isRoot)
you can set the variable inside of the function and avoid sending it by parameter, like you did with children vector

2023-03-28 11:06 UTC, DADSILVER commented on Source/DataModels/GameObject/GameObject.h
> +inline const bool GameObject::IsChildSelected()
True, my bad this function had been used before some changes.

2023-03-28 11:07 UTC, DADSILVER commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +        else
Yes, thank you.

2023-03-28 14:36 UTC, merged