Feat: States were added to the windows in a json file, to might know if a window is closed or not
Horizons-Games/Axolotl-Engine pull request #255
Opened 2023-03-31 02:15 UTC by elbuho12Jesus

...

2023-04-01 01:25 UTC, gerard-queralt requested changes
Left many comments, but mostly minor things. Really great job overall, this will be a great addition!

2023-04-01 01:25 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/EditorWindow.h
> +	void LoadMeta(const std::string name, bool& enable);
Unused

2023-04-01 01:25 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/EditorWindow.h
> +	void UpdateMeta(bool enabled, const std::string name);
Unused

2023-04-01 01:25 UTC, gerard-queralt commented on Source/DataModels/Windows/Window.h
> +	bool enabled;
Unnecessary

2023-04-01 01:25 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +		enabled = !showAbout;
This change probably needs to be reverted. Now the about window doesn't work properly.

2023-04-01 01:25 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.cpp
> +	about->Draw(enabled);
```suggestion
	about->Draw(showAbout);
```

2023-04-01 01:25 UTC, gerard-queralt commented on Source/FileSystem/Json.h
> +	void getVectorNames(std::vector<const char*> &vec);
Why have it as an output parameter and not as a return type? Also, "get" should be capitalized.
```suggestion
	std::vector<std::string> GetVectorNames();
```

2023-04-01 01:25 UTC, gerard-queralt commented on Source/FileSystem/ModuleResources.cpp
> +const std::string ModuleResources::settingsFolder = "Settings/";
Shouldn't be here, not a resource.

2023-04-01 01:25 UTC, gerard-queralt commented on Source/FileSystem/ModuleResources.cpp
> +	CreateFolderSettings();
Shouldn't be here. For now maybe move it to `ModuleEditor`, but we might need to create a "ModuleConfig" or something that handles this.

2023-04-01 01:25 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.cpp
> +		windows[i].get()->UpdateState(json);
As I said in one of the first comments, I think we don't need `EditorWindow::UpdateState`. What I would do is write the JSON in `ModuleEditor`, just like reading it. Something like:
```
json[windows[i]->GetName().c_str()] = mainMenu->IsWindowEnabled(i);
```

2023-04-01 01:25 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.cpp
> +			json[windows[i].get()->GetName().c_str()]=true;
```suggestion
			json[windows[i]->GetName().c_str()]=true;
```

2023-04-01 01:25 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.cpp
> +	std::string lib = "Settings/WindowsStates.cong";
```suggestion
	std::string settingsPath = "Settings/WindowsStates.conf";
```

2023-04-01 01:25 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/EditorWindow.cpp
> +		std::string set = "Settings/WindowsStates.cong";
Also probably better to have it as a static string, like we do Assets and Lib in `ModuleResources`. This way we only need to change it in one place.

2023-04-14 00:18 UTC, gerard-queralt requested changes
Thank you Jesús, every change you did looks great! You seem to have missed some of my requests hidden in the "Show more", please take a look at those as well :P

2023-04-14 00:18 UTC, gerard-queralt commented on Source/Modules/ModuleEditor.cpp
> +	std::string settingsFolder = "Settings/";
This is not needed, since you already have this string as a static member.
```suggestion
```

2023-04-15 23:15 UTC, gerard-queralt approved these changes

2023-04-16 22:05 UTC, AuxPort66 approved these changes

2023-04-17 09:36 UTC, gerard-queralt approved these changes

2023-04-17 23:04 UTC, gerard-queralt approved these changes

2023-04-18 23:55 UTC, AuxPort66 approved these changes

2023-04-19 00:18 UTC, merged