Skinning FileSystem
Horizons-Games/Axolotl-Engine pull request #269
Opened 2023-04-05 17:53 UTC by sncarbo

2023-04-07 07:06 UTC, DADSILVER reviewed
Good job, but let me tell you some suggestions.

2023-04-07 09:02 UTC, sncarbo commented on Source/DataModels/Resources/ResourceMesh.h
> +	static constexpr unsigned int bonesPerVertex = 4;
Done! Thank you for noticing.

2023-04-07 16:07 UTC, DADSILVER approved these changes

2023-04-07 16:11 UTC, MarcGonzalezMoratona commented on Source/DataModels/Resources/ResourceMesh.h
> +	unsigned int GetNumBones();
I think this and the rest of the getters of this class can be const

2023-04-07 16:16 UTC, MarcGonzalezMoratona commented on Source/DataModels/Resources/ResourceMesh.h
> +	return this->numWeights;
can we do it this way? If it works I think is more simple
```suggestion
	return numWeights;
```

2023-04-07 16:18 UTC, MarcGonzalezMoratona commented on Source/DataModels/Resources/ResourceMesh.h
> +	this->attaches.resize(this->numVertices);
do you think we can avoid using `this->` to simplify this kind of methods?

2023-04-07 16:26 UTC, MarcGonzalezMoratona commented on Source/FileSystem/Importers/MeshImporter.cpp
> +		Bone bone;
if this bone is only used in the scope of this loop, is there a way to delete its memory once we have finished working with it?

2023-04-07 17:12 UTC, sncarbo commented on Source/DataModels/Resources/ResourceMesh.h
> +	unsigned int GetNumBones();
Done! Thank you for pointing this out.

2023-04-07 17:13 UTC, sncarbo commented on Source/DataModels/Resources/ResourceMesh.h
> +	return this->numWeights;
I think that according to the programming rules it has to be in this format.

2023-04-07 17:51 UTC, MarcGonzalezMoratona submitted a review, later dismissed

2023-04-08 14:14 UTC, PaablooCH requested changes
Hi, good job. I see some things in the code:

2023-04-08 14:14 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceMesh.h
> +	std::vector<Attach> attaches;
Why don't u make these vectors a vector of pointers? will be easier to pass them through the getters

2023-04-08 14:14 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceMesh.h
> +	return this->numWeights;
this-> is not necessary

2023-04-08 14:14 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceMesh.h
> +	this->attaches.resize(this->numVertices);
this-> is not necessary in both variables

2023-04-08 14:14 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceMesh.h
> +	this->attaches[vertexId].bones[this->attaches[vertexId].numBones] = boneId;
this-> is not necessary

2023-04-08 14:14 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceMesh.h
> +		++this->attaches[vertexId].numBones;
this-> is not necessary

2023-04-08 14:14 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceMesh.h
> +	if (this->attaches[vertexId].numBones < bonesPerVertex)
this-> is not necessary

2023-04-08 21:28 UTC, sncarbo commented on Source/DataModels/Resources/ResourceMesh.h
> +	if (this->attaches[vertexId].numBones < bonesPerVertex)
Done! I have removed all the `this` that you mentioned above.

2023-04-08 21:30 UTC, sncarbo commented on Source/DataModels/Resources/ResourceMesh.h
> +	std::vector<Attach> attaches;
The struct destructors need to be explicitly defined and I had thought that this was not necessary as the size in bytes should not be very large.

2023-04-09 14:57 UTC, PaablooCH approved these changes

2023-04-10 16:44 UTC, MacXxs approved these changes
Everything working! 👍🏼

2023-04-10 16:44 UTC, merged