Engine/animation: remove extra nodes from hirearchy
Horizons-Games/Axolotl-Engine pull request #270
Opened 2023-04-05 19:47 UTC by MacXxs

Removed the drawing of the extra nodes that assimp creates when importing models, with the information of the pre_rotations and pre_translations applied to the bones (this commit only affects the imgui drawing of the hirearchy, we must keep the nodes themselves for the animations)

<b>Before</b>             |  <b>After</b>
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/18547655/230187974-63fc214c-298c-4e44-826c-19284525a6f6.png)  |  ![image](https://user-images.githubusercontent.com/18547655/230188731-7612a66f-b542-4e88-b0ce-d1f5310ad676.png)

2023-04-07 06:41 UTC, DADSILVER approved these changes

2023-04-08 00:24 UTC, markmeliaa requested changes
Nice! Just one comment.

2023-04-08 00:24 UTC, markmeliaa commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +            if (gameObject->GetComponent(ComponentType::TRANSFORM) != nullptr)
This if its a bit useless, every gameobject has to have a transform, its not a possiblity, its an obligation, so this if will always resolve to `true`.

2023-04-08 00:26 UTC, markmeliaa commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +            if (gameObject->GetComponent(ComponentType::TRANSFORM) != nullptr)
Wait, just noticed that you did not add this line of code, idk why GitHub shows like you changed those, so don't mind me.

2023-04-08 00:27 UTC, markmeliaa approved these changes

2023-04-08 13:27 UTC, PaablooCH approved these changes

2023-04-08 14:16 UTC, merged