feat: get animation info from assimp
Horizons-Games/Axolotl-Engine pull request #272
Opened 2023-04-07 16:02 UTC by MarcGonzalezMoratona

2023-04-08 14:40 UTC, PaablooCH requested changes
One thing a part of my changes is (idk if it's only me) all the animation files are outside of its filters, it's just a reminder for later.
![image](https://user-images.githubusercontent.com/62140600/230727083-e99d9978-1df3-4298-9e33-70ff9d7609c0.png)

2023-04-08 14:40 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceAnimation.h
> +	double duration;
why you change to double? We really need that precision?

2023-04-08 14:40 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceModel.h
> +	const std::vector<std::shared_ptr<ResourceAnimation>>& GetAnimations() const;
Should this not return a vector of raw pointers?

2023-04-08 14:40 UTC, PaablooCH commented on Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
> +					AddComponentAnimation();
```suggestion
					App->scene->GetSelectedGameObject()->CreateComponent(ComponentType::ANIMATION);
```
you can delete the function at 357

2023-04-08 14:40 UTC, PaablooCH commented on Source/Globals.h
> +#define VERSION "0.0.3"
```suggestion
#define VERSION "0.3.0"
```
our last tag was that

2023-04-08 14:57 UTC, MarcGonzalezMoratona commented on Source/DataModels/Resources/ResourceAnimation.h
> +	double duration;
Assimp defines mDuration as a double, that's why we did it the same way
https://assimp.sourceforge.net/lib_html/structai_animation.html

But if you think that a float is enough we can change it

2023-04-08 14:58 UTC, MarcGonzalezMoratona commented
> One thing a part of my changes is (idk if it's only me) all the animation files are outside of its filters, it's just a reminder for later. ![image](https://user-images.githubusercontent.com/62140600/230727083-e99d9978-1df3-4298-9e33-70ff9d7609c0.png)

I had some problems adding new files to the project, I will try to fix it. Thank you for noticing!

2023-04-08 15:03 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceAnimation.h
> +	double duration;
ok, thanks for the explanation

2023-04-08 15:11 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
> +					AddComponentAnimation();
we are encapsulating into methods all the logic related to components. There are other methods such as AddComponentPlayer, AddComponentRigidBody and AddComponentMockState that are defined in a similar way. I think that it's good to have it like this for reutilisation purposes. I would suggest to do a refactor in the future if we don't find this useful

2023-04-08 15:18 UTC, MarcGonzalezMoratona commented on Source/DataModels/Resources/ResourceModel.h
> +	const std::vector<std::shared_ptr<ResourceAnimation>>& GetAnimations() const;
methods for GetMeshes and GetMaterials were returning a vector of shared_ptr. I don't know which approach is better, so I did something similar. Why do you think it's better to return a vector of raw pointers here?

2023-04-09 14:55 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceModel.h
> +	const std::vector<std::shared_ptr<ResourceAnimation>>& GetAnimations() const;
i find working with raw is easier than smart, also you don't need to bring shared pointer's logic with you if the purpose of calling GetAnimation is to get only the info in ResourceAnimation

2023-04-09 16:04 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceModel.h
> +	const std::vector<std::shared_ptr<ResourceAnimation>>& GetAnimations() const;
When working with resources we should always use shared/weak pointers, since they could be deleted at any point. If someone wants to get this resources we should assume that they intend to extend the lifespan of the object. Furthermore, converting the inner vector of shared to a vector of raw is a relatively expensive operation, and as I said I don't think it has any benefit in this case to justify it.

2023-04-10 13:45 UTC, PaablooCH submitted a review, later dismissed

2023-04-10 15:34 UTC, MacXxs requested changes
'm getting this error when drag and dropping the Gunan model with animations provided by the teachers:

![image](https://user-images.githubusercontent.com/18547655/230933222-c5d55797-68cc-42b3-bee0-227a63d59200.png)

It seems that one of the animations when requesting the resource during the load function is trying to get a resource with an empty path so it breaks.

Also this PR doesn't have the latest changes in animation, so they should be merged in this branch before pushing the pr.

2023-04-10 16:54 UTC, MacXxs approved these changes

2023-04-10 16:57 UTC, merged