static GameObjects implementation
Horizons-Games/Axolotl-Engine pull request #274
Opened 2023-04-08 19:17 UTC by Dedado3000

2023-04-10 20:44 UTC, gerard-queralt requested changes
Thanks for your work, David. Left some minor comments.

2023-04-10 20:44 UTC, gerard-queralt commented on Source/Modules/ModuleScene.h
> +	void AddGameObjectAndChildrens(GameObject* object);
```suggestion
	void AddGameObjectAndChildren(GameObject* object);
```

2023-04-10 20:44 UTC, gerard-queralt commented on Source/Modules/ModuleScene.h
> +	void RemoveGameObjectAndChildrens(GameObject* object);
```suggestion
	void RemoveGameObjectAndChildren(GameObject* object);
```

2023-04-10 20:44 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.h
> +	const std::vector<GameObject*>& GetNonStaticObjects();
```suggestion
	const std::vector<GameObject*>& GetNonStaticObjects() const;
```

2023-04-10 20:44 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
> +				lastSelectedGameObject->SpreadStatic();
I would add a comment here to remind us that we should update this behaviour, so it's not always propagated.

2023-04-12 14:46 UTC, gerard-queralt submitted a review, later dismissed

2023-04-12 15:11 UTC, OriolSors commented on Source/Modules/ModuleScene.cpp
> +	for (GameObject* children : object->GetChildren())
```suggestion
	for (GameObject* child: object->GetChildren())
```
This is more readable

2023-04-12 15:11 UTC, OriolSors commented on Source/Modules/ModuleScene.cpp
> +		RemoveGameObjectAndChildren(children);
```suggestion
		RemoveGameObjectAndChildren(child);
```

2023-04-12 15:13 UTC, OriolSors commented on Source/Modules/ModuleScene.h
> +
Did you delete these functions from the Quadtree?

2023-04-12 15:14 UTC, OriolSors reviewed
Good implementation and ready for simplify the Quadtree @Dedado3000 !

Please, take a look what I commented about deleting the redundant functions in the Quadtree with your new implementation. Maybe we can delete that with the refactor.

Accept please my suggestions, its more clear xd

2023-04-15 16:37 UTC, OriolSors approved these changes

2023-04-15 20:18 UTC, gerard-queralt approved these changes

2023-04-15 20:18 UTC, merged