FEAT: Basic game play mode
Horizons-Games/Axolotl-Engine pull request #278
Opened 2023-04-14 15:31 UTC by DADSILVER

- OnPlay and OnStop states are created in the application.
- An own timer is created for the OnPlay state.
- Frustum for the camera is changed to a raw pointer because it has no copy constructor.
- Copy constructors are created for player and rigid-body components.
- To exit the OnPlay state, press ctrl+Q.
- The player is copied for the Onplay state. In the stop, the player copied is deleted and the actual player is turned on to enable.

2023-04-14 21:06 UTC, PaablooCH requested changes
I didn't find anything wrong testing it. Just 3 things

2023-04-14 21:06 UTC, PaablooCH commented on Source/Modules/ModulePlayer.cpp
> +				if (!child->GetComponentsByType<ComponentCamera>(ComponentType::CAMERA).empty())
could you create cameraPlayer outside this if and check if its null, saving making this call?

2023-04-14 21:06 UTC, PaablooCH commented on Game/Assets.zip
delete this zip

2023-04-15 21:23 UTC, gerard-queralt requested changes
Left a comment regarding `Camera::frustum` and a minor thing with `Timer`.

I don't particularly like the idea of having the Application as a whole be aware of whether we are on play mode or not. Wouldn't it make more sense to store that information (boolean and Timer) in `ModuleScene`? In particular, for Scripting, a script's `Init` and `Start` need to be called when entering play mode, and `CleanUp` when exiting. As it stands, we would need two additional methods in `ModuleScene` to call them to do that functionality. If we moved `OnPlay` and `OnStopPlay`, we could have everything together in that same method body. I'd like to know your thoughts on this, it's possible I'm missing something important.

2023-04-15 21:23 UTC, gerard-queralt commented on Source/DataModels/Camera/Camera.cpp
> +	frustum(new Frustum(*camera.frustum))
Instead of changing the frustum to a raw pointer (which you aren't deleting, if I didn't miss it), you could do something like
```suggestion
	frustum(std::unique_ptr<Frustum>(new Frustum(*camera.frustum)))
```

2023-04-15 21:23 UTC, gerard-queralt commented on Source/DataModels/Timer/Timer.cpp
> +	stopped = false;
This is changing the functionality of the class. If I recall correctly, a Timer isn't supposed to be reusable after calling `Stop`. We would need to make sure this doesn't break anything, at the very least.

2023-04-16 10:45 UTC, MacXxs commented
> Left a comment regarding `Camera::frustum` and a minor thing with `Timer`.
> 
> I don't particularly like the idea of having the Application as a whole be aware of whether we are on play mode or not. Wouldn't it make more sense to store that information (boolean and Timer) in `ModuleScene`? In particular, for Scripting, a script's `Init` and `Start` need to be called when entering play mode, and `CleanUp` when exiting. As it stands, we would need two additional methods in `ModuleScene` to call them to do that functionality. If we moved `OnPlay` and `OnStopPlay`, we could have everything together in that same method body. I'd like to know your thoughts on this, it's possible I'm missing something important.

For Animation I need the OnPlay, OnStop and OnUpdate on Application as it is referenced to be done this way in the ppt. On top of this, if we put the OnPlay, OnStop and OnUpdate on the Application every module and component that needs to access this state simply needs check the application's isOnPlayMode state. I wouldn't change where things need to be implemented, and do it as it is stipulated on the documentation that we are given.

2023-04-16 22:27 UTC, AuxPort66 requested changes
We should have the ability to use the mouse in Play mode by hitting a key. This is essential to be able to use the editor with the scripting while we test on Play mode.

2023-04-18 00:18 UTC, gerard-queralt commented on Source/Modules/ModulePlayer.cpp
>  			SetPlayer(camera->GetParent()->GetParent()->RemoveChild(camera->GetParent()));
I'm pretty sure this line won't work after your change to `SetPlayer`. Can you try compiling in Game mode just to make sure?

2023-04-18 00:18 UTC, gerard-queralt commented on Source/Modules/ModulePlayer.h
> +	GameObject*  player;
Why was this changed?

2023-04-18 10:41 UTC, PaablooCH submitted a review, later dismissed

2023-04-19 18:14 UTC, gerard-queralt submitted a review, later dismissed

2023-04-19 20:49 UTC, gerard-queralt submitted a review, later dismissed
I'm trying on Mark's branch ([scripting/component-script-window](https://github.com/Horizons-Games/Axolotl-Engine/tree/scripting/component-script-window)), so this might be inacurate. But holding `Ctrl+A` ends up locking the mouse in place if you don't exit play mode fast enough. Could you check this doesn't happen in your branch?

2023-04-20 16:29 UTC, gerard-queralt requested changes
Thank you for your work David, left a few comments.

2023-04-20 16:29 UTC, gerard-queralt commented on Source/Application.cpp
> +{
Not a big deal, but I would leave the call to `scene->OnPause()` ready, even if it's not currently used.

2023-04-20 16:29 UTC, gerard-queralt commented on Source/Application.h
> +	bool GetIsOnPlayMode() const;
```suggestion
	bool IsOnPlayMode() const;
```

2023-04-20 16:29 UTC, gerard-queralt commented on Source/Application.h
> +	std::unique_ptr<Timer> onPlayTimer;
Now that I whink about it, maybe both timers could be references? Maybe it's not possible.
```suggestion
	Timer onPlayTimer;
```

2023-04-20 16:29 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentMaterial.cpp
> +#pragma warning (disable: 4804)
This entire file should not be added.

2023-04-20 16:29 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentPlayer.cpp
> +ComponentPlayer::ComponentPlayer(const ComponentPlayer& componentPlayer) :
I think we already talked about this, but could you remind me why we need these copy constructors? Looks pretty redundant to me.

2023-04-20 16:29 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +            if (gameObject == App->scene->GetSelectedGameObject() && gameObject !=App->player->GetPlayer())
I know we currently require a Player in Game/Play mode, but that shouldn't be the case. Is there a reason beyond that that we couldn't delete the player in play mode? Feels a bit arbitrary, but I could be missing something.

2023-04-20 16:29 UTC, gerard-queralt commented on Source/Modules/ModulePlayer.cpp
> +	App->camera->SetSelectedCamera(-1);
Not really related to this PR so feel free to ignore this, but `SetSelectedCamera` should probably receive an `enum`. @Dedado3000

2023-04-20 16:59 UTC, DADSILVER commented on Source/Application.cpp
> +{
Sure.

2023-04-20 17:14 UTC, DADSILVER commented on Source/Application.h
> +	std::unique_ptr<Timer> onPlayTimer;
I don't think so. In this case both timers are only used in the application. And they are used during the whole execution, so I think it is worth to have them unique to not have to deal with the delete.

2023-04-20 17:16 UTC, DADSILVER commented on Source/DataModels/Components/ComponentMaterial.cpp
> +#pragma warning (disable: 4804)
this file does not exist anymore, no?

2023-04-20 17:21 UTC, markmeliaa commented on Source/DataModels/Components/ComponentMaterial.cpp
> +#pragma warning (disable: 4804)
yup, it does not

2023-04-20 17:27 UTC, DADSILVER commented on Source/DataModels/Components/ComponentPlayer.cpp
> +ComponentPlayer::ComponentPlayer(const ComponentPlayer& componentPlayer) :
At the beginning, the player was copied at the time of executing the scene in order not to make a temporary save and reload the scene. But I have left it in case you need to do a CTRL + c at some point.

2023-04-20 17:29 UTC, DADSILVER commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +            if (gameObject == App->scene->GetSelectedGameObject() && gameObject !=App->player->GetPlayer())
If it is deleted I am sure it will crash because it is not controlled. but it also seems a bit strange to be able to delete a player during the execution. maybe later if for some reason it is interesting we can add that freature. :)

2023-04-20 20:44 UTC, PaablooCH approved these changes

2023-04-21 01:28 UTC, gerard-queralt commented on Source/Application.h
> +	std::unique_ptr<Timer> onPlayTimer;
Sorry, that's not what I mean. I think you are thinking about using a `Timer*`. In which case, yeah, I think it's better to have it as a unique pointer. But I'm wondering if it could be a plain `Timer`, since it will never be null and it doesn't need to be passed around. If I'm not mistaken it should also be more efficient, but I could be wrong. As I said in the original comment, maybe it's not possible, but wanted to ask just in case.

2023-04-21 01:31 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentPlayer.cpp
> +ComponentPlayer::ComponentPlayer(const ComponentPlayer& componentPlayer) :
Yes, but that was not my question. This copy constructor is the same that is implicitly declared with every class. That is, I think you can delete it and the copy will work just fine. If that's the case, would there be any reason to keep this constructor around?
You can check in `scripting-main` that we don't declare an explicit copy constructor, but we still copy the component just fine because the default one is exactly what we need.

2023-04-21 01:34 UTC, gerard-queralt commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +            if (gameObject == App->scene->GetSelectedGameObject() && gameObject !=App->player->GetPlayer())
I imagine it would crash, so not really something to change in this PR. But I was wondering if there was any reason for this check besides that. Ideally, there shouldn't be any issues with deleting the player, since it should be a regular GameObject for the most part.

2023-04-21 08:38 UTC, DADSILVER commented on Source/Application.h
> +	std::unique_ptr<Timer> onPlayTimer;
Ahhh, a see your point. I Will change thx.

2023-04-21 13:07 UTC, markmeliaa submitted a review, later dismissed
Everything correct, we can merge this whenever, so merging scripting will be easier.

2023-04-21 16:00 UTC, gerard-queralt approved these changes
Thank you for your work David!

2023-04-21 17:19 UTC, AuxPort66 approved these changes

2023-04-21 19:37 UTC, merged