Feat : Add and remove materials
Horizons-Games/Axolotl-Engine pull request #279
Opened 2023-04-14 16:00 UTC by AlexisDieu

- Allow to add and remove a material from a mesh
- Can change a material for an another one
- Use a default material when no one is binded

2023-04-14 22:29 UTC, PaablooCH requested changes
Just one thing, but the other part of the code are good. After this we only have 1 job 🎊

2023-04-14 22:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +#include "Resources/ResourceMaterial.h"
this include is not necessary we already have it in forward declaration

2023-04-14 23:47 UTC, AlexisDieu commented on Source/DataModels/Batch/GeometryBatch.h
> +#include "Resources/ResourceMaterial.h"
Done thanks I forgot to remove it after tested

2023-04-15 01:13 UTC, PaablooCH approved these changes

2023-04-15 13:44 UTC, MacXxs approved these changes

2023-04-15 13:55 UTC, merged