feat: Bones GO Hierarchy & Skinning CPU Algorithm
Horizons-Games/Axolotl-Engine pull request #280
Opened 2023-04-15 15:23 UTC by sncarbo

Now each ComponentMeshRenderer contains a vector with the bone hierarchy that is affected by each transformation of the global matrix of its GameObject.

2023-04-16 11:07 UTC, MacXxs commented
Hi Santi! Remember to remove the metas and the meshes! hahahah

2023-04-16 11:07 UTC, MacXxs requested changes
Hi Santi! Remember to remove the metas and the meshes! hahahah

2023-04-16 12:54 UTC, sncarbo commented
> Hi Santi! Remember to remove the metas and the meshes! hahahah

Done Miki!

2023-04-16 13:06 UTC, MarcGonzalezMoratona commented on Source/DataModels/Scene/Scene.cpp
> +					break;
Why do you need this break?

2023-04-16 13:15 UTC, MarcGonzalezMoratona requested changes
Hi Santi! I think that the meta files are still there. Did you commit the last changes?
I also see that the pipeline is not working. I pressed "retry" because it seems to be a timeout.

2023-04-16 13:18 UTC, MarcGonzalezMoratona commented on Source/DataModels/Scene/Scene.cpp
> +					break;
I suppose that this method is making a search and when you find the root bone you skip the next iterations of the loop. Can you confirm?

2023-04-16 13:28 UTC, sncarbo commented on Source/DataModels/Scene/Scene.cpp
> +					break;
What the method essentially does is to look for the rootbone within the bones of each GO. The rootbone is the one whose name appears within the mesh bone names of that GO and whose parent's name **does not** appear. In other words, you could say that if the name of the parent appears, we already know that it is not the rootbone. That's why we put the `break`, because we don't need to look any further because we already know it's not the rootbone.

2023-04-16 13:39 UTC, sncarbo commented
> Hi Santi! I think that the meta files are still there. Did you commit the last changes?
> 
> I also see that the pipeline is not working. I pressed "retry" because it seems to be a timeout. (SOLVED)

I have deleted the metas and meshes from the animation branch, not the others. Do you want me to delete them all?

2023-04-16 13:45 UTC, MacXxs commented
> > Hi Santi! I think that the meta files are still there. Did you commit the last changes?
> > 
> > I also see that the pipeline is not working. I pressed "retry" because it seems to be a timeout. (SOLVED)
> 
> I have deleted the metas and meshes from the animation branch, not the others. Do you want me to delete them all?

Hey Santi, yeah we should only push the code modified, not the metas nor the meshes, so remove them all please!

2023-04-16 14:04 UTC, sncarbo commented
> > > Hi Santi! I think that the meta files are still there. Did you commit the last changes?
> > > I also see that the pipeline is not working. I pressed "retry" because it seems to be a timeout. (SOLVED)
> > 
> > 
> > I have deleted the metas and meshes from the animation branch, not the others. Do you want me to delete them all?
> 
> Hey Santi, yeah we should only push the code modified, not the metas nor the meshes, so remove them all please!

Done!

2023-04-16 14:45 UTC, MacXxs requested changes

2023-04-16 14:45 UTC, MacXxs commented on Game/Assets/Animation/Take 001.anim
This too should be removed ahaha. With this out of the way it should be everything! 😵‍💫

2023-04-16 15:13 UTC, sncarbo commented on Game/Assets/Animation/Take 001.anim
I deleted it!

2023-04-24 17:07 UTC, MacXxs approved these changes

2023-04-24 17:09 UTC, merged