Adding mesh collider component and window + feat to collide with objects when moving
Horizons-Games/Axolotl-Engine pull request #282
Opened 2023-04-15 19:33 UTC by totisama

2023-04-16 11:54 UTC, PaablooCH requested changes
I see 3 things: 
PS: pls fill the description box

2023-04-16 11:54 UTC, PaablooCH commented on Source/DataModels/Components/ComponentMeshCollider.h
> +	return this->isTrigger;
`this` not necessary

2023-04-16 11:54 UTC, PaablooCH commented on Source/DataModels/Components/ComponentMeshCollider.cpp
> +#include "ComponentTransform.h"
componentTransform class is not used

2023-04-16 11:54 UTC, PaablooCH commented on Source/DataModels/Components/ComponentMeshCollider.cpp
> +#include <iostream>
why this library is used?

2023-04-16 12:29 UTC, totisama commented on Source/DataModels/Components/ComponentMeshCollider.cpp
> +#include <iostream>
Thanks, I didnt notice I was including it

2023-04-16 13:51 UTC, OriolSors submitted a review, later dismissed
https://user-images.githubusercontent.com/31882514/232315751-8b4b0a08-18cd-4e18-ab09-baee212059aa.mp4

It seems that there is something weird with certain movements, maybe the raycasts are not accurate enough.

2023-04-18 17:19 UTC, PaablooCH approved these changes

2023-04-18 17:45 UTC, Dedado3000 commented
> axolotl-engine-2023-04-16-15-39-33_BVt18HOP.mp4 
> It seems that there is something weird with certain movements, maybe the raycasts are not accurate enough.

I solved in the last commit it was bc we weren't updating the transfoms matrices when moving

2023-04-18 22:01 UTC, PaablooCH reviewed
is this normal? xd
![rampa](https://user-images.githubusercontent.com/62140600/232914735-dfc208fd-6d9b-4849-a3f6-4af7152e18f5.gif)

2023-04-21 19:15 UTC, merged