feat: Scripts are "fully" funcional and accept different types of variables
Horizons-Games/Axolotl-Engine pull request #300
Opened 2023-04-19 23:13 UTC by markmeliaa

Now, scripts accept not only floats, but also strings, booleans and GameObjects (that should suffice for now, we'll add the different types of Components in the future, by now we can access to any Component instantiating a GameObject in the Script and calling `GetComponent(type)` on it).

Also, the ScriptComponentWindow was improved, you can load `DefaultScript` to see how the different types of variables are shown (this window also accepts Drag and Drop of GameObjects, so you can set any GameObject of the hierarchy into the script).

In the `HelloWorldScript` you can find a couple trials that everything works as intended (a couple of bugs arised, they would be reported because I think that they have nothing to do with this pr so they shouldn't be addressed here).

That's all, any doubt of how Scripts work please feel free to ask!

2023-04-20 16:31 UTC, gerard-queralt commented on Game/Scripts/HelloWorldScript.h
> +	void SetHelloWorld(const std::string helloWorld);
Thank you for your work Mark. I'll take a better look at your changes later, but I noticed something here:
```
	void SetHelloWorld(const std::string& helloWorld);
```
If this script is to serve as an example, it better set a good one! :P

2023-04-20 17:13 UTC, markmeliaa commented on Game/Scripts/HelloWorldScript.h
> +	void SetHelloWorld(const std::string helloWorld);
Whoops, thanks for noticing!

2023-04-20 17:48 UTC, DADSILVER commented on Game/Settings/WindowsStates.conf
Should be deleted.

2023-04-20 17:48 UTC, DADSILVER commented on Game/Assets/Unknown
Should be deleted

2023-04-20 19:44 UTC, DADSILVER approved these changes

2023-04-20 20:56 UTC, PaablooCH requested changes
all seems good, I request just a little change

2023-04-20 20:56 UTC, PaablooCH commented on Game/Scripts/DefaultScript.cpp
> +	this->check = verify;
`this` unnecessary

2023-04-21 10:22 UTC, markmeliaa commented on Game/Scripts/DefaultScript.cpp
> +	this->check = verify;
Done, ty for noticing!

2023-04-21 10:39 UTC, markmeliaa commented
> Hi Mark! @Vlukkee reported that the engine crashes when deleting a component script. After checking, tuns out I forgot to check that the pointer is not null after the "remove" button has been processed, like it's done in every other window ([MeshRenderer](https://github.com/Horizons-Games/Axolotl-Engine/blob/scripting/component-script-window/Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp#L41), for example). Could you please fix this? Something like
> 
> ```c++
> ComponentScript* script = static_cast<ComponentScript*>(this->component);
> 
> if (script)
> {
> 	std::vector<std::string> constructors = App->scriptFactory->GetConstructors();
> 	.........
> ```
> 
> Thank you in advance and sorry for the trouble!

Done!

2023-04-21 11:35 UTC, PaablooCH approved these changes

2023-04-21 12:04 UTC, gerard-queralt approved these changes

2023-04-21 12:04 UTC, merged