feat: scripting added to the engine
Horizons-Games/Axolotl-Engine pull request #301
Opened 2023-04-21 12:14 UTC by gerard-queralt

List of pull requests about scripting:

-  #262
    - Currently not used due to issues with the library, but idealy will be in the future
- #264
    - Not merged, but good insight on how to access code from another project
- #265
    - Not merged directly, but merged later with @ericdacal's branch in #286
- #286
    - Integration of a library that does hot reloading for us with our idea for scripting
- #300
   - Added more types of variables, example scripts and improved the component window. Also fixed some issues unnoticed in the previous PR

Authors:
- @Piterga12 
- @AlexisDieu 
- @totisama 
- @markmeliaa 
- @gerard-queralt

2023-04-21 12:15 UTC, gerard-queralt commented
Depends on #278

2023-04-21 12:39 UTC, Dedado3000 approved these changes
I don't see any problem in the parts i worked on.

In the other Part, good implementation of scripting @ericdacal  and @gerard-queralt congrats

2023-04-21 13:09 UTC, markmeliaa commented
Yessss, we got this! Nice work everyone 💯

2023-04-21 13:09 UTC, markmeliaa submitted a review, later dismissed
Yessss, we got this! Nice work everyone 💯

2023-04-21 13:13 UTC, ericdacal approved these changes

2023-04-21 13:18 UTC, AuxPort66 submitted a review, later dismissed

2023-04-21 13:45 UTC, Piterga12 approved these changes
Everything works fine!

2023-04-21 19:43 UTC, markmeliaa submitted a review, later dismissed

2023-04-21 21:20 UTC, PaablooCH requested changes
good job all of you, I notice a couple of things
PS: it doesn't compile in debugGame

2023-04-21 21:20 UTC, PaablooCH commented on Source/Modules/ModuleInput.cpp
> +#include "ModulePlayer.h"
why is only added this include? i mean it's the only change, you didn't add a use

2023-04-21 21:20 UTC, PaablooCH commented on Source/Modules/ModuleScene.cpp
there are a couple ifs that can be merge into one, lines: 95-97, 119-121 and137-139

2023-04-21 21:20 UTC, PaablooCH commented on Source/Modules/ModuleUI.cpp
> +	App->camera->GetCamera()->GetFrustum()->SetOrthographic((float)width, (float)height);
it is better to use static cast instead of c cast

2023-04-21 21:20 UTC, PaablooCH commented on Source/Scripting/IScript.h
> +	this->App = app;
i guess `this` is unnecessary

2023-04-21 21:42 UTC, gerard-queralt commented on Source/Scripting/ScriptFactory.h
> +	std::vector<std::pair<ObjectId, IScript*>> allScripts;
I'm not sure if they are, to be honest. But this container is never used as a dictionary (we never search a Script by it's ObjectID). What we do is, when a hot reload happens, we iterate this collection, request the new Script instance to the library through that ObjectID, and perform the necessary updates. That's why it's a vector of pairs instead of a map. Let me know if you're still not sure about this!

2023-04-21 21:43 UTC, gerard-queralt commented on Source/Modules/ModuleInput.cpp
> +#include "ModulePlayer.h"
Maybe it got mixed up in some merge. Thanks for noticing!

2023-04-21 22:08 UTC, DADSILVER reviewed
Many thanks to all of you who have worked on this branch. Just one thing.

2023-04-22 00:13 UTC, gerard-queralt commented on Game/Scripts/DefaultScript.cpp
Ideally yes, but the library we use doesn't seem to detect changes in the header so it doesn't trigger hot reloading. This means that, if you were to change something in an inlined method, you would need to save the source file anyway. To make it less strange for the user, we opted for this solution.
We still need to figure out if this is a limitaion of the library or something we configured wrong, but decided to leave it for after the vertical slice.
Hopefully this answers your question!

2023-04-22 12:58 UTC, gerard-queralt commented
Thank you for your feedback @PaablooCH and @DADSILVER. Tried to apply your suggestions, take a look when you can and resolve the comment if you are satisfied.

2023-04-22 18:55 UTC, PaablooCH submitted a review, later dismissed

2023-04-22 19:53 UTC, DADSILVER submitted a review, later dismissed

2023-04-22 20:29 UTC, Dedado3000 approved these changes

2023-04-22 21:18 UTC, markmeliaa approved these changes

2023-04-22 21:31 UTC, DADSILVER approved these changes

2023-04-22 22:01 UTC, merged