Feat : Efficient rendering persistent buffer and double buffer
Horizons-Games/Axolotl-Engine pull request #303
Opened 2023-04-21 14:52 UTC by AlexisDieu

- Add the persistent buffer in order to have better performance
- Create double buffer to manage a change the buffer each frame for more performance and better synchronization

2023-04-21 23:30 UTC, PaablooCH requested changes
i leave you some correction but the most important is the creation of dirtyBatch, i would like to talk about it

2023-04-21 23:30 UTC, PaablooCH commented on Source/DataModels/Batch/BatchManager.cpp
> +	if (batch->dirtyBatch)
why you change the flow of the batch doing this? you are deleting buffers and recreating them, maybe i miss something, but i prefer our previous version

2023-04-21 23:30 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	GLbitfield createFlags = mapFlags | GL_DYNAMIC_STORAGE_BIT;
At this two variables to the constructor

2023-04-21 23:30 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	Material* materialData;
why this is needed? i understand the purpose of having the transformData, but material is something that wouldn't change

2023-04-21 23:30 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.cpp
> +	program = App->program->GetProgram(ProgramType::MESHSHADER);
program is a class variable initializated in constructor, this line can be deleted

2023-04-21 23:30 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	Material* materialData;
in the pdf only talks about model matrix
![image](https://user-images.githubusercontent.com/62140600/233748054-7bb37131-6626-47b5-a7dd-f713e4cfcd0a.png)
so it is not necessary

2023-04-22 11:02 UTC, AlexisDieu commented on Source/DataModels/Batch/BatchManager.cpp
> +	if (batch->dirtyBatch)
Yeah exactly because I am using persistent buffer now that is immutable so i need to re create the batch every time we add or delete a component and this solution is to do that and be able to re do all persistent buffer correctly, it's not really costly because it's only done on Engine mode and it's the only way to redo the size of a persistant buffer

2023-04-22 11:05 UTC, AlexisDieu commented on Source/DataModels/Batch/GeometryBatch.h
> +	Material* materialData;
It's only talking of model in the pdf but do a persistent buffer of the materials is not that bad I think but I am open to talk about it to know which one is better, in did i tried also to do double buffer for material but is really not a good idea cause of the instance that get broken really quickly when adding or deleting but yet make a persistent buffer is not that bad (also because I redo the batch when adding or removing and the way we delete material by remplacing with a default one fit correctly with the persistnt buffer idea)

2023-04-22 11:07 UTC, AlexisDieu commented on Source/DataModels/Batch/GeometryBatch.cpp
> +	program = App->program->GetProgram(ProgramType::MESHSHADER);
True I had a bug for a moment and I put that to test but forgot to delete it

2023-04-22 11:13 UTC, AlexisDieu commented on Source/DataModels/Batch/GeometryBatch.h
> +	enum { DOUBLE_BUFFERS = 2 };
I think enumeration in this case may be considered better practice because it provides more type safety because it's hard typed and can only use the value defined in the enumeration but I can change it I you think it's better +enumaration can be use in switch statements and i use this value a bunch of times and in some case switch can be an idea !

2023-04-22 11:18 UTC, AlexisDieu commented on Source/DataModels/Batch/GeometryBatch.cpp
> +	if (frame == 0)
i tried but it's not working because frame is not a boolean but a int (because it can go to 2 if we will use triple buffer in futur) what i can do it's try to calculate it with a modulo but i don't like this idea , it will be like 	frame = (frame + 1) % DOUBLE_BUFFERS;

2023-04-22 11:24 UTC, AlexisDieu commented on Source/DataModels/Batch/GeometryBatch.h
> +	Material* materialData;
Well in fact i found an issue when deleting a material only and persitant buffer so I keep the idea in mind but I am gonna use normal SSBO once again I guess

2023-04-24 14:13 UTC, PaablooCH requested changes
new things:
PS: check the previous one also thx

2023-04-24 14:13 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	enum { DOUBLE_BUFFERS = 2 };
now is just a number that is repeat it a bunch of times, constexpr could be also an option because is fast in compilation time. We can leave this as a tie between us and if someone wants to aport something can untie 👍

2023-04-24 14:22 UTC, AlexisDieu commented on Source/DataModels/Batch/BatchManager.cpp
> +	if (batch->dirtyBatch)
In fact I did it lik that because i found that bindBatch had already a lot of if() exception and one more will make it maybe less clear to read (i also thought about move the creation of command and transforms in a function then call them in bind batch instead of doing it there) but you right it's just it was the easiest way for me and more visually clear ! For the redo of buffer you right but as i said before I would like to do a function for transforms and command and when it's dirty I call it and redo it and not all buffer because you right we didn't need to recreate vertices and stuff

2023-04-26 13:36 UTC, sncarbo commented
In terms of functionality, I don't see the Skybox and the engine freezes when I try to import something. I don't know if it's a problem with my computer or not, but I want to check it. It compiles in all modes.

In terms of code, good use of OpenGL concurrency with glFenceSync, glDeleteSync and glClientWaitSync. Good use of glBufferStorage and glBindBufferRange. There are some cases where you don't apply the programming rules, such as the brackets in the line break after an if statement.

Apply the changes that Pablo asked you to make and, when I check what I said before, I will approve the pull request. 

Very good work from my point of view.

2023-05-11 18:11 UTC, closed without merging