Fix OnPlayMode
Horizons-Games/Axolotl-Engine pull request #329
Opened 2023-04-27 19:03 UTC by DADSILVER

- Fix problem with ctrl+q.
- remove a raycast not used from fucn Move(...).
- Add new raycastFirst with a exceptionGameObject.
- remove save options and other features that should not be usable during onGameMode.

2023-04-28 15:59 UTC, OriolSors requested changes
Very good job @DADSILVER! I tested in Game Mode and PlayMode:

- The Play issue with FPS is solved
- The Rotation of the player now works on PlayMode
- Good overload of the RaycastFirst. Hope you can use it while we implement the Bullet...

Unfortunately, the Drone/Enemy is falling down on PlayMode but is working fine in Game Mode. Can you check it?

2023-04-29 11:12 UTC, gerard-queralt reviewed
I see you've removed a couple calls to `SetReadyToEliminate`. Could you explain what that method does? Destroy the player game object? I'm not sure just by the name.

2023-04-29 11:17 UTC, gerard-queralt commented on Source/Physics/Physics.h
> +	static bool RaycastFirst(const LineSegment& ray, GameObject* exceptionGameObject);
Maybe `exceptionGameObject` could be a collection (C-style array or a vector), so it's more flexible.

2023-04-29 11:17 UTC, gerard-queralt approved these changes
Haven't tested, but the code looks good.

2023-04-30 07:50 UTC, DADSILVER commented on Source/Physics/Physics.h
> +	static bool RaycastFirst(const LineSegment& ray, GameObject* exceptionGameObject);
I understand that this is looking to the future, but right now we wouldn't use it and we don't know if we will ever use it. That's why I think it's better not to implement it or to wait until it's necessary :)

2023-04-30 07:52 UTC, DADSILVER commented
> I see you've removed a couple calls to `SetReadyToEliminate`. Could you explain what that method does? Destroy the player game object? I'm not sure just by the name.

Thanks for reminding me. It is a function that was used in the rigged body but is no longer needed. I have removed it.

2023-04-30 13:34 UTC, AlexisDieu commented
- First fps looks great I am around 50fps everytime
- I can move and rotate without any problem
- if i wait the drone can pass through me 
![image](https://user-images.githubusercontent.com/73070531/235354898-34b70825-6444-4f50-9a01-0a714696c503.png)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/73070531/235355177-458260df-7f91-4250-b66c-ba31109be05b.gif)
- I also see some raycast issue because only with walking i can pass through object 
![image](https://user-images.githubusercontent.com/73070531/235355256-9afe82a9-03d3-448f-b8cd-ca8579dbfab1.png)
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/73070531/235355684-89aa41bf-41f9-4f6c-b2e5-fed83165bdea.gif)

Else everything seems great !

2023-04-30 18:24 UTC, MarcGonzalezMoratona commented
I have this error when pressing ctrl + x

![image](https://user-images.githubusercontent.com/80526953/235369960-443f5eb0-a92a-4b30-91cc-9f50564ee9e9.png)
![image](https://user-images.githubusercontent.com/80526953/235369973-d147ed77-ae70-41ed-9e8a-75fdef09873a.png)
![image](https://user-images.githubusercontent.com/80526953/235369921-41ac8d53-f948-4699-93b3-66b0a0ccdbd0.png)

2023-04-30 18:27 UTC, MarcGonzalezMoratona commented
I see in the description that you fixed Ctrl + q but I don't see anything related to this in the code. What is this shortcut supposed to do? Can you explain me the ctrl + q changes?

2023-04-30 20:16 UTC, DADSILVER commented
> I see in the description that you fixed Ctrl + q but I don't see anything related to this in the code. What is this shortcut supposed to do? Can you explain me the ctrl + q changes?

In moduleinput in the line 198 more or less. GitHub doesn't show theses lines because the change is inside the función.

2023-04-30 20:39 UTC, gerard-queralt commented
Hi @MarcGonzalezMoratona, there was an error with deleting GameObjects that's been mostly fixed. #330 should have fixed the crash, and in #332 fixes a non-breaking bug where the non-static objects weren't removed from the list in Scene. Could you try merging develop locally to see if the crash still occurs?

2023-04-30 21:51 UTC, MarcGonzalezMoratona commented
> Hi @MarcGonzalezMoratona, there was an error with deleting GameObjects that's been mostly fixed. #330 should have fixed the crash, and in #332 fixes a non-breaking bug where the non-static objects weren't removed from the list in Scene. Could you try merging develop locally to see if the crash still occurs?

I see that supr does not remove the objects from the Hierarchy, Ctrl + X works, but not Ctrl + V or Ctrl + D.

I also see that if you create an empty GameObject, then Ctrl + X and Ctrl + V for this GameObject, there is an error:
![image](https://user-images.githubusercontent.com/80526953/235377760-21515900-22eb-41b2-8a57-3dae8e914aaa.png)
![image](https://user-images.githubusercontent.com/80526953/235377767-5e992653-003e-47cd-ac7f-eda861d49aa7.png)
![image](https://user-images.githubusercontent.com/80526953/235377770-4e9dad8d-8b22-46c3-84b9-8fe03e6b7e3c.png)

2023-04-30 21:53 UTC, MarcGonzalezMoratona commented
> Hi @MarcGonzalezMoratona, there was an error with deleting GameObjects that's been mostly fixed. #330 should have fixed the crash, and in #332 fixes a non-breaking bug where the non-static objects weren't removed from the list in Scene. Could you try merging develop locally to see if the crash still occurs?

Also tried to make Ctrl+X on the scene, the parent of all GameObjects and got this error:
![image](https://user-images.githubusercontent.com/80526953/235377843-d0f9665e-d375-41a7-80f6-02e77a6d967d.png)
![image](https://user-images.githubusercontent.com/80526953/235377846-7ffaaf1c-b3d3-4510-b089-483630d95f47.png)

2023-05-01 08:51 UTC, gerard-queralt commented
Thanks Marc, I'll take a look.

2023-05-01 09:42 UTC, gerard-queralt commented
Should be fixed in #334 @MarcGonzalezMoratona

2023-05-02 20:30 UTC, gerard-queralt approved these changes

2023-05-02 20:32 UTC, OriolSors approved these changes

2023-05-02 20:33 UTC, merged