Import Scene
Horizons-Games/Axolotl-Engine pull request #338
Opened 2023-05-03 08:51 UTC by Dedado3000

New Button Added that allows yo to import a scene into another scene, giving facilities to merge work in diferent parts of level design.

Knowed Bug:
You can't import an scene with an script that have a pointer to a gameobject, Im currently working on it but doesn't affect the motive for what we use this.

2023-05-03 10:21 UTC, gerard-queralt reviewed
Added a few questions, would like to know yours and @AuxPort66's opinion.

2023-05-03 10:21 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.h
> +#include "WindowImportScene.h"
Use a forward declaration. Now that I notice, we should use them for the other windows as well, if possible.

2023-05-03 10:21 UTC, gerard-queralt commented on Source/Modules/ModuleScene.cpp
> +void ModuleScene::ImportFromJson(const std::string& filePath)
Could this be done in the (currently unused) `SceneImporter`? This way we could do asyncronous importing just reusing the code in `ModuleResources`. It would require actually implementing the `SceneResource` class as well, but that's also a bit overdue in my opinion, especially once we start having many scenes.

2023-05-03 10:21 UTC, gerard-queralt commented on Source/Modules/ModuleScene.cpp
> +	loadedScene->AddSceneCameras(loadedCameras);
Maybe create a new method, I don't know, `MergeScenes`, that encapsulates this logic? Following the above comment, maybe it can also be in `SceneImporter`.

2023-05-03 10:30 UTC, Dedado3000 commented on Source/Modules/ModuleScene.cpp
> +void ModuleScene::ImportFromJson(const std::string& filePath)
I don't know if using asyncronous importing there have problems because what will you do while is loading the scene to include in the scene? you can't work until it finish

2023-05-03 13:39 UTC, gerard-queralt commented on Source/Modules/ModuleScene.cpp
> +void ModuleScene::ImportFromJson(const std::string& filePath)
"Asyncronous" might have been a strong word. Currently what's done when a resource is imported is display a "Loading" window, so the user has some visual feedback. That's what I meant :P

2023-05-03 13:41 UTC, AuxPort66 requested changes

2023-05-03 13:41 UTC, AuxPort66 commented on Source/Modules/ModuleScene.cpp
> +	std::unordered_map<UID, UID> uidMap{};
Like I say before, changing the UIDs of a GameObject inside the scene it's problematic, not only for the dependencies of their childrens, that have the UID, also for scripting, because we can save a reference to a gameObject, and that reference is saved with the UID.

So we are destroying the scripting dependencies of all scenes, even the ones that don't need to change the UID because they don't have the same root.

In any case, if you want to load 2 identical scenes, it's an acceptable risk that your scripting will be pointing to the original gameObject, you can check that they are the same scene and do this by looking at the UID of the root, but you can have this functionality with a ctrl+c ctrl +v, you don't need a full load function for this.

2023-05-03 16:59 UTC, Dedado3000 commented on Source/DataModels/Windows/WindowMainMenu.h
> +#include "WindowImportScene.h"
I don't know what but i can't use a forward declaration, can we check together? im feeling so dumb

2023-05-03 17:42 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.h
> +#include "WindowImportScene.h"
It's possible it can't be done in this case ^^'

2023-05-03 17:48 UTC, gerard-queralt commented on Source/DataModels/Windows/WindowMainMenu.h
> +#include "WindowImportScene.h"
Nope, you definitely can, make sure to include the actual class in the source file.

2023-05-03 17:48 UTC, gerard-queralt submitted a review, later dismissed

2023-05-03 17:48 UTC, gerard-queralt commented on Source/WindowImportScene.h
Put these new files in the proper folder.

2023-05-03 17:56 UTC, Dedado3000 commented on Source/WindowImportScene.h
Check it guapetón

2023-05-03 17:56 UTC, Dedado3000 commented on Source/Modules/ModuleScene.cpp
> +	std::unordered_map<UID, UID> uidMap{};
Guapetona, is okey now?

2023-05-03 22:59 UTC, Dedado3000 commented on Source/DataModels/Windows/WindowMainMenu.h
> +#include "WindowImportScene.h"
Okey they where other includes from imguy needed that where included in  a include from an include, and obviously i was missing it

2023-05-09 17:22 UTC, AuxPort66 submitted a review, later dismissed

2023-05-09 18:13 UTC, gerard-queralt approved these changes

2023-05-09 18:33 UTC, AuxPort66 approved these changes

2023-05-09 18:59 UTC, merged