feat [Game play]: separate scrip movility into rotation and move
Horizons-Games/Axolotl-Engine pull request #352
Opened 2023-05-06 20:05 UTC by DADSILVER

- The mobility script is divided into two scripts.
- Added a collision function for rotation (We seek to avoid colliding with the ground).
- updated the scene.

2023-05-06 22:58 UTC, gerard-queralt commented on Game/Scripts/PlayerMoveScript.h
> +	float GetSpeed() const;
As a reminder, all these getters and setters are not needed if you're not using the `REGISTER_FIELD_WITH_ACCESSORS` macro.

2023-05-07 17:00 UTC, markmeliaa submitted a review, later dismissed
Everything works and looks correct, thank you David!

2023-05-08 16:44 UTC, gerard-queralt requested changes

2023-05-08 16:53 UTC, DADSILVER commented on Game/Scripts/PlayerMobilityScript.cpp
> +			moveScript->GetScript()->Start();
The scrip is disable, so i need call start, preupdate...

2023-05-08 17:14 UTC, gerard-queralt commented on Game/Scripts/PlayerMobilityScript.cpp
> +			moveScript->GetScript()->Start();
Do they need to be disabled though? I feel like this might create issues down the line if someone forgets about disabling them, but could be wrong.

2023-05-08 18:02 UTC, OriolSors commented on Game/Scripts/PlayerRotationScript.cpp
> +	if (collider->IsRotationColliding(frontPoints, -direction, trans->GetLocalAABB().Size().z * 0.00f))
Are you passing a 0 value in the size? How are you doing the raycast then?

2023-05-08 18:02 UTC, OriolSors commented on Source/DataModels/Components/ComponentMeshCollider.cpp
> +	startingPoints[3].y -= 0.25f;
What is the purpose of these offsets?

2023-05-09 17:10 UTC, DADSILVER commented on Game/Scripts/PlayerRotationScript.cpp
> +	if (collider->IsRotationColliding(frontPoints, -direction, trans->GetLocalAABB().Size().z * 0.00f))
I changed and nothing happened. So I forgot put it back again this vale.

2023-05-09 17:15 UTC, DADSILVER commented on Game/Scripts/PlayerMobilityScript.cpp
> +			moveScript->GetScript()->Start();
For now, we believe this is the best way to do it. It may be changed at a later date.

2023-05-09 18:09 UTC, UriMurcia commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_SPACE) == KeyState::DOWN && jumps > 0)
same for jump. I think would be better to separate, jump, crouch and dash in different scripts, but not the movement and rotation

2023-05-09 18:53 UTC, markmeliaa commented on Game/Scripts/PlayerMobilityScript.cpp
> +			moveScript->GetScript()->Start();
If we keep the functionality of the gameplay in small scripts, we will need a general script for each entity that manages the scripts that the enitity will support (as for example the player with move/rotate or the drone with patrol/seek). That said, I agree that disabling every other script and only keeping active the manager one is not a good solution, but for now we are working like that until we have a better solution.

2023-05-09 18:58 UTC, markmeliaa commented on Game/Scripts/PlayerMobilityScript.cpp
> +			rotateScript->GetScript()->PreUpdate(deltaTime);
Already adressed here https://github.com/Horizons-Games/Axolotl-Engine/pull/352#discussion_r1187658111

2023-05-09 19:08 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_SPACE) == KeyState::DOWN && jumps > 0)
This is related to what we talk in the discord once, I find separating behaviours in different scripts a good idea (one for attack, one for movement, one for rotation, one for health...), but maybe having one for jump, another one for crouch and another one for the dash is way too much (we are working on creating a Jump(), Crouch(), Dash() functions but for now David told me that we cannot decouple them so easily, so we'll do it in the future).

I don't find the usefulness of having scripts as divided as you say because no single entity in our game will dash, crouch or jump apart from the two main characters (who will also move, that's why all those actions are together). I mean, it is good to keep in mind the "one script should do one thing" principle, but only if that one thing is or would be reused by any other entity in our game (which is why the patrol and seek behaviours are separated into different scripts but the jump and crouch are not).

2023-05-09 19:09 UTC, markmeliaa commented on Game/Scripts/PlayerMobilityScript.cpp
> +	componentPlayer = static_cast<ComponentPlayer*>(owner->GetComponent(ComponentType::PLAYER));
There is a reason why ComponentPlayer is not yet dead, @DADSILVER explained it to me but I can't remember now, so he'll give you an answer.

2023-05-09 19:12 UTC, markmeliaa commented on Game/Scripts/PlayerRotationScript.cpp
> +		trans->UpdateTransformMatrices();
It could in fact, yep.

2023-05-10 05:53 UTC, diegusmejia117 commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_SPACE) == KeyState::DOWN && jumps > 0)
We havent discussed it but maybe the mini bosses or the boss migh be able to jump, dash or crouch, so i think is valuable to have it separated, but as you said Mark, its not needed right now. So for now we can leave it like this but in the future we would have to separate it we we need it.

2023-05-10 10:18 UTC, gerard-queralt commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_SPACE) == KeyState::DOWN && jumps > 0)
Another thing to consider is what both characters can do, which I don't know so maybe my point is moot. But if we want to make it so, say, only Bix can dash because she is more agile or something, it'd be better to have them separated. Again, maybe this doesn't apply to our game, I'm not up to date with the mechanics.

2023-05-10 17:34 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_SPACE) == KeyState::DOWN && jumps > 0)
The basic moveset will be the same for both Bix and Allura, the only thing that will differentiate them is that one of them has melee attacks and the other one ranged attacks (that's why the attack will go in a separate file).

2023-05-11 16:50 UTC, DADSILVER commented
> Commenting here because after the merge with develop I can't view the files changed. I noticed that the destructor of `PlayerMobilityScript` calls `delete` on one of the components of the owner of the script. You shouldn't do this, this memory is owned by the game object.

Changed, thx.

2023-05-11 17:14 UTC, DADSILVER commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_SPACE) == KeyState::DOWN && jumps > 0)
I see your point, but actually the problem we have is that the gravity calculation is in the rigbody but the calculation of not falling into the void is in the ScriptMove. And all the functions of the movement have this values in common. That's why I decided to keep them in the same script until we can separate them better.

2023-05-11 17:17 UTC, markmeliaa approved these changes

2023-05-19 06:49 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.h
> +// Little fix until we could check if an audio is being reproduced
```suggestion
// Small fix until we can check if an audio is being played
```

2023-05-19 06:52 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerRotationScript.cpp
> +	//Corroborate that you don't fuse with a owner
What do you mean with "fuse"?
```suggestion
	//Corroborate that you don't fuse with an owner
```

2023-05-25 22:23 UTC, closed without merging