perf: Quadtree refactor
Horizons-Games/Axolotl-Engine pull request #355
Opened 2023-05-08 16:29 UTC by Dedado3000

Full rework of quadtree based on Task #865c2x27z
- No more duplicated render
- Remove "Shared GameObject", only object at leaves
- More eficient rendering selected game object

2023-05-09 13:43 UTC, gerard-queralt reviewed
Do we know the cause of #217? Because a GameObject shouldn't appear in the quadtree twice, even before this refactor, or am I wrong? I thought we fixed that.
Also, I don't know if the vector `drawnGameObjects` can be removed, since it was used to prevent a game object from being drawn twice, even if it appeared multiple times in the vector to drawn.

2023-05-09 17:14 UTC, Dedado3000 commented
> added

In fact #217 was one of the focus of this refactor and is solved with this pr

2023-05-10 00:32 UTC, PaablooCH requested changes
Plus some code refactor and questions, i loaded the first scene and count the gameobject that has (i delete some like the whole blockout father and cameras) and compared them with the size of opaquesToDraw and is like 320~ vs 407, can you check it too?

2023-05-10 00:32 UTC, PaablooCH commented on Source/DataStructures/Quadtree.h
> +	void RecalculateQuadtree();
is this function called somewhere?

2023-05-15 19:02 UTC, Dedado3000 commented on Source/Modules/ModuleRender.h
> +	std::set<const GameObject*> opaqueGOToDraw;
Im looking for efficiency

2023-05-15 19:10 UTC, Dedado3000 commented on Source/DataStructures/Quadtree.cpp
> +	this->GetFamilyObjects(familyGameObjects);
well, this was deleted bc was unused.

2023-05-15 19:13 UTC, Dedado3000 commented on Source/DataStructures/Quadtree.h
> +	void RecalculateQuadtree();
I think that was something that was dropped after some conversation at physics meetings

2023-05-15 19:19 UTC, Dedado3000 commented on Source/Modules/ModuleRender.h
> +	std::set<const GameObject*> opaqueGOToDraw;
Okey, as we are deleting every frame and rebuilding is more eficiency using a normal Set, unordered_set is better in a case we will mantain the "vector" across the ticks and we will not rebuild it so frequently

2023-05-16 10:05 UTC, PaablooCH commented on Source/DataStructures/Quadtree.cpp
> +	this->GetFamilyObjects(familyGameObjects);
> we don't have any standard about this, should we?

I think that we already have it, but i could be wrong, plus we have a task https://app.clickup.com/t/865bph92u where we deleted unnecessary `this->`

2023-05-18 10:37 UTC, OriolSors commented on Source/Modules/ModuleRender.cpp
> +					static_cast<ComponentTransform*>(gameObject->GetComponent(ComponentType::TRANSFORM));
Why are you retrieving the transform again?

2023-05-18 10:37 UTC, OriolSors commented on Source/Modules/ModuleRender.cpp
> +					float addDistance = 0.0001f;
Maybe we can start putting epsilon offsets like this in a Local configuration or something? Abro debate

2023-05-19 20:28 UTC, PaablooCH commented on Source/Modules/ModuleRender.h
> +	std::set<const GameObject*> opaqueGOToDraw;
are u sure about that? for what i found it's the same as map/unordered_map and if we are rebuilding the structure every frame an unordered_set could fit better.

2023-05-19 20:49 UTC, PaablooCH submitted a review, later dismissed

2023-05-19 22:04 UTC, Dedado3000 commented on Source/Modules/ModuleRender.cpp
> +					float addDistance = 0.0001f;
this is someone from graphics, you can speak with them but seems ok

2023-05-19 22:04 UTC, Dedado3000 commented on Source/Modules/ModuleRender.cpp
> +					static_cast<ComponentTransform*>(gameObject->GetComponent(ComponentType::TRANSFORM));
Mental lag, solved

2023-05-20 00:15 UTC, PaablooCH approved these changes

2023-05-20 10:08 UTC, OriolSors approved these changes

2023-05-20 10:08 UTC, merged