Feat: Object doesn't move when changing parent
Horizons-Games/Axolotl-Engine pull request #359
Opened 2023-05-09 16:14 UTC by Dedado3000

2023-05-09 16:16 UTC, ericdacal submitted a review, later dismissed

2023-05-09 16:37 UTC, gerard-queralt requested changes

2023-05-09 16:37 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentTransform.h
> +	void CalculateLocalFromNewGlobal( float4x4 globalMatrix );
```suggestion
	void CalculateLocalFromNewGlobal(const float4x4& globalMatrix );
```

2023-05-09 19:27 UTC, markmeliaa requested changes

2023-05-09 19:27 UTC, markmeliaa commented on Source/DataModels/GameObject/GameObject.cpp
> +	if (transform && newParentTransform)
What is this check for?

2023-05-09 19:27 UTC, markmeliaa commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +                    bool newParentSelected = std::find(std::begin(listSGO), std::end(listSGO), gameObject) != std::end(listSGO);
Line length pls, this has 129 characters

2023-05-09 19:27 UTC, markmeliaa commented on Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
> +                    else if (!actualParentSelected && newParentSelected)
What is the point of this `if` and `else if`? They just remove and add the same gameobjects again?

2023-05-16 17:12 UTC, DADSILVER approved these changes

2023-05-16 17:13 UTC, markmeliaa approved these changes

2023-05-16 17:14 UTC, gerard-queralt approved these changes

2023-05-19 06:42 UTC, MarcGonzalezMoratona commented on Source/DataModels/Components/ComponentTransform.cpp
> +// This will calculate the new local that the object needs to be iin order not to move with the change of father
```suggestion
// This will calculate the new local that the object needs to be in order not to move with the change of father
```

2023-05-20 10:06 UTC, OriolSors approved these changes

2023-05-20 10:06 UTC, merged