feat: vector3 added as script field parameter
Horizons-Games/Axolotl-Engine pull request #363
Opened 2023-05-10 17:47 UTC by Piterga12

It has been added a vector3 to scripting (is implemented in defaultScript) and it serializes as the rest of the parts of scripting

2023-05-10 18:45 UTC, gerard-queralt approved these changes
Thanks Peter, everything looks good!

2023-05-11 12:01 UTC, markmeliaa requested changes
Thanks for your work Peter, just some small things.

2023-05-11 12:01 UTC, markmeliaa commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
> +					if(ImGui::InputFloat3(float3Field.name.c_str(), (&value[2], &value[1], &value[0]), "%.2f"))
Maybe this could be a `DragFloat` instead of an `InputFloat`?

2023-05-11 17:05 UTC, gerard-queralt commented on Game/Scripts/DefaultScript.h
> +#include "Math/float3.h"
No, because we are storing the `float3` as a refrence, and references can't be forward declared since the compiler needs to know their sice at compile time, unlike pointers. Peter managed to remove it because it's included somewhere in `Script.h`, probably `GameObject`.

2023-05-11 17:11 UTC, markmeliaa approved these changes
Ty for the changes Peter! If you could fix the merge conflict everything should be good to go.

2023-05-11 17:15 UTC, Piterga12 commented
Merge conflict resolved and i also removed the forward declaration as Gerard said not to. Thanks for all the comments Mark

2023-05-11 17:44 UTC, merged