Efficient rendering develop
Horizons-Games/Axolotl-Engine pull request #364
Opened 2023-05-10 18:10 UTC by MacXxs

2023-05-10 18:12 UTC, AlexisDieu submitted a review, later dismissed

2023-05-10 18:40 UTC, sncarbo requested changes
When I try to create a Cube and another 3D object the program crashes. This is the call stack:
![ef1](https://github.com/Horizons-Games/Axolotl-Engine/assets/116657602/13fa9dc9-df5d-451c-8732-d2d7c3f326e1)

2023-05-10 18:48 UTC, AlexisDieu commented
> When I try to create a Cube or another 3D object the program crashes. This is the call stack: ![ef1](https://user-images.githubusercontent.com/116657602/237485406-13fa9dc9-df5d-451c-8732-d2d7c3f326e1.png)

Is the command.size() is equal to 0 when it crash ?

2023-05-10 18:52 UTC, MacXxs commented
> When I try to create a Cube or another 3D object the program crashes. This is the call stack: ![ef1](https://user-images.githubusercontent.com/116657602/237485406-13fa9dc9-df5d-451c-8732-d2d7c3f326e1.png)

Hi Santi! Have you tried deleting Lib? For us is not crashing so maybe it's that. If not we are going to keep looking into it!

2023-05-10 19:03 UTC, sncarbo commented
> > When I try to create a Cube or another 3D object the program crashes. This is the call stack: ![ef1](https://user-images.githubusercontent.com/116657602/237485406-13fa9dc9-df5d-451c-8732-d2d7c3f326e1.png)
> 
> Hi Santi! Have you tried deleting Lib? For us is not crashing so maybe it's that. If not we are going to keep looking into it!

I deleted `Lib` but still not working. I will keep looking.

2023-05-10 19:06 UTC, AlexisDieu commented
> > > When I try to create a Cube or another 3D object the program crashes. This is the call stack: ![ef1](https://user-images.githubusercontent.com/116657602/237485406-13fa9dc9-df5d-451c-8732-d2d7c3f326e1.png)
> > 
> > 
> > Is the command.size() is equal to 0 when it crash ?
> 
> Yes, `command.size()` is 0.

Can you test with the new commit

2023-05-10 19:43 UTC, sncarbo commented
@MacXxs @AlexisDieu It no longer crashes, but I have found a weird bug. I created a box inside a loaded scene and, when I change the parameters of the box material, it seems that they are also changed in the environment. It is possible that the parameters of several mesh renderers in the same batch are changed at the same time.

https://github.com/Horizons-Games/Axolotl-Engine/assets/116657602/e3a73fb3-f41a-47e3-8508-8e9a335e1ed3

2023-05-10 19:44 UTC, MacXxs commented
> @MacXxs @AlexisDieu It no longer crashes, but I have found a weird bug. I created a box inside a loaded scene and, when I change the parameters of the box material, it seems that they are also changed in the environment. It is possible that the parameters of several mesh renderers in the same batch are changed at the same time.
> 
>  error.ef.mp4

Hi Santi! That's normal, the cube is using the same default material as the environment, that's why they change.

2023-05-10 20:03 UTC, sncarbo commented
@MacXxs You are right, the material is common to all GOs. There is another bug if you create a spot light and try to change it to point light in the spot light panel (or vice versa) it crashes. It's similar to the error that Pablo got in IBL, and it's solved in develop, but I don't know if it's the same. The call stack is as follows:

![ef1](https://github.com/Horizons-Games/Axolotl-Engine/assets/116657602/3a1b45c1-23a9-445d-9b16-cda9af06f77d)

2023-05-10 20:14 UTC, MacXxs commented
> @MacXxs You are right, the material is common to all GOs. There is another bug if you create a spot light and try to change it to point light in the spot light panel (or vice versa) it crashes. It's similar to the error that Pablo got in IBL, and it's solved in develop, but I don't know if it's the same. The call stack is as follows:
> 
> ![ef1](https://user-images.githubusercontent.com/116657602/237501916-3a1b45c1-23a9-445d-9b16-cda9af06f77d.png)

Yeah this will be fixed with the second merge with develop. This first merge was with a version of develop of three/four weeks ago, so with the second merge after this PR is approved, it will be fixed!

2023-05-10 20:29 UTC, PaablooCH requested changes
well done, it costs a lot but we are close, a part of the changes  remember to delete comments and check the includes 👍

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.cpp
> +	bool findMaterial = false;
this boolean can be inside of the loop and then we don't need to set it to false each loop, or we can also delete this variable and put the if(findMaterial) inside of the first if

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.cpp
> +	componentToMove.clear();
this class variable is used in other place? we can just create the vector here

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.cpp
> +				else if (selected)
```suggestion
				else
```

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +#include "Math/float2.h"
this include is already in .cpp

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +#include <map>
this is not used

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	bool CleanUp();
make it private

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	bool IsFillMaterials() const;
not used

2023-05-10 20:29 UTC, PaablooCH commented on Source/DataModels/Batch/GeometryBatch.h
> +	bool dirtyBatch;
make it private?

2023-05-11 10:30 UTC, AlexisDieu reviewed
I fix the last issue I said with this

2023-05-11 10:45 UTC, AlexisDieu commented
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/73070531/abdd1202-466e-4944-a05c-367a6016a0a9)
Changing the scene make the engine crash (not happening before the commit again i verified)

2023-05-11 15:59 UTC, MacXxs commented
> ![image](https://user-images.githubusercontent.com/73070531/237660189-abdd1202-466e-4944-a05c-367a6016a0a9.png) Changing the scene make the engine crash (not happening before the commit again i verified) It seems to enter in deleteComponent but the vector of component it's empty (It occur because i but back the batch->DeleteComponent(this); i think but else there was another issue and i just revert the change

Hi! I told you again from here so everybody knows. This wasn't happening before 'cause the batches were never destroyed because the batchmanager cleanup was inlined, and when doing deletes inside inline functions don't work, so the destructor of the objects to delete are never called. That's why you could change, remove and add stuff from a scene, 'cause the pointers to that batch in the componentMeshRenderer were pointing to batches that were never truly destroyed. I've fixed this so now everything is propertly being deleted.

2023-05-11 19:42 UTC, AlexisDieu approved these changes

2023-05-12 13:51 UTC, sncarbo approved these changes

2023-05-13 09:52 UTC, PaablooCH approved these changes

2023-05-13 13:27 UTC, merged