feat: Physics with Bullet
Horizons-Games/Axolotl-Engine pull request #385
Opened 2023-05-17 14:15 UTC by OriolSors

Main features

- Collision management with Bullet in the new ModulePhysics
- Modifiable basic RigidBody Shapes in ImGui
- Proportional Controller adapted to Bullet RigidBody
- New Scene and new Script as "testing" reference

2023-05-17 17:34 UTC, DADSILVER approved these changes
Nice job!!!

2023-05-17 20:05 UTC, gerard-queralt requested changes
Aside from all the comments, I have a general question regarding this implementation. Is there a particular reason for not having separate classes for each of the shapes? So, a `ComponentBoxColider`, `ComponentCapsuleColider`... Maybe not even a component, just a different class from which all these colliders inherit from, and the Component just holds an instance of it, similar to the relation between a `ComponentScript` and a `Script`. As it stands, it feels to me that there is a lot of useless information in the component. For instance, if the shape is a Box, the radius is invalid, right? Similarly, judging by the name, a Sphere won't have a boxSize.

2023-05-17 20:05 UTC, gerard-queralt commented on Source/Modules/ModulePhysics.h
> +class GLDebugDrawer : public btIDebugDraw
As I said, I think this is complex enough to warrant its own file.

2023-05-17 20:05 UTC, gerard-queralt commented on Source/Modules/ModulePhysics.h
> +	uint64_t GetAmountOfRigidBodies() const { return rigidBodyComponents.size(); }
Inline outside of class body.

2023-05-17 20:05 UTC, gerard-queralt commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
Why are these `unordered_map`s instead of regular `map`s?

2023-05-18 01:36 UTC, AuxPort66 commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
For some of the changes or questions about modulePhysics we will have to ask Ruben, because it is from him. In order to not slow down this PR waiting for us to have a class with him so we can ask him some of these things with calm, we are going to leave it as the module has given us, for now.

2023-05-18 05:50 UTC, gerard-queralt commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
Can't we not do what we think is best, and if we are wrong, correct it later? As we've learned, `unordered_map`s have very niche use cases, and I'm wondering if this is one of them. For instance, in one of the other comments I noticed we are doing the same insertion on the map twice. If I recall correctly, this is significantly more expensive with an unordered map rather than a regular one.

2023-05-18 11:46 UTC, AuxPort66 commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
If I do what we think and not what we know is better without consulting someone else who knows more about the module that I don't know so well, I am exposing this to screwing up something very delicate such as physics. I find it's a better use of time to ask.

2023-05-18 12:17 UTC, AuxPort66 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    App->GetModule<ModulePhysics>()->AddRigidBody(this, rigidBody);
On Line 152, on the same Function they are removing the RigidBody, So they need to added after that.

2023-05-18 12:20 UTC, Dedado3000 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    int value = 0;
This is only a count to the module count hbow much is gonna draw

2023-05-18 13:16 UTC, AuxPort66 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    motionState = new btDefaultMotionState(startTransform);
I can't promise that we have full authorship on those pointers because I don't know what the library does with it and it uses various functions that remove and work with the rigidbody.

Tried to put unique ptrs but it gave some problems, so that's the answer.

2023-05-18 14:37 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    motionState = new btDefaultMotionState(startTransform);
If we are allocating the memory, we should also be freeing it, which we are not doing. Either we check the documentation to see if they are indeed taken care of by Bullet, or we can just check if it's leaking directly. Also, I can't help you if you don't specify which problems you had.

2023-05-18 14:47 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    motionState = new btDefaultMotionState(startTransform);
Just noticed that the memory leak has been fixed. So we allocate and free the memory, therefore, we own it. I don't see why it can't be a unique pointer.

2023-05-18 14:53 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    int value = 0;
The point was that maybe we can use a more descriptive name.

2023-05-18 17:07 UTC, gerard-queralt commented
Might be doing something wrong, but while testing, the rigid body seems to still be simulated even when disabled.

2023-05-18 17:17 UTC, AuxPort66 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    motionState = new btDefaultMotionState(startTransform);
> If we are allocating the memory, we should also be freeing it, which we are not doing. Either we check the documentation to see if they are indeed taken care of by Bullet, or we can just check if it's leaking directly. Also, I can't help you if you don't specify which problems you had.

Helping out on github issues takes more time than asking you later in person. And as I said before I'd rather fix the memory leak and look at this calmly than block a physics base for this, because it's a base not the definitive work on physics. I told David to give it a try, but if he had a problem that he couldn't fix quickly, he'd do a delete for the moment.

2023-05-18 17:19 UTC, AuxPort66 commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
> For some of the changes or questions about modulePhysics  <---

For some changes, this include all the questions about modulePhysics. Not only this question

2023-05-18 17:37 UTC, AuxPort66 commented
> Might be doing something wrong, but while testing, the rigid body seems to still be simulated even when disabled.

I tested it with a normal rigidbody and seams to work correctly. Is it with a scene? Maybe it's with a script?

2023-05-18 18:02 UTC, AuxPort66 commented
> Might be doing something wrong, but while testing, the rigid body seems to still be simulated even when disabled.

Fixed! Thank you for testing

2023-05-18 18:46 UTC, Dedado3000 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    assert(nextId != 0); //if this assert triggers, we have reached the maximum number of rigidbodies 2^32 - 1. This is a very unlikely scenario.
Im having the same question, but if it works i don't wanna break it

2023-05-18 18:49 UTC, Dedado3000 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    //TODO: Implement delegate for this
well, people on gameplay should know the state of the engine with the meetings and asking, doesnt'0t seems relevant to me

2023-05-18 18:50 UTC, Dedado3000 commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +        currentShape = static_cast<int>(newShape);
done

2023-05-18 19:47 UTC, solidajenjo commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    assert(nextId != 0); //if this assert triggers, we have reached the maximum number of rigidbodies 2^32 - 1. This is a very unlikely scenario.
I'm Rubén. This is variable is static and the declaration is executed only once at the beginning of the execution. This line is not executed anymore so if its value is 0 it means that it overflowed and somehow a ridiculous amount of rigidbodies have been created

2023-05-18 19:49 UTC, solidajenjo commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
Used unordered because it's intended to have insert/deletes very often which is one of the use cases where it's recommended use unordered containers

2023-05-18 20:39 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +    assert(nextId != 0); //if this assert triggers, we have reached the maximum number of rigidbodies 2^32 - 1. This is a very unlikely scenario.
I just realized I was reading it the other way around, thinking the assert would be triggered if the condition was met, that's why I said I thought it needed to check `== 0`. Sorry for the confusion and thank you for answering!

2023-05-18 20:40 UTC, gerard-queralt commented on Source/Modules/ModulePhysics.h
> +	std::unordered_set<uint64_t> collisions;
Thank you for explaining it Rubén!

2023-05-19 07:13 UTC, diegusmejia117 approved these changes
Well done! Need to work on attack animation state, but it can be done after the merge.

2023-05-19 08:25 UTC, markmeliaa commented on Game/Scripts/SeekBehaviourScript.cpp
> +	ComponentTransform* ownerTransform = static_cast<ComponentTransform*>(owner->GetComponent(ComponentType::TRANSFORM));
Is this `ownerTransform` used anywhere?

2023-05-19 11:56 UTC, merged