Triggers created
Horizons-Games/Axolotl-Engine pull request #414
Opened 2023-05-23 09:44 UTC by Dedado3000

Now you can create a Ghost objects that triggers the on collision enter / exit of the scripts of the 2 objects

2023-05-23 09:46 UTC, Dedado3000 commented
The develop update was for having a real scene where I can test big scenarys

2023-05-27 12:46 UTC, OriolSors requested changes

2023-05-27 12:46 UTC, OriolSors commented on Source/DataModels/Components/ComponentRigidBody.cpp
> -	// delegate to notify other components
We need that for the ComponentBreakable

2023-05-27 12:46 UTC, OriolSors commented on Source/Modules/ModulePhysics.cpp
> +						other->OnCollisionEnter(rb);
With the other revert we doesn't need that

2023-05-27 15:54 UTC, OriolSors approved these changes

2023-05-27 15:56 UTC, AlexisDieu approved these changes

2023-05-27 15:57 UTC, merged