Refactor [Game play]: new mobility script using bullet
Horizons-Games/Axolotl-Engine pull request #419
Opened 2023-05-25 22:12 UTC by DADSILVER

- Old mobility scripts are deleted.
- The mobility scrips are divided into 3: Move, rotation, and jump.
- The mobility script also contains the dash. Because you need the direction to know where to dash to.
- A new camera script has been added. With it, you can move the camera vertically.
- A new scene is created to test gameplay.
- The other scenes are updated with the news scripts.

2023-05-26 10:20 UTC, gerard-queralt commented on Source/Modules/ModuleInput.cpp
> +				if (keysState[sdlEvent.key.keysym.scancode] != KeyState::REPEAT)
I'm not sure this is going to work, even if it should in theory. If I recall correctly, when a key is held, SDL emits alternate SDL_KEYDOWN/UP signals. What we should do to detect such cases is use the `repeat` flag in the SDL event. All of this to say, take a look at #408, it should fix this.

2023-05-26 10:20 UTC, gerard-queralt commented on Game/Scripts/PlayerJumpScript.cpp
> +	REGISTER_FIELD_WITH_ACCESSORS(JumpParameter, float);
A suggestion from the scripting side, since you don't seem to be using the accessor methods for anything, you can use
```suggestion
	REGISTER_FIELD(jumpParameter, float);
```
And get rid of them entirely. This macro is intended to allow the game team to add additional logic when getting and setting a given field. For example, if one of the members of the class is computed from another, similar to what you're doing in `Start`.

2023-05-26 11:49 UTC, markmeliaa requested changes
Good job to both of you! Left just one small change regarding the name of a script. Also, one question out of curiosity, why did you decide to call the `Move()`, `Rotate()`... functions from the `PreUpdate()` instead of from the `Update()`? I'm not seeing it as a bad thing, just to know why the decision of doing so.

2023-05-26 11:49 UTC, markmeliaa commented on Game/Scripts/PLAYERROTATIONSCRIPT.CPP
Could you change the name of this script to PlayerRotationScript.cpp, please?

2023-05-26 11:49 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.cpp
> +float PlayerMoveScript::GetSpeed() const
The good thing about what Gerard said is that, when using `REGISTER_FIELD` instead of `REGISTER_FIELD_WITH_ACCESSORS` is that all these getters and setters will not be needed because the MACRO will manage them for us, so only use the `REGISTER_FIELD_WITH_ACCESSORS` only if you have to give some extra logic to any getter or setter.

2023-05-26 13:47 UTC, DADSILVER commented on Game/Scripts/PlayerJumpScript.cpp
> +	REGISTER_FIELD_WITH_ACCESSORS(JumpParameter, float);
Fixed :)

2023-05-26 13:48 UTC, DADSILVER commented on Game/Scripts/PlayerMoveScript.cpp
> +float PlayerMoveScript::GetSpeed() const
Fixed

2023-05-26 14:13 UTC, DADSILVER commented on Source/Modules/ModuleInput.cpp
> +				if (keysState[sdlEvent.key.keysym.scancode] != KeyState::REPEAT)
Okay, I undo the changes.

2023-05-27 08:44 UTC, markmeliaa submitted a review, later dismissed

2023-05-27 08:51 UTC, Dedado3000 submitted a review, later dismissed

2023-05-27 09:17 UTC, markmeliaa approved these changes

2023-05-27 15:52 UTC, PaablooCH approved these changes

2023-05-27 15:59 UTC, merged