chore: update platform trigger
Horizons-Games/Axolotl-Engine pull request #469
Opened 2023-06-05 18:44 UTC by Vlukkee

Update Platform triggers to do certain damage over time.
Add a float to the trigger to change the damage on the trigger options.

2023-06-05 18:54 UTC, MarcGonzalezMoratona commented on Game/Scripts/HealthSystem.cpp
> +float HealthSystem::GetCurrentLife() const
```suggestion
float HealthSystem::GetCurrentHealth() const
```

2023-06-05 18:54 UTC, MarcGonzalezMoratona commented on Game/Scripts/HealthSystem.h
> +	float GetCurrentLife() const;
```suggestion
	float GetCurrentHealth() const; 
```

2023-06-05 18:54 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +			ENGINE_LOG("Taking damage %f --- Player Current Life %f", damageTaken, playerHealthSystem->GetCurrentLife());
```suggestion
			ENGINE_LOG("Taking damage %f --- Player Current Health %f", damageTaken, playerHealthSystem->GetCurrentHealth());
```

2023-06-05 18:59 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +	if(onTriggerState != false)
onTriggerState is a boolean?
Why aren't we just checking `if(onTriggerState)` or `ìf(!onTriggerState)`? It should do the same if the field is a boolean and it is more readable.

This also applies to other conditions of this file where we do `if(isWhateverTrigger == true)` , that can be refactored to `if(isWhateverTrigger)`

```suggestion
	if (onTriggerState)
```

2023-06-05 19:17 UTC, Dedado3000 commented on Game/Scripts/UITrigger.cpp
> +			ENGINE_LOG("Taking damage %f --- Player Current Life %f", damageTaken, playerHealthSystem->GetCurrentLife());
why will a console log enter into develop? please erase it

2023-06-05 19:17 UTC, Dedado3000 requested changes
Can we change the name of the script?, why is called UITrigger

2023-06-05 20:53 UTC, MarcGonzalezMoratona commented on Game/Scripts/HealthSystem.cpp
> +float HealthSystem::GetCurrenHealth() const
```suggestion
float HealthSystem::GetCurrentHealth() const
```

2023-06-06 05:15 UTC, Vlukkee commented on Game/Scripts/UITrigger.cpp
> +			ENGINE_LOG("Taking damage %f --- Player Current Life %f", damageTaken, playerHealthSystem->GetCurrentLife());
Done!

2023-06-06 05:15 UTC, Vlukkee commented on Game/Scripts/UITrigger.cpp
>  		if (isLoseByDamage == true)
Done!

2023-06-06 05:15 UTC, Vlukkee commented on Game/Scripts/UITrigger.cpp
> +	if(onTriggerState != false)
Done!

2023-06-06 05:17 UTC, Vlukkee commented on Game/Scripts/HealthSystem.h
> +	float GetCurrentLife() const;
Nice! i dont saw it and its correlative with the all script. ty!

2023-06-06 05:18 UTC, Vlukkee commented on Game/Scripts/UITrigger.cpp
> +			playerHealthSystem->TakeDamage(damageTaken);
Done!

2023-06-06 05:18 UTC, Vlukkee commented on Game/Scripts/HealthSystem.cpp
> +float HealthSystem::GetCurrenHealth() const
Done!

2023-06-15 17:14 UTC, Dedado3000 submitted a review, later dismissed

2023-06-16 13:11 UTC, Dedado3000 submitted a review, later dismissed

2023-06-16 14:01 UTC, Dedado3000 approved these changes

2023-06-16 18:52 UTC, diegusmejia117 approved these changes

2023-06-16 19:47 UTC, merged