Art Cantina WIP
Horizons-Games/Axolotl-Engine pull request #498
Opened 2023-06-15 18:28 UTC by diegusmejia117

This PR adds new props and art to the cantina section of the scene.

Added:

Floors, 
Ceiling pipelines, 
subfloor pipelines, 
new dance floor, 
turbines, 
VIP ceilings,
bootles,
More NPCs
and their respective colliders(dance floor colliders have a werid bug)

2023-06-15 18:42 UTC, Dedado3000 requested changes
Can you please delete unused scenes from level1

2023-06-15 18:42 UTC, Dedado3000 commented on Source/DataModels/Batch/GeometryBatch.cpp
> +				return;
please, undo this, was a missclick.

2023-06-15 19:22 UTC, diegusmejia117 commented on Source/DataModels/Batch/GeometryBatch.cpp
> +				return;
just checked the code it is written correctly no missclick(maybe bug)?

2023-06-15 22:28 UTC, gerard-queralt commented on Source/DataModels/Batch/GeometryBatch.cpp
> +				return;
This difference indicates that you added an extra space after the return, which you probably did by mistake. I imagine you didn't notice any difference because it's a space :P

2023-06-16 18:41 UTC, diegusmejia117 commented on Source/DataModels/Batch/GeometryBatch.cpp
> +				return;
Done

2023-06-16 18:51 UTC, Dedado3000 approved these changes

2023-06-16 19:47 UTC, ericdacal approved these changes

2023-06-16 19:47 UTC, merged