refactor/chore: address compilation warnings
Horizons-Games/Axolotl-Engine pull request #505
Opened 2023-06-18 23:14 UTC by gerard-queralt

Tried to avoid changing types as much as possible and use casts instead, but as far as I know it's better to avoid using `unsigned int`, since its size may vary between architechtures and operative systems, and instead use fixed size types, like `size_t` or `uintX_t`.

2023-06-22 11:55 UTC, markmeliaa approved these changes
Amazing work, does this clean all the warnings that we had in the engine?

2023-06-22 11:55 UTC, markmeliaa commented on Source/DataModels/Resources/EditorResource/EditorResource.h
> +#pragma warning(push)
What does pragma warning push/pop?

2023-06-22 13:58 UTC, gerard-queralt commented
> Amazing work, does this clean all the warnings that we had in the engine?

Thank you very much! Not _all_ of them, only the compilation ones, which as you can see in the changes were mostly about unchecked size changes. If we run a code analysis we'll still have some, like usage of C-style casts, for instance.

2023-06-22 14:02 UTC, gerard-queralt commented on Source/DataModels/Resources/EditorResource/EditorResource.h
> +#pragma warning(push)
"Push" will store the current state of warning configuration, and "pop" will restore it. This way, the warnings disabled in between these two directives will only remain disabled for this file, which in most cases it's what we want in order to decide on a case-by-case basis.
Windows documentation: https://learn.microsoft.com/en-us/cpp/preprocessor/warning?view=msvc-170

2023-06-22 23:28 UTC, Dedado3000 submitted a review, later dismissed
All chances semestre ok.

2023-06-23 00:40 UTC, PaablooCH requested changes
Hi, all seem good, just 2 things:

2023-06-23 00:40 UTC, PaablooCH commented on Source/DataStructures/Quadtree.cpp
> +		childrenRemovedObject = frontLeftNode->Remove(gameObject) || childrenRemovedObject;
You can use |= and remove the last part

2023-06-23 00:40 UTC, PaablooCH commented on Source/DataStructures/Quadtree.cpp
> +		childrenRemovedObject = frontLeftNode->Remove(gameObject) || childrenRemovedObject;
Or even merge all into one sentence

2023-06-23 07:20 UTC, gerard-queralt commented on Source/DataStructures/Quadtree.cpp
> +		childrenRemovedObject = frontLeftNode->Remove(gameObject) || childrenRemovedObject;
What I'm not sure about is if lazy evaluation would prevent the expression from being executed, that's why I wrote it in this "clunky" way. I'll check if there'd be any issues and get back to you.

2023-06-23 08:23 UTC, gerard-queralt commented on Source/DataStructures/Quadtree.cpp
> +		childrenRemovedObject = frontLeftNode->Remove(gameObject) || childrenRemovedObject;
I was right that short-circuit evaluation (forgot C++ doesn't have lazy evaluation) would prevent the methods from being executed if a previous one returned true. However, this won't happen using bitwise OR (`|`), which also means that your first suggestion of using `|=` was correct since it's a short-hand for the same operator. If you don't mind, I'll go with that approach because I feel like using `|` might be confusing and lead to thinking it's a mistake.

2023-06-23 08:44 UTC, PaablooCH approved these changes

2023-06-23 08:48 UTC, markmeliaa approved these changes

2023-06-23 09:29 UTC, markmeliaa commented on Source/DataModels/Resources/EditorResource/EditorResource.h
> +#pragma warning(push)
Gotcha, thanks!

2023-06-23 09:45 UTC, merged