chore: update/improve the structure of the scripts so they are more intuitive
Horizons-Games/Axolotl-Engine pull request #507
Opened 2023-06-19 13:57 UTC by markmeliaa

The scripts were quite a mess and there was some functionality that got mixed and other functionality that could be separated into a different script, so that's what this is about.

Bix now has:
- `PlayerManagerScript` to manage her stats and any other functionalities in the future.
- `InteractWithPowerUpScript` to manage the interactions between her and the powerups.
- `PlayerDeathManager` to manage everything related to her death, what should happen when her life hits 0 (this was inside the `HealthSystem` script, which made that script a bit confusing.

The drones (and any future other enemies) now have:
- `EnemyDeathScript`, same as the script that manages Bix death, functionality that was inside the `HealthSystem` script that was divided into another script. This script also manages the request of a powerup that an enemy could drop after its death.

The powerups now have:
- `PowerUpLogicScript`, practically the same as the previous script (`PowerUpScript`) but with a more intuitive name and some code logic changed.

And a new script `PowerUpsManagerScript` that will act as the manager of the powerups in the current scene (just set this script in an empty gameobject and that's all, it does not need to be attached to any GameObject in particular)

2023-06-20 23:38 UTC, DADSILVER approved these changes
Good job, Only one thing.

2023-06-20 23:38 UTC, DADSILVER commented on Game/Scripts/PowerUpsManagerScript.cpp
> +void PowerUpsManagerScript::EliminateCurrentPowerUpEffect()
In this func activePowerUp is set to NONE in the init so don't go to enter in the others ifs.

2023-06-21 11:34 UTC, markmeliaa commented on Game/Scripts/PowerUpsManagerScript.cpp
> +void PowerUpsManagerScript::EliminateCurrentPowerUpEffect()
Good catch, thanks!

2023-06-21 15:09 UTC, PaablooCH requested changes
👍, few things:

2023-06-21 15:21 UTC, markmeliaa commented on Game/Scripts/PlayerDeathScript.cpp
> +	if (loseSceneName != "" && !componentAnimation->isPlaying() && componentAnimation->GetActualStateName() == "Death")
Not related to this pr

2023-06-21 15:22 UTC, markmeliaa commented on Game/Scripts/BixAttackScript.cpp
> +			if (hit.gameObject->GetRootGO() && hit.gameObject->GetRootGO()->CompareTag("Enemy"))
I think that's not related to this pr, but what do you mean?

2023-06-21 17:59 UTC, merged