feat: improve the force powers
Horizons-Games/Axolotl-Engine pull request #515
Opened 2023-06-21 21:16 UTC by DADSILVER

- Added an example of the attack to Bix.
- Added force attack script.
- Set stun time to enemies (maybe need to be changed to new enemyManager).
-When an enemy is on the range, press Q to push them.

2023-06-22 11:52 UTC, markmeliaa reviewed
I'll try the functionality in today's class, but overall, the code looks good, nice job!

2023-06-22 11:52 UTC, markmeliaa commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	if (input->GetKey(SDL_SCANCODE_Q) != KeyState::IDLE && currentCoolDown <= 0)
Could you add all the logic of the force attack into a separate function so we have all the code regarding to the attack encapsulated?

2023-06-22 11:52 UTC, markmeliaa commented on Game/Scripts/PlayerForceAttackScript.cpp
> +			enemyRigidBody->DisablePositionController();
Here you are disabling the position and the rotation controller of the rigidbody, but you are never enabling it again, is that what you intended?

2023-06-22 17:39 UTC, UriMurcia reviewed
Nice work! Will try to test it when I can, but good code!

2023-06-22 17:39 UTC, UriMurcia commented on Game/Scripts/EnemyDroneScript.cpp
> +			if (timeStunnedAux < 0)
What is timeStunnedAux used for?

2023-06-22 17:39 UTC, UriMurcia commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	const ComponentTransform* parentTransform =
This should be saved as a member variable and do it once at the start, GetComponent function is costly and should be avoided in the update

2023-06-22 17:39 UTC, UriMurcia commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	const ComponentTransform* transform =
same for this, in this case it's not in the update, but it's repeated every time we push enemies, if it can be avoided better :)

2023-06-22 17:39 UTC, UriMurcia commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	for (std::vector<GameObject*>::iterator it = enemiesInTheArea.begin(); it == enemiesInTheArea.end(); it++)
Maybe try
```c++
enemiesInTheArea.erase(std::remove_if(
	std::begin(enemiesInTheArea),
	std::end(enemiesInTheArea),
	[other](const GameObject* gameObject)
	{
		return gameObject == other->GetOwner();
	}),
	std::end(enemiesInTheArea));
```

Link: https://en.cppreference.com/w/cpp/algorithm/remove

2023-06-22 18:27 UTC, markmeliaa approved these changes

2023-06-22 20:55 UTC, PaablooCH requested changes
some questions

2023-06-22 20:55 UTC, PaablooCH commented on Game/Scripts/EnemyDroneScript.cpp
> +			return;
why this return? you don't want to execute the rest?

2023-06-22 20:55 UTC, PaablooCH commented on Game/Scripts/EnemyDroneScript.cpp
> +	timeStunnedAux = std::min(0.5f, newTime);
which is the purpose of this variable? i don't see it anymore

2023-06-22 20:55 UTC, PaablooCH commented on Game/Scripts/PlayerForceAttackScript.cpp
> +		enemyHealthScript->TakeDamage(10.0f);
if this value is gonna repeat it we can put it in a define for example

2023-06-22 21:34 UTC, DADSILVER commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	const ComponentTransform* parentTransform =
Done.

2023-06-22 21:39 UTC, DADSILVER commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	const ComponentTransform* transform =
In this case, I think we can keep it. because we can pass a level without using this ability . With this, I want to say that I would love the player to use this ability every time that he has it, but he can avoid to uses.

2023-06-22 22:05 UTC, DADSILVER commented on Game/Scripts/PlayerForceAttackScript.cpp
> +	for (std::vector<GameObject*>::iterator it = enemiesInTheArea.begin(); it == enemiesInTheArea.end(); it++)
Sure, I will put this. But I think it may have the same complexity as the for.

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/14923700/3ef23257-5326-43ef-b872-cf25d82c5160)

2023-06-22 22:07 UTC, DADSILVER commented on Game/Scripts/EnemyDroneScript.cpp
> +			return;
no

2023-06-22 22:09 UTC, DADSILVER commented on Game/Scripts/EnemyDroneScript.cpp
> +	timeStunnedAux = std::min(0.5f, newTime);
deleted :)

2023-06-22 22:11 UTC, DADSILVER commented on Game/Scripts/PlayerForceAttackScript.cpp
> +		enemyHealthScript->TakeDamage(10.0f);
Changed, now is a register field.

2023-06-23 00:21 UTC, PaablooCH approved these changes
Pana 👍

2023-06-23 09:28 UTC, merged