feat: Player camera and movement changed
Horizons-Games/Axolotl-Engine pull request #522
Opened 2023-06-23 19:13 UTC by OriolSors

- Player camera based on proportional controller
- Sample points for manage camera behaviour
- Player mobility adapted to camera space
- Unattached camera in Player hierarchy

2023-06-23 22:11 UTC, PaablooCH requested changes
i put the playerManagerScript and load the 1.1 but can't execute the game
![Imagen de WhatsApp 2023-06-24 a las 00 05 03](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/bf16ec70-2817-4d1d-92ea-a7449cc0b5ea)

2023-06-23 22:17 UTC, OriolSors commented
@PaablooCH put the PlayerManager (with 300 as speed value), save scene and load it again. Then you can play the level

2023-06-23 22:24 UTC, OriolSors commented
> @PaablooCH put the PlayerManager (with 300 as speed value), save scene and load it again. Then you can play the level

I updated it for make the life easier. Also, now there is only one sample point in the scene for testing reasons. When this will be agreed, approved and adapted for gameplay, I will start to add more.

2023-06-23 22:33 UTC, PaablooCH commented
okay, thx

2023-06-23 22:42 UTC, PaablooCH commented
this movement happens to you? i move in diagonal 

https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/2d7da6aa-2477-4fd9-9acb-42d4d0af6e85

2023-06-23 22:49 UTC, OriolSors commented
> this movement happens to you? i move in diagonal
> 
>  camara.mp4 
> the camera sample works fine :)

Can you try it in Release?

2023-06-23 23:15 UTC, PaablooCH commented
Release engine or Game?

2023-06-23 23:16 UTC, OriolSors commented
> Release engine or Game?

ReleaseEngine

2023-06-24 09:13 UTC, markmeliaa commented
So this only works on release now? Any idea why it's so wacky in debug?

2023-06-24 09:17 UTC, OriolSors commented
> So this only works on release now? Any idea why it's so wacky in debug?

It's because of framerate. The controller of the camera focus the player position instead of being "dragged" by him. So if the position of the player changes drastically between frames, the camera will get crazy.

2023-06-24 09:29 UTC, markmeliaa commented
Oh, understandable! Although this may hinder our future trials in debug due to the camera being slow, that's what we were asked to do, so I guess its fine (we can always improve the framerate in debug to fix that too). Let me check it's working correctly and I'll approve this pr real quick!

2023-06-24 09:41 UTC, markmeliaa reviewed
In level 1.1 everything works correctly, but in the gameplay scene the engine breaks when I try to move Bix after pressing play, is something missing in that scene? What should we add to make it work correctly?

2023-06-24 09:47 UTC, OriolSors commented
> In level 1.1 everything works correctly, but in the gameplay scene the engine breaks when I try to move Bix after pressing play, is something missing in that scene? What should we add to make it work correctly?

I put the basic init conditions for the scene! Try it now! I will update the description of the PR with the steps needed, sorry!

2023-06-24 09:58 UTC, OriolSors commented
> Oh, understandable! Although this may hinder our future trials in debug due to the camera being slow, that's what we were asked to do, so I guess its fine (we can always improve the framerate in debug to fix that too). Let me check it's working correctly and I'll approve this pr real quick!

Yess, in fact with few assets, and a very simple scene we will be able to test it correctly. The problem is when we get 4 FPS, that won't allow us to test anything, not only by the camera

2023-06-24 16:12 UTC, DADSILVER approved these changes
Awesome job, only I think When I try to pass the park out the camera don let us see where is the next jump. I don't know if you can fix it or is something that you have to discuss with level.

I have these 2 questions too.

2023-06-24 16:18 UTC, OriolSors commented
> Awesome job, only I think When I try to pass the park out the camera don let us see where is the next jump. I don't know if you can fix it or is something that you have to discuss with level.
> 
> I have these 2 questions too.

Well, actually there are some sample points missing. I added a few of them only for testing, now that all will be approved I will start adding more, and then Level Team will bring them to the new version of the scene

2023-06-24 16:25 UTC, OriolSors commented on Game/Scripts/PlayerMoveScript.cpp
>  		movement = btVector3(totalDirection.x, totalDirection.y, totalDirection.z) * deltaTime * newSpeed;
Actually I'm currently working on that (some troubles appear). This function takes de totalDirection as the final target for the transform global forward, but as we are using only discrete directions with WASD, it seems not as soft as if we use a joystick. For avoiding that, we will need to use, maybe the SetPositionTarget (and I tried and it works, but sometimes depending of framerate, the collisions are not managed well; similar to the force problem), or interpolating the rotation with a proportional controller for the transform rotation. This is the approach I'm following but there are few difficulties

2023-06-24 16:26 UTC, OriolSors commented on Game/Scripts/CameraSample.cpp
> +	position = transform->GetGlobalPosition();
Yess, makes sense. In the start there were a lot of different parameters while trying to adjust the sample structure, and finally I left as this. I will make a rework on that

2023-06-24 16:39 UTC, PaablooCH approved these changes

2023-06-24 16:53 UTC, markmeliaa approved these changes
Everything perfect Oriol, amazing work!

2023-06-24 17:22 UTC, merged