feat[Graphics]: Lights updated when parent moved
Horizons-Games/Axolotl-Engine pull request #526
Opened 2023-06-24 19:53 UTC by MacXxs

* Now light inside gameObjects are Updated when their parents are moved
* Optimized light updates so now only the light being modified is updated instead of updating all the lights of the same type
* The same from the previous point but applied to the rendering and the updating of the ssbo of the light type
* Lights being cached so the access to them is faster

2023-06-24 22:39 UTC, gerard-queralt reviewed
Left some questions, if you don't mind my meddling.

2023-06-24 22:39 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.h
> +	void RenderAreaSpheres() const;
I feel like all of these rendering methods should go in ModuleRender rather than directly on Scene.

2023-06-24 22:39 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.h
> +	std::vector<std::pair<const ComponentPointLight*, unsigned int>> cachedPoints;
Might be a dumb question, but could we add this information to the respective structs? If so, we would avoid having twice the amount of vectors.

2023-06-24 22:39 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.cpp
> +	bool found = false;
Instead of having this boolean, could we not just return from the method once we found and process the light? Same for all of the other ones.

2023-06-24 22:39 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.cpp
> +				cachedPoints.push_back(std::make_pair(pointLightComp, pos));
Is this `pos` variable necessary? Couldn't we not do
```suggestion
				cachedPoints.push_back(std::make_pair(pointLightComp, cachedPoints.size()));
```
Same for the other loops.

2023-06-25 10:11 UTC, MacXxs commented on Source/DataModels/Scene/Scene.h
> +	std::vector<std::pair<const ComponentPointLight*, unsigned int>> cachedPoints;
No it can't be done, that's why it's in a separate vector. If you test it, you will see that it will break the lights because the information in those structs needs to be the same as the structs in the shaders, they contain just the necessarary information for the shaders to render the lights.

2023-06-25 10:15 UTC, MacXxs commented on Source/DataModels/Scene/Scene.cpp
> +	bool found = false;
Yeah we could, but it's a short function, ones it founds the light to process the next iteration will end the function so there's not a big improvement in performance, and for readability it's fine as it is.

2023-06-25 10:21 UTC, MacXxs commented on Source/DataModels/Scene/Scene.cpp
> +				cachedPoints.push_back(std::make_pair(pointLightComp, pos));
Yeah we could to do it. Actually, it would be cachedPoints.size() - 1, but i prefer having it in a separate variable. I find it more clear for it's purpose and readability, and the complexity is the same as doing a size().

2023-06-25 10:29 UTC, AlexisDieu commented
Changing from spot to point light or other way make the engine crash : 
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/73070531/4cfc29db-a48d-44a6-899f-ca2bcd1e3acf)
Else the rest seems working correctly !

2023-06-25 10:30 UTC, MacXxs commented on Source/DataModels/Scene/Scene.h
> +	void RenderAreaSpheres() const;
They are fine in the Scene class with all the information with the lights to render, actually if i recall correctly Carlos told us that ModuleRender shoudln't have all the functions realated to rendering, just do the calls to them, so actually the ModuleRender should just call the rendering functions for the objects to render. And in the case of the lights, for optimization purposes, its rendering (modification of info in the ssbo of the lights) is only done when a value has been modified and updated, so the the call for the rendering isn't done in ModuleRender every frame, but only when a modification has been detected in its transform (so the ComponentLight directly updates the light and the render) or during a modification on the values of the light (so the window calls for the update of the light and it's render).

2023-06-25 10:37 UTC, AlexisDieu approved these changes
The bug is in develop so nevermind need another PR for this.

2023-06-25 10:38 UTC, MacXxs commented
> Changing from spot to point light or other way make the engine crash : ![image](https://user-images.githubusercontent.com/73070531/248547949-4cfc29db-a48d-44a6-899f-ca2bcd1e3acf.png) Else the rest seems working correctly !

This is happening also in develop, it seems that again for the fourth or fifth time someone broke changing from one light to another....

2023-06-25 11:04 UTC, MacXxs commented
> > Changing from spot to point light or other way make the engine crash : ![image](https://user-images.githubusercontent.com/73070531/248547949-4cfc29db-a48d-44a6-899f-ca2bcd1e3acf.png) Else the rest seems working correctly !
> 
> This is happening also in develop, it seems that again for the fourth or fifth time someone broke changing from one light to another.... We'll have to fix it again in a separate PR

Don't mind me, already fixed it, gonna upload the change in this PR

2023-06-25 12:01 UTC, AlexisDieu approved these changes

2023-06-25 15:56 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.h
> +	void RenderAreaSpheres() const;
Even if it's not in Module Render, I feel like Scene is getting too bloated. Ideally, it should just represent a Scene in the engine, and have much less logic, at least in my opinion. Maybe we should consider a new module for all of this logic, even if it's in a different MR?

2023-06-25 16:00 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
Is this change part of the fix? I could've sworn the components vector should never have null values, and if that's the case, we can save ourselves a check.

2023-06-25 16:07 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
Also, I don't think this is right, because now the lambda might not return any value. If we need to check for nullity, we could either add a return after the if block or add a filter view before the transform one.

2023-06-25 16:12 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
> Is this change part of the fix?

Nevermind, I've just seen the other changes in the commit are basically aesthetic. Still, I don't know how there can be null pointers in that vector :/

2023-06-25 16:22 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
Just repo'd locally. I imagine it's because this call is performed during the destruction of the light object, so the vector hasn't been cleared yet. Would you mind if I updated the code to have the lambda return something? It'd be just integrating the condition into the return statement.

2023-06-25 23:20 UTC, PaablooCH requested changes
Hi, here are somethings that i see, now i'm going to test it

EDIT: seems work fine

2023-06-25 23:20 UTC, PaablooCH commented on Source/DataModels/Scene/Scene.cpp
> +					cachedSpheres.push_back(std::make_pair(areaLightComp, posSpheres));
why you keep this function if you created the other two that do the same?

2023-06-25 23:20 UTC, PaablooCH commented on Source/DataModels/Windows/EditorWindows/WindowScene.cpp
> +#include "Components/ComponentAreaLight.h"
unused

2023-06-25 23:36 UTC, PaablooCH commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
> I imagine it's because this call is performed during the destruction of the light object, so the vector hasn't been cleared yet

yep, is for this reason that it crash

2023-06-26 06:36 UTC, MacXxs commented on Source/DataModels/Scene/Scene.cpp
> +					cachedSpheres.push_back(std::make_pair(areaLightComp, posSpheres));
Because during initalization its called, and it saves us to go through the vector of objects in scene two times

2023-06-26 06:38 UTC, MacXxs commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
Yes this is because of the bug that crashes the engine when changing the light type, for example from point to spot

2023-06-26 06:47 UTC, MacXxs commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
> Just repo'd locally. I imagine it's because this call is performed during the destruction of the light object, so the vector hasn't been cleared yet. Would you mind if I updated the code to have the lambda return something? It'd be just integrating the condition into the return statement.

Yeah, as long as the lights keep working and you can switch between them its fine by me

2023-06-26 07:07 UTC, MacXxs commented on Source/DataModels/GameObject/GameObject.inl
> +									  if (comp)
Did a commit putting the null check inside the return of the lambdas, if you wanted something else go ahead

2023-06-26 07:39 UTC, AlexisDieu approved these changes

2023-06-26 09:56 UTC, PaablooCH approved these changes

2023-06-26 10:11 UTC, merged