feat: Debug Features
Horizons-Games/Axolotl-Engine pull request #532
Opened 2023-06-26 15:16 UTC by diegusmejia117

Added:
Gameplay Debug Features

-Acrtivate God Camera + paralize player ( Number 4)
-Full Health (Number 7)
-Immortality (Number 8)
-One Attack Death (Number 9)
-Teleporting (Number 0)

2023-06-26 22:41 UTC, markmeliaa requested changes
outdated

2023-06-27 10:06 UTC, markmeliaa requested changes

2023-06-27 10:06 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.h
> +	bool GetIsParalized();
```suggestion
	bool GetIsParalized() const;
```

2023-06-27 10:06 UTC, markmeliaa commented on Game/Scripts/PlayerRotationScript.cpp
> +bool PlayerRotationScript::GetCanRotate()
```suggestion
bool PlayerRotationScript::GetCanRotate() const
```

2023-06-27 10:06 UTC, markmeliaa commented on Source/Modules/ModuleCamera.cpp
> +		/*else if (input->GetKey(SDL_SCANCODE_3) == KeyState::DOWN)
Is this fragment of code going to be unused now that we have debug features? If so, you could delete it instead of comenting.

2023-06-27 10:09 UTC, markmeliaa commented
Also, if you could fix the conflicts that this pr has, that would be fine. Remember to keep your branch periodically updated with the branch you will be finally merging into (in this case `game-programming`), so you'll avoid big conflicts like this ones.

2023-06-27 10:13 UTC, diegusmejia117 commented on Source/Modules/ModuleCamera.cpp
> +		/*else if (input->GetKey(SDL_SCANCODE_3) == KeyState::DOWN)
this one in particular is original to David's code, so i don't know if its needed or will be needed.

2023-06-27 10:14 UTC, gerard-queralt commented on Game/Scripts/BixAttackScript.cpp
> +								    healthScript->TakeDamage(deathTouchedDamage);
> Also if you could fix the indentation of that if and else, I'd be grateful

Chiming in to remind you you can use `Ctrl+K`, `Ctrl+D` to automatically fix formatting in the file :)

2023-06-27 10:47 UTC, diegusmejia117 commented on Game/Scripts/DebugGame.cpp
> +	if(!playerOnLocation)
In this case we need the this if here because its the one that sets bix movement to normal after reaching a debug point, for this to happen it should be constantly searching when bix gets to that point.

2023-06-27 12:01 UTC, PaablooCH commented on Game/Scripts/BixAttackScript.h
> +	float deathTouchedDamage;
Variable not used

2023-06-27 12:08 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +	REGISTER_FIELD(setPlayer, GameObject*);
You can a void this and get the player in the start using App->getmodule<modulePlayer>, or smthing like that

2023-06-27 12:09 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +	isDebugModeActive = false;
Move it to constructor

2023-06-27 12:10 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +DebugGame::DebugGame() : Script()
Initialize all the variables here

2023-06-27 12:11 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +	playerOnLocation = false;
Move it to constructor

2023-06-27 12:12 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +	ModuleInput* input = App->GetModule<ModuleInput>();
Module input never changes, so it's better if you get it only once in the start ()

2023-06-27 12:13 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +	//TELEPORTMOV
What means mov?

2023-06-27 12:15 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +void DebugGame::ActivateDebugMode()
Here we not only activate debugMode we also deactivate it, i suggest
```suggestion
void DebugGame::SwitchDebugMode()
```

2023-06-27 12:17 UTC, PaablooCH commented on Game/Scripts/DebugGame.cpp
> +void DebugGame::BeImmortal()
Change the name as before suggested

2023-06-27 12:22 UTC, PaablooCH commented on Game/Scripts/HealthSystem.cpp
> +	if (currentHealth <= 0 && !isImmortal)
If its immortal she can take dammage so her life can be lower 0 during that state

2023-06-27 12:24 UTC, PaablooCH commented on Game/Scripts/PlayerJumpScript.cpp
> +	canJump = true;
To constructor

2023-06-27 12:24 UTC, PaablooCH commented on Game/Scripts/PlayerMoveScript.cpp
> +	isParalized = false;
To constructor

2023-06-27 12:26 UTC, PaablooCH commented on Game/Scripts/PlayerRotationScript.cpp
> +	canRotate = true;
Constructor

2023-06-27 12:27 UTC, PaablooCH commented on Game/Scripts/PlayerRotationScript.h
> +	bool canRotate;
Idk why we have 2 privates but move the variable in the second

2023-06-27 21:52 UTC, markmeliaa approved these changes

2023-06-27 21:59 UTC, PaablooCH approved these changes

2023-06-27 22:01 UTC, merged