Scripting/qol
Horizons-Games/Axolotl-Engine pull request #558
Opened 2023-06-28 19:58 UTC by Piterga12

Implemented the vectors and it's serialization in scripting:
-Vector Float
-Vector String
-Vector Bool
-Vector GO
-Vector Float3
(the vector can have as many components as the user defines on the script)
(there is an example in DefaultScript)

2023-06-28 22:24 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentScript.cpp
> +					vectorElementsWithName[i]["innerType"] = 0;
I don't think this `innerType` needs to be saved for each of the elements of the vector, we can probably just do:
```c++
vectorElements["innerType"] = 0;
```
But most importantly, I don't like that we're using integers directly here, since we already have an enum. I'd write it:
```c++
vectorElements["innerType"] = static_cast<int>(vectorField.innerType);
```
To be perfectly clear, what you did doesn't have any issues in terms of performance or robustness (any change in the order of the enum will still break it), but I think my suggestion makes it more readable, and you avoid having to check the value in the switch like you're doing.

2023-06-28 22:28 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
> +	if (ImGui::InputText(name.c_str(), value.data(), 24))
In all of these `DrawXXXField` methods (except GameObject), you are returning the value regardless, so we can probably just do
```c++
ImGui::InputText(name.c_str(), value.data(), 24);
return value;
```
Same for the others.

2023-06-28 22:29 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
> +	std::string DrawStringField(std::string value, const std::string name);
Remember to pass strings as const reference to avoid creating copies 😉 
```suggestion
	std::string DrawStringField(const std::string& value, const std::string& name);
```
Same for the others.

2023-06-28 22:30 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
> +	GameObject* DrawGOField(GameObject* value, const std::string name);
```suggestion
	GameObject* DrawGameObjectField(GameObject* value, const std::string name);
```
Don't be lazy :P

2023-06-30 11:22 UTC, markmeliaa requested changes
Can we have, in the ScriptComponent UI, a better display of vectors? Something like:
`random boolean from the script`
`random float from the script`
`vector name`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `vector value 1`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `vector value 2`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `vector value 3`
`anoter random bool`
This way we could visually diferentitate between when a value is on a vector and when a value is on its own.

(Haven't checked the code, this is just an idea that came after seeing the image in yesterday's class presentation)

2023-07-02 19:18 UTC, Piterga12 commented on Source/DataModels/Components/ComponentScript.cpp
> +					vectorElementsWithName[i]["innerType"] = 0;
Done!

2023-07-03 07:50 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
> +	math::float3 DrawFloat3Field(math::float3 value, const std::string& name);
Whoops, just realized that this float3 is passed by copy.
```suggestion
	math::float3 DrawFloat3Field(const math::float3& value, const std::string& name);
```
Sorry for not noticing before.

2023-07-03 18:47 UTC, Piterga12 commented
> Can we have, in the ScriptComponent UI, a better display of vectors? Something like: `some random boolean from the script` `some random float from the script` `vector name`        `vector value 1`        `vector value 2`        `vector value 3` `another random boolean from the script` This way we could visually diferentitate between when a value is on a vector and when a value is on its own.
> 
> (Haven't checked the code, this is just an idea that came after seeing the image in yesterday's class presentation)



> Can we have, in the ScriptComponent UI, a better display of vectors? Something like: `some random boolean from the script` `some random float from the script` `vector name`        `vector value 1`        `vector value 2`        `vector value 3` `another random boolean from the script` This way we could visually diferentitate between when a value is on a vector and when a value is on its own.
> 
> (Haven't checked the code, this is just an idea that came after seeing the image in yesterday's class presentation)

It should look like that now

2023-07-04 10:23 UTC, markmeliaa commented
> It should look like that now

Thanks! Could you add some kind if indentation (a TAB would be more that enough IMO) to every member of a vector, so each item of the vector is clearly differentiated from those elements that are not in a vector?

2023-07-05 16:49 UTC, Piterga12 commented
> > It should look like that now
> 
> Thanks! Could you add some kind if indentation (a `TAB` would be more that enough IMO) to every member of a vector, so each item of the vector is clearly differentiated from those elements that are not in a vector?

Done, now the value appears indented

2023-07-05 19:19 UTC, markmeliaa reviewed
Nice, thanks Peter! I'll try it tomorrow and if everything works you'll have my approve!

2023-07-06 12:38 UTC, markmeliaa approved these changes
Looks amazing now, thanks Peter!

2023-07-08 17:50 UTC, gerard-queralt approved these changes

2023-07-08 17:59 UTC, merged