feat : component line
Horizons-Games/Axolotl-Engine pull request #588
Opened 2023-07-14 16:39 UTC by AlexisDieu

- Add the componentLine 
- You can choose the End point (P1) by drag and drop any GameObject
- Add the AnimatedTexture script to be able to change his speed and see it while playing
- Use multiple parameters to it as the number of billboarding (that change the accuracy of it)
- Size at the begin and the end of the line
- Bezier with Imgui to modify the size

2023-07-15 01:31 UTC, PaablooCH requested changes
Good job 👍 
PS: Please review your content before creating the pr

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
clean the comments

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +#include <string>
unnecessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +		glBindVertexArray(lineVAO);
is this necessary?

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +	if (program != nullptr && childGameObject != nullptr)
the program check is not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
float4x4 has a function that returns a float pointer, do proj.ptr()

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +	meta["numTiles"] = (int) numTiles;
use static_cast<>

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +	numTiles = (int) meta["numTiles"];
use static_cast

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +															   (float) jsonColors[i]["color_y"],
this don't seem well indexed

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +#include "Program/Program.h"
use forward declaration

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +#include "Math/float3.h"
unnecessary they are already in StdAfx

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	int numTiles = 1;
declare it in the constructor

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	float time = 0;
same, put it in constructor

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	bool dirtyBuffers = true;
constructor

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	float4 sizeFadingPoints = float4::zero;
constructor....

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	this->speed = speeds;
`this` is not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	this->lineTexture = texture;
`this` is not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	this->sizeFading = range;
`this` is not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.h
> +	this->sizeFadingPoints = points;
`this` is not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.cpp
> +	ComponentWindow("Line", component),
use capital letters for LINE

2023-07-15 01:31 UTC, PaablooCH commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.h
> +	this->lineTexture = texture;
`this` is not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/Modules/ModuleRender.cpp
> +	//glPolygonMode(GL_FRONT_AND_BACK, GL_LINE); //See the billboard
clean comments if they are not necessary

2023-07-15 01:31 UTC, PaablooCH commented on Source/Modules/ModuleUI.cpp
is this ok?

2023-07-15 11:42 UTC, AlexisDieu commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
Yeah but then I need to include frustum just for it, it's maybe not a good thinks to include frustum just for that ?

2023-07-15 15:18 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
i do that in trails and i didn't need to add frustum.h

2023-07-15 15:36 UTC, AlexisDieu commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
Well in my case, I tried but frustum was not recognized, maybe in trails it's due to another include or idk but for me visual studio said no

2023-07-15 19:37 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
If I may interject, I think it's better to add the include in this case and use the built-in function of the lib. Should have little impact in compilation time since it's added to a source file, not a header. Furthermore, we could even add it to the pre-compiled headers, since we will never modify `Frustum.h`, and we could remove the include from most of the project. But that's a different topic :P

2023-07-16 10:46 UTC, PaablooCH commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
check if this compiles in your solution and if not we will have to solve it, because ptr is in `float4x4.h` not in `frustum.h`
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/9a5f14f6-c985-43c0-a688-aa13ab9f57f2)
PS: if i remember frustum is used in a few class i don't see it necessary. What i see is that someone uses `frustrum` as a name of variable/function.

2023-07-16 11:31 UTC, AlexisDieu commented on Source/DataModels/Components/ComponentLine.cpp
> +		program->BindUniformFloat4x4(0, reinterpret_cast<const float*>(&proj), true);
done

2023-07-16 11:55 UTC, xavi1111 approved these changes
I tested the basic functionallity of the component and all works. I tested the changes to the approach ot the line end and work wonderful nice work.

2023-07-16 13:17 UTC, PaablooCH approved these changes

2023-07-16 13:31 UTC, merged