Scripting/fix scripting debug
Horizons-Games/Axolotl-Engine pull request #614
Opened 2023-07-30 09:54 UTC by ericdacal

Now the scripts work again

2023-07-30 12:13 UTC, gerard-queralt commented on Game/Scripts/ActivationLogic.cpp
> +	catch(const ComponentNotFoundException){
From what I gathered, the C++ standard is to catch by reference. Please change this catch clause and the one in line 80.
```suggestion
	catch(const ComponentNotFoundException&){
```

2023-07-30 12:13 UTC, gerard-queralt commented on Game/Scripts/TriggerSewersMusic.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
Should this have a log? If I'm reading it correctly, this was just a check, and we're not storing the `ComponentPlayer` anywhere. I guess the question is: is this something unexpected that should not happen? Same goes for the other instances where this check (`GetComponent<ComponentPlayer>() != nullptr`) was previously performed.

2023-07-30 14:50 UTC, DADSILVER submitted a review, later dismissed
Thx a lot for this PR. Only 1 question and 1 thing. Should the assets be added to the PR?

The other thing is that we should use GetTag instead of get component if possible. GetComponente is most costly than GetTag.

2023-07-30 14:50 UTC, DADSILVER commented on Game/Scripts/TriggerSewersMusic.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
This should be GetTag() == "Player" as the others.

2023-07-30 14:50 UTC, DADSILVER commented on Game/Scripts/TriggerSewersMusicExit.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
This should be GetTag() == "Player" as the others.

2023-07-30 14:50 UTC, DADSILVER commented on Game/Scripts/UIMissionTrigger.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
This should be GetTag() == "Player" as the others.

2023-07-30 14:50 UTC, DADSILVER commented on Game/Scripts/UITrigger.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
This should be GetTag() == "Player" as the others.

2023-07-30 14:50 UTC, DADSILVER commented on Game/Scripts/UITrigger.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
This should be GetTag() == "Player" as the others.

2023-07-31 10:43 UTC, markmeliaa requested changes
Good job Eric, thanks for fixing this., just a couple things.

If you did not change any model or any texture, the assets modified should not be uploaded, so if you could delete those, that would be nice!

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +		try {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +			componentRigidBody = child->GetComponent<ComponentRigidBody>();
Before, when a `ComponentRigidBody` was found, there was a `break`, should it be added here as well?

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/CantinaNPCAnimationManager.cpp
> +	try {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/CantinaNPCAnimationManager.cpp
> +		LOG_WARNING("{} have not Component Audio Source", owner->GetName());
```suggestion
		LOG_WARNING("{} has not Component Audio Source", owner->GetName());
```

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +	LOG_VERBOSE("{} enter in CollisionExit",other->GetOwner()->GetName());
```suggestion
	LOG_VERBOSE("{} enters in CollisionExit",other->GetOwner()->GetName());
```

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +	if (other->GetOwner()->GetTag() == "Player") {
```suggestion
	if (other->GetOwner()->CompareTag("Player")) {
```

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +	if (other->GetOwner()->GetTag() == "Player") {
```suggestion
	if (other->GetOwner()->CompareTag("Player")) {
```

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +	if (other->GetOwner()->GetTag() == "Player") {
Please, when performing tag checks, use `CompareTag`.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/HealthSystem.cpp
> +		LOG_WARNING("{} not have ComponentParticleSystem", owner->GetName());
```suggestion
		LOG_WARNING("{} does not have ComponentParticleSystem", owner->GetName());
```

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/HealthSystem.cpp
> +	try {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/HealthSystem.cpp
> +		try {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/HealthSystem.cpp
> +		catch (const ComponentNotFoundException&) {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/HealthSystem.cpp
> +	catch (const ComponentNotFoundException&) {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +		catch (const ComponentNotFoundException&) {
The opening bracket of this `try...catch` block should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/ActivationLogic.cpp
> +	if (other->GetOwner()->GetTag() == "Player") {
The opening bracket of this `if statement` should go on the next line, as stated in our programming rules.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/TriggerSewersMusic.cpp
> +	try {
`try...catch` block not needed.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/TriggerSewersMusic.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
CompareTag("Player") instead, please. Same with all the following ones.

Also, changing this to a CompareTag eliminates the need of having the `try...catch` block.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/TriggerSewersMusic.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
IMO, I don't see the logs of the `try...catch` blocks necessary at all, its just "useless" info.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/TriggerSewersMusicExit.cpp
> +	try {
`try...catch` block not needed.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/CantinaNPCAnimationManager.cpp
> +	try {
Is this `try...catch` needed? Would there be situations in which a `ComponentAudioSource` is not found?

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/UIMissionTrigger.cpp
> +		player = App->GetModule<ModulePlayer>()->GetPlayer()->GetComponent<ComponentPlayer>();
Is this `try...catch` block needed? A player would always have a `ComponentPlayer`.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/UIMissionTrigger.cpp
> +	try {
Unnecessary `try...catch` block.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/UITrigger.cpp
> +	try {
Unnecessary `try...catch` block.

2023-07-31 10:43 UTC, markmeliaa commented on Game/Scripts/UITrigger.cpp
> +	try {
Unnecessary `try...catch` block.

2023-07-31 13:11 UTC, gerard-queralt commented on Game/Scripts/TriggerSewersMusic.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
I think they're fine as long as they are temporary. Just to indicate that a given component should be there, for some reason isn't, but for now we leave it as is. But I wouldn't want them in the final version either. That's why I'm not sure these fit that criteria. Having said that, I trust your judgement over mine on this.

2023-07-31 13:11 UTC, gerard-queralt commented on Game/Scripts/TriggerSewersMusic.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
I think they're fine as long as they are temporary. Just to indicate that a given component should be there, for some reason isn't, but for now we leave it as is. But I wouldn't want them in the final version either. That's why I'm not sure these fit that criteria. Having said that, I trust your judgement over mine on this.

2023-08-01 16:59 UTC, Dedado3000 approved these changes

2023-08-01 17:53 UTC, gerard-queralt commented
Now that #616 has been merged, we could take a look at which `try...catch` blocks can be removed, starting with the one in `ActivationLogic::Start`.

2023-08-03 09:17 UTC, MarcGonzalezMoratona commented on Game/Assets/Materials/Lv1_CargoBay_RunWay2Body_0.mat
> +    "DiffuseAssetPath": "C:\\Users\\eric\\Desktop\\Pasarelas\\Texturas\\Pasarela_Pasarela_BaseColor.png",
Is this working?

2023-08-03 09:18 UTC, MarcGonzalezMoratona commented on Game/Assets/Materials/Lv1_CargoBay_RunWay2Barandilla_0.mat
> +    "DiffuseAssetPath": "C:\\Users\\eric\\Desktop\\Pasarelas\\Texturas\\substanceBarandilla_Barandilla.002_BaseColor.png",
I think this path is not the right one

2023-08-03 09:43 UTC, MarcGonzalezMoratona commented on Game/Scripts/CantinaNPCAnimationManager.cpp
> +		LOG_WARNING("{} have not Component Audio Source", owner->GetName());
```suggestion
		LOG_WARNING("{} does not have a Component Audio Source", owner->GetName());
```

2023-08-03 09:44 UTC, MarcGonzalezMoratona commented on Game/Scripts/ActivationLogic.cpp
> +			LOG_WARNING("{} has not Component Rigid Body", child->GetName());
```suggestion
			LOG_WARNING("{} does not have Component Rigid Body", child->GetName());
```

2023-08-03 09:47 UTC, MarcGonzalezMoratona commented on Game/Scripts/HealthSystem.cpp
> +			LOG_WARNING("{} not have ComponentParticleSystem", owner->GetName());
```suggestion
			LOG_WARNING("{} does not have ComponentParticleSystem", owner->GetName());
```

2023-08-03 09:49 UTC, MarcGonzalezMoratona commented on Game/Scripts/TriggerSewersMusicExit.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
```suggestion
		LOG_WARNING("{} does not have ComponentPlayer", other->GetOwner()->GetName());
```

2023-08-03 09:50 UTC, MarcGonzalezMoratona commented on Game/Scripts/TriggerSewersMusicExit.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
Prever using CompareTag method as se saw in other comments

2023-08-03 09:52 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIMissionTrigger.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
Prefer using CompareTag method

2023-08-03 09:52 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIMissionTrigger.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
```suggestion
		LOG_WARNING("{} does not have ComponentPlayer", other->GetOwner()->GetName());
```

2023-08-03 09:53 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIMissionTrigger.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", owner->GetName());
```suggestion
		LOG_WARNING("{} does not have ComponentPlayer", owner->GetName());
```

2023-08-03 09:53 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
Prefer using CompareTag method

2023-08-03 09:55 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +		LOG_WARNING("{} have not ComponentPlayer", other->GetOwner()->GetName());
```suggestion
		LOG_WARNING("{} does not have ComponentPlayer", other->GetOwner()->GetName());
```

2023-08-03 09:56 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +		other->GetOwner()->GetComponent<ComponentPlayer>();
Prefer using CompareTag method

2023-08-03 10:01 UTC, MarcGonzalezMoratona commented
Thank you for your work, Eric! Keep in mind the comments about the assets and the try catch blocks

2023-08-03 17:48 UTC, gerard-queralt commented
Things to note after my changes:
- Left `try...catch` block for `ComponentParticleSystem` in `HealthSystem`. Doesn't look like a state machine exists for that animation, judging by the names. Updated log message to reflect this is just a patch and needs to be addressed.
- @Dedado3000 says assets are fine to be merged, but I agree with @MarcGonzalezMoratona that some of them don't look correct. Pending confirmation from Level Design team.

2023-08-04 04:32 UTC, AuxPort66 commented
> Things to note after my changes:
> * @Dedado3000 says assets are fine to be merged, but I agree with @MarcGonzalezMoratona that some of them don't look correct. Pending confirmation from Level Design team.

This was discussed in the meeting and its solved and checked.

2023-08-04 16:10 UTC, markmeliaa submitted a review, later dismissed
Thanks for taking the time to fix this pr @gerard-queralt, everything looks correctly!

2023-08-05 09:57 UTC, MarcGonzalezMoratona commented on Game/Scripts/CantinaNPCAnimationManager.cpp
> +#include "AxoLog.h"
I think we don't need this include right now

2023-08-05 09:59 UTC, MarcGonzalezMoratona commented on Game/Scripts/TriggerSewersMusic.cpp
> +#include "AxoLog.h"
do we need this include?

2023-08-05 10:00 UTC, MarcGonzalezMoratona commented on Game/Scripts/TriggerSewersMusicExit.cpp
> +#include "AxoLog.h"
maybe we don't need this

2023-08-05 10:00 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +#include "AxoLog.h"
do we need this include?

2023-08-05 10:11 UTC, MarcGonzalezMoratona approved these changes

2023-08-05 18:50 UTC, gerard-queralt commented
I've cleaned up the includes, but the network in this camping is so bad I can't pull to update my local branch, so I can't push the commit. Here's the patch, for whoever wants to [apply](https://git-scm.com/docs/git-apply) it xD
[0001-perf-cleaned-up-AxoLog-includes.patch](https://github.com/Horizons-Games/Axolotl-Engine/files/12267967/0001-perf-cleaned-up-AxoLog-includes.patch)

2023-08-05 19:56 UTC, gerard-queralt approved these changes

2023-08-05 20:02 UTC, MarcGonzalezMoratona approved these changes

2023-08-05 20:16 UTC, merged