feat: improve dash
Horizons-Games/Axolotl-Engine pull request #615
Opened 2023-07-30 15:48 UTC by MarcGonzalezMoratona

2023-07-30 15:56 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.cpp
> +			componentAnimation->SetParameter("IsRunning", false);
I would like to change the name of this parameter to IsWalking, because running is a different action. We should change Bix's state machine accordingly, so I didn't want to change that without asking. Please comment what you think about this. 

@Piterga12 
@AuxPort66 
@markmeliaa 

Everyone is invited to comment about this

2023-07-30 15:59 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.cpp
> +			float3 dashDirection(0.f, 0.f, 1.f);
@Piterga12 do you think that it is okay to initialize this to 0,0,1?

I think it is a default value to go front, isn't it? Probably we will never need it, but if we end up with this default value, isn't it better to have a 0,0,0 (meaning no dash) rather than a front dash even when the player is not looking front?

2023-07-30 16:01 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
> +void WindowInput::DrawWindowContents()
```suggestion

void WindowInput::DrawWindowContents()
```

2023-07-30 17:53 UTC, diegusmejia117 commented on Game/Scripts/PlayerMoveScript.cpp
> +			componentAnimation->SetParameter("IsRunning", false);
Hi Marc, i would advise against this as right now we indeed only have the running state(walking was taken down on a game meeting, as it was deemed to be running).

2023-07-30 18:56 UTC, Piterga12 commented on Game/Scripts/PlayerMoveScript.cpp
> +			componentAnimation->SetParameter("IsRunning", false);
The the commented code in line 171 for run, should be erased?

2023-07-30 19:00 UTC, Piterga12 commented on Game/Scripts/PlayerMoveScript.cpp
> +			float3 dashDirection(0.f, 0.f, 1.f);
I did initialise it like that because otherwise it wouldn't work in some weird cases, but maybe it's not necessary anymore to initialise it like that

2023-07-30 19:57 UTC, gerard-queralt commented on Game/Scripts/PlayerMoveScript.h
> +	bool GetIsParalyzed() const;
```suggestion
	bool IsParalyzed() const;
```

2023-07-30 19:57 UTC, gerard-queralt commented on Game/Scripts/PlayerJumpScript.h
May I ask why this was moved into `PlayerManagerScript`? As a rule of thumb, the more scripts the better. And if there was a reason for it, why leave this script basically empty?

2023-07-30 19:57 UTC, gerard-queralt commented on Game/Scripts/PlayerMoveScript.h
> +	bool GetCanJump() const;
```suggestion
	bool CanJump() const;
```

2023-07-30 19:57 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform2D.cpp
> +#include "WindowComponentTransform2D.h"
I personally prefer full paths, since it's more strict, but that's just me. Feel free to ignore me ;)

2023-07-30 19:57 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
The user can still click on the buttons, even though they do nothing. Could you check if there's an ImGui flag to prevent this?

2023-07-30 19:57 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
> +	const char* buttonLabels[numButtons] = { "Q", "W", "E", "R", "A", "S", "D", "F", "Z", "X", "C", "V" };
This is all constant, but this arrays are allocated and freed each frame. It'd be better if you could define them in an unnamed namespace in the source file. You can look at [WindowComponentSlider](https://github.com/Horizons-Games/Axolotl-Engine/blob/develop/Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentSlider.cpp#L11) for an example.

2023-07-30 21:22 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.cpp
> +			componentAnimation->SetParameter("IsRunning", false);
perfect, we can leave it as it is right now, then. Thank you Diego!

2023-07-30 21:24 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
> +	const char* buttonLabels[numButtons] = { "Q", "W", "E", "R", "A", "S", "D", "F", "Z", "X", "C", "V" };
nice catch, thank you Gerard!

2023-07-30 21:26 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
I'll check it. I used ImGui::Selectable because buttons force you to click before the action, and selectable make what we need. I'll take a deeper look to the Selectable component

2023-07-30 21:27 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform2D.cpp
> +#include "WindowComponentTransform2D.h"
This was changed because the component was in the wrong folder. I could use full paths, but I think there are too much places to make this change right now

2023-07-30 21:30 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerJumpScript.h
The initial idea was to remove the PlayerJumpScript because we need some information about the jump inside the movement script and I didn't find a better way to get it. I thought that we could delete it because both of them (movement and jump) are basic player actions, and also related to each other.

The file was not deleted because of a merge conflict that messed it up.

Anyway, I'll try to find a better way to comunicate info between scripts without deleting the PlayerJumpScript.

2023-07-30 21:32 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.h
> +	bool GetIsParalyzed() const;
I'll apply this change, it was a method name inherited from previous PRs

2023-07-30 21:32 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.h
> +	bool GetCanJump() const;
Same situation that in the one before

2023-07-30 21:41 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/80526953/a2af9495-45f8-421d-88cd-a8c543b28c37)

2023-07-30 21:43 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
After testing a bit, disabled flag does what we need

2023-07-30 21:47 UTC, MarcGonzalezMoratona commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
> +	const char* buttonLabels[numButtons] = { "Q", "W", "E", "R", "A", "S", "D", "F", "Z", "X", "C", "V" };
@gerard-queralt should I put only the labels and keys arrays or the numeric constants too?

2023-07-30 21:53 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerMoveScript.cpp
> +			float3 dashDirection(0.f, 0.f, 1.f);
You are right. The static dash does not work without this values.

2023-07-31 08:41 UTC, gerard-queralt commented on Game/Scripts/PlayerJumpScript.h
My main concern is that we might be able to reuse the jump logic for another game object, like the boss (with some adjustments, of course). If that's not something we want there's not really an issue. An option would be to add the jump script as a field of the move one, but again, might not be necessary. I trust your judgement ;)

2023-07-31 08:43 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/WindowInput.cpp
> +	const char* buttonLabels[numButtons] = { "Q", "W", "E", "R", "A", "S", "D", "F", "Z", "X", "C", "V" };
Yes, better to have them all in one place. Easier to modify them this way too.

2023-07-31 08:48 UTC, gerard-queralt commented on Game/Scripts/PlayerMoveScript.cpp
> +			float3 dashDirection(0.f, 0.f, 1.f);
If that's the case, maybe we should initialize it with the forward of the player. Unless I'm misunderstanding your conversation, this seems to work because the player starts facing the Z axis, but that might not be the case in future levels.

2023-08-01 21:35 UTC, gerard-queralt commented on Game/Scripts/PlayerMoveScript.cpp
> +		if (GetPlayerState() != PlayerActions::WALKING && !isDashing && jumpScript->IsGrounded() && !bixAttackScript->IsAttacking())
This is just a coding style thing so feel free to disagree with me, but when conditions get this long I prefer declaring a variable and naming it with what the condition actually is. As someone who has never touched this script, I understand that we are checking if the player is not walking, is not dashing, is grounded and is not attacking. But I have no idea what this all actually means. I need to check the code inside the `if`, and it looks like it means the player is running

2023-08-02 10:50 UTC, markmeliaa requested changes
Thank you both for your work, I just have one concern aside from some code suggestions.

Right now, if I'm not seeing it wrong, when the character dashes, it automatically gets teleported "x" distance infront of them, which makes me worry about how would we add the animation here. Ideally, instead of a teleporting we need to see the player during the whole transition of the dash, so the animation can be seen correctly. If you have any doubt about that, do not hesitate in contacting me.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/BixAttackScript.h
> +}
Good call making this functions inline, but we don't do inlines in gameplay scripts. I know inlines are more optimal, but we started not doing inlines due to having no hot reloading in the header files, so we decided to leave all the small functions in the source files (even after having hot reloading).

So, if you could add them back to the source file please.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/ComboManager.h
> +inline bool ComboManager::IsSpecialActivated() const
Same here with this inline.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/DebugGame.cpp
> +	else if (playerHealthSystem->IsImmortal())
Not your fault, but this could be just a simple `else statement`.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/DebugGame.cpp
> +	else if (playerAttackScript->IsDeathTouched())
And same here.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/HealthSystem.h
> +}
Again, swap these to the source file pls.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/PlayerJumpScript.h
> +}
To the source file.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.cpp
> +			float3 dashDirection(0.f, 0.f, 1.f);
Yea, if I'm catching this correctly too, the forward of the player would be a more suitable value than just `1.f` in the z.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.cpp
> +			isDashing = true;
Could you encapsulate all this logic of the dash into its own function? It would improve the readability.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.cpp
> +	if (!isDashing)
Instead of indexing all the code inside this `if statement` you could actually just write
```c++
if (isDashing)
{
   return;
}

//The rest of the code
```
So this way we would have less levels of indentation and the code will look cleaner.

2023-08-02 10:50 UTC, markmeliaa commented on Game/Scripts/PlayerMoveScript.h
> +}
To the source file.

2023-08-02 12:59 UTC, markmeliaa commented
> We wanted to make the dash a bit more spectacular by increasing the dash force. The player is moving fast, but by reducing this value we can remove this sense of "teleport". We can play with the value to reduce the force and align correctly with the animation once it's ready. I think we should talk about this together to find the best visual feedback for the player

Sure, we could talk about this in tomorrow's game meeting, at 18:30!

2023-08-04 09:06 UTC, markmeliaa commented
I've been trying values and seems that 2000 for the dash force is the best value we can give to it right now, so if you change it in the scene and fix the conflicts, we can merge this pr.

2023-08-04 11:13 UTC, markmeliaa approved these changes

2023-08-04 17:36 UTC, gerard-queralt commented on Game/Scripts/PlayerJumpScript.cpp
> +	moveScript = owner->GetComponent<PlayerMoveScript>();
I could be missing something, but are we using this variable anywhere? Because if not, we're potentially creating an unnecessary dependency. With the latest changes in scripting, a script will stop running if one of the components it asks for is not found. That will obviously not happen here, but I think it's a good thing to keep in mind.

2023-08-05 15:21 UTC, diegusmejia117 approved these changes

2023-08-05 15:23 UTC, merged