Filesystem/skybox resource loader
Horizons-Games/Axolotl-Engine pull request #623
Opened 2023-08-03 17:41 UTC by ericdacal

Skybox now can be change in runtime

2023-08-03 21:26 UTC, PaablooCH requested changes
Hi i found 3 things all regarding includes

2023-08-03 21:26 UTC, PaablooCH commented on Source/DataModels/Components/ComponentSkybox.h
> +#include "Skybox/Skybox.h"
Use `class Skybox`

2023-08-03 21:26 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceSkyBox.cpp
> +#include "ModuleResources.h"
Not used

2023-08-03 21:26 UTC, PaablooCH commented on Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowMaterialInput.cpp
> +#include "Skybox/Skybox.h"
Not used

2023-08-03 22:09 UTC, ericdacal commented on Source/DataModels/Components/ComponentSkybox.h
> +#include "Skybox/Skybox.h"
Done

2023-08-03 22:12 UTC, ericdacal commented on Source/DataModels/Resources/ResourceSkyBox.cpp
> +#include "ModuleResources.h"
Remove

2023-08-03 22:14 UTC, ericdacal commented on Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowMaterialInput.cpp
> +#include "Skybox/Skybox.h"
Remove

2023-08-07 22:50 UTC, PaablooCH submitted a review, later dismissed
all is perfect

2023-08-07 22:50 UTC, PaablooCH commented on Source/DataModels/Resources/ResourceSkyBox.cpp
>  #include "AxoLog.h"
you didn't include but pls this is not necessary :D

2023-08-08 12:22 UTC, AlexisDieu submitted a review, later dismissed
Working fine !

2023-08-10 01:38 UTC, AuxPort66 requested changes
It explodes when import a scene, because the component doesn't have any skybox loaded and the load tries to enable it. This is because the Load is done in the SkyBox of the Scene and not directly in the SkyBox of the Component. We should change that.

Anyway, we should filter the skybox component in the LoadSceneFromJson function in ModuleScene.cpp (or further in as in the CreateHierarchyFromJson function) when mantainActualScene is true because we don't want two skyboxes when we import a second scene.

2023-08-10 01:38 UTC, AuxPort66 commented on Source/DataModels/Resources/ResourceSkyBox.h
> +	std::vector<std::shared_ptr<ResourceTexture>> loadedTextures;
This is used?

2023-08-10 01:38 UTC, AuxPort66 commented on Source/DataModels/Components/ComponentSkybox.h
> +	Skybox* skybox;
If we have here a skybox maybe the correct thing to do is erase the SkyBox* skybox of Scene.h and use this skybox. Anyways all the code of SkyBox.h/.cpp is the code of a component so we can move all the code of SkyBox here and use this instead, this will be more easy to treat on Load/Import Scene and with this change it will not explode on the importer even without the filter.

2023-08-10 01:38 UTC, AuxPort66 commented on Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowSkyboxInput.cpp
> +	skyboxComponent->SetSkybox(App->GetModule<ModuleScene>()->GetLoadedScene()->GetSkybox());
And if we delete Skybox and only use the Component we can simplify this.

2023-08-14 22:20 UTC, ericdacal commented on Source/DataModels/Resources/ResourceSkyBox.cpp
>  #include "AxoLog.h"
Remove

2023-08-14 22:24 UTC, ericdacal commented on Source/DataModels/Resources/ResourceSkyBox.h
> +	std::vector<std::shared_ptr<ResourceTexture>> loadedTextures;
Not used, remove

2023-08-15 17:12 UTC, ericdacal commented on Source/DataModels/Components/ComponentSkybox.h
> +	Skybox* skybox;
Skybox removed

2023-08-15 17:14 UTC, ericdacal commented on Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowSkyboxInput.cpp
> +	skyboxComponent->SetSkybox(App->GetModule<ModuleScene>()->GetLoadedScene()->GetSkybox());
I remove Skybox class and now skybox is rendered when there is the skybox component. When import a scene with another skybox, the only skybox keep is the current, no imported scene.

2023-08-19 22:57 UTC, AuxPort66 commented on Source/Modules/ModuleScene.cpp
> -	selectedGameObject = loadedScene->GetRoot();
With out this line the scene explode when you have something selected and then load another scene. The rest seems fine, but you need to update all the scenes (right now all the json have the old skybox json reference, so no scene has skybox or skybox component)

2023-08-20 10:43 UTC, ericdacal commented on Source/Modules/ModuleScene.cpp
> -	selectedGameObject = loadedScene->GetRoot();
I include the line again, if there is not Skybox Component in the scene can be include using GUI. Even so I modify all the scene, removing all Skybox objects and including default Skybox Component.

2023-08-20 12:50 UTC, AuxPort66 submitted a review, later dismissed
Good job, now works perfect

2023-08-31 16:26 UTC, Dedado3000 submitted a review, later dismissed

2023-08-31 18:06 UTC, gerard-queralt commented on Source/Modules/ModuleRender.cpp
> +		loadedScene->GetRoot()->GetComponent<ComponentSkybox>()->Draw();
```suggestion
		loadedScene->GetRoot()->GetComponentInternal<ComponentSkybox>()->Draw();
```

2023-08-31 18:06 UTC, gerard-queralt commented on Source/Modules/ModuleScene.cpp
> +	skybox->SaveOptions(jsonScene);*/
We can delete this.

2023-09-01 10:34 UTC, ericdacal commented on Source/Auxiliar/SceneLoader.cpp
> +//#include "DataModels/Skybox/Skybox.h"
Remove

2023-09-01 10:37 UTC, ericdacal commented on Source/Auxiliar/SceneLoader.cpp
> +		if (obj->HasComponent<ComponentSkybox>()  && currentLoadingConfig->mantainCurrentScene)
Done

2023-09-01 10:39 UTC, ericdacal commented on Source/DataModels/Components/ComponentSkybox.cpp
> +void ComponentSkybox::SetSkyboxResource(const std::shared_ptr<ResourceSkyBox> resource)
Done

2023-09-01 10:44 UTC, ericdacal commented on Source/DataModels/Scene/Scene.cpp
> +		root->GetComponentInternal<ComponentSkybox>()->SetSkyboxResource(resourceSkybox);
Done

2023-09-01 10:45 UTC, ericdacal commented on Source/Modules/ModuleScene.cpp
> +	skybox->SaveOptions(jsonScene);*/
Done

2023-09-01 10:52 UTC, ericdacal commented on Source/DataModels/Components/ComponentSkybox.h
> +	bool enable;
I use this name, because in the Inspector GUI , enable is the name for this functionality.

2023-09-01 11:32 UTC, ericdacal commented on Source/DataModels/Components/ComponentSkybox.cpp
> +	jsonSkybox["skyboxAssetPath"] = skyboxRes->GetAssetsPath().c_str();
Added and also in all the current scenes in the game

2023-09-01 11:40 UTC, ericdacal commented on Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
> +		const std::string names[] = { "Right", "Left", "Top", "Bottom", "Back", "Front" };
Done

2023-09-01 14:54 UTC, gerard-queralt submitted a review, later dismissed

2023-09-02 13:11 UTC, gerard-queralt approved these changes

2023-09-04 16:41 UTC, gerard-queralt approved these changes

2023-09-05 14:26 UTC, gerard-queralt approved these changes

2023-09-05 18:29 UTC, AuxPort66 approved these changes

2023-09-05 18:33 UTC, diegusmejia117 approved these changes
BEAUTIFUL SKYBOX

2023-09-05 18:33 UTC, merged