fix[WindowComponentMeshRenderer]: remove call to BeginChild
Horizons-Games/Axolotl-Engine pull request #635
Opened 2023-08-07 21:01 UTC by gerard-queralt

As per `ImGui::BeginChild` documentation (skipping to the relevant part):

> For each independent axis of 'size': ==0.0f: use remaining host window size / >0.0f: fixed size / <0.0f: use remaining window size minus abs(size) / Each axis can use a different mode, e.g. ImVec2(0,400).

Looks like this was the reason the window took the remaining space of the parent window.

2023-08-08 08:32 UTC, markmeliaa submitted a review, later dismissed
LGTM!

2023-08-10 01:01 UTC, AuxPort66 requested changes
If you remove the beginChild the material doesn't put to red when you change things so Level and art don't have any visual input to know they didn't save the edited material. Don't erase that functionality. And ask me if you didn't know why something is there pls.

2023-08-10 07:18 UTC, gerard-queralt commented
> If you remove the beginChild the material doesn't put to red when you change things so Level and art don't have any visual input to know they didn't save the edited material. Don't erase that functionality.

Could you be more specific on what's the functionality so I know how to test it? I was hoping `PushID` would achieve the same thing, but I guess you've tested it and it doesn't.

> And ask me if you didn't know why something is there pls.

Already did, pinged you in the engine channel.

2023-08-10 07:30 UTC, gerard-queralt commented
Nevermind, got it. But the need to use `BeginChild` only comes from using the flag `ImGuiCol_ChildBg` to set the background.

2023-08-10 09:23 UTC, gerard-queralt commented
@AuxPort66 should be fixed, check it when you can

2023-08-10 19:11 UTC, AuxPort66 commented
> Already did, pinged you in the engine channel.
Before the PR, about the issue.

I check it. Everything seems correct. Nice.

2023-08-10 19:11 UTC, AuxPort66 approved these changes

2023-08-10 19:14 UTC, markmeliaa approved these changes

2023-08-10 22:44 UTC, merged