feat: capactity to discard meshes and use its diffuseColor, effect damage && create a batch exclusively for Characters
Horizons-Games/Axolotl-Engine pull request #648
Opened 2023-08-16 16:09 UTC by PaablooCH

Things added:

- In order to create the effect I add the capacity to choose if we want to discard (not render, for the people outside graphics :)) or choose the diffuseColor for a mesh. You can test it through interface.
- Too make it less cost that change I create a new category for batches to store Characters, who are the ones that must use the effect. Characters are the ones who uses the tag `Player` or `Enemy` and his children, when you modify a tag if now is a character or was a character, the gameObject and his children will be moved to the correct batch.
- I create the effect inside healtScript. It's important that once you finish changing the mesh call FillBatchMaterial();

If you want to test the effect go to any scene and let you be hitted

Other things:

- Clear objectIndexes in batch before fill it again.
- Solve warings.

2023-08-17 18:34 UTC, markmeliaa requested changes
Nice job, tried it and works correctly, my only complain is that when the mesh turns red after a hit it is for a really brief period of time, maybe we could extend a little bit that time so it is easier for the player to see the effect?

P.S. Didn't check the shaders because my knowledge about them is practically non-existent.

2023-08-17 18:34 UTC, markmeliaa commented on Source/DataModels/Batch/BatchManager.cpp
> +	for (auto child : go->GetChildren())
Couldn't this `auto` be a `GameObject*`?

2023-08-17 18:34 UTC, markmeliaa commented on Source/DataModels/Batch/BatchManager.cpp
> +	for (auto child : parent->GetChildren())
Same with this `auto`.

2023-08-17 18:34 UTC, markmeliaa commented on Source/Modules/ModuleRender.cpp
Lines 757, 803 and 894 raise a warning, could you take a look at them please? Not really related in this pr.

2023-08-17 19:53 UTC, PaablooCH commented
> maybe we could extend a little bit that time so it is easier for the player to see the effect?

It can be tweaked with the values `TIME_BETWEEN_EFFECTS` and `MAX_TIME_EFFECT_DURATION` so is not a big problem, if you want you can also add more transitions like `color-discard-color` or `discard-color` instead of what is now `color-discard`.

2023-08-17 19:55 UTC, PaablooCH commented on Source/DataModels/Batch/BatchManager.cpp
> +	for (auto child : go->GetChildren())
i use auto to avoid writting each time GameObject*, it doesn't affect the performance.

2023-08-17 20:08 UTC, markmeliaa approved these changes

2023-08-18 06:12 UTC, UriMurcia commented
Hi! I've haven't time to see all the code and test it, but from the part of gameplay I think it would be interesting that the functions that change the color of the mesh wouldn't depend from HealthSystem script, we may want to use these functionality for other purposes, for example, when the drone is seeking the player to explode.
I'll take a look to the other things when I have time! :)

2023-08-20 13:37 UTC, markmeliaa requested changes
*solved*

2023-08-23 14:13 UTC, MacXxs commented
We need to first approve PR #647 before this one in order to adapt the percentage selection from texturing into the tiling changes done in this PR (that maybe shouldn't been done in this one actually in order to not have any trouble while merging with developments from other PRs)

2023-08-24 18:40 UTC, markmeliaa reviewed
I'm failing to see the effect happening now, is the damage effect not red anymore or is it so fast that I can't even percieve it?

2023-08-24 18:40 UTC, markmeliaa commented on Game/Scripts/MeshEffect.cpp
> +	for (auto mesh : meshes)
```suggestion
	for (ComponentMeshRenderer* mesh : meshes)
```

2023-08-24 18:40 UTC, markmeliaa commented on Game/Scripts/MeshEffect.cpp
> +	for (auto mesh : meshes)
```suggestion
	for (ComponentMeshRenderer* mesh : meshes)
```

2023-08-24 18:40 UTC, markmeliaa commented on Game/Scripts/MeshEffect.cpp
> +	for (auto mesh : meshes)
```suggestion
	for (ComponentMeshRenderer* mesh : meshes)
```

2023-08-24 18:40 UTC, markmeliaa commented on Source/DataModels/Scene/Scene.cpp
> +	for (auto childSelected : selected->GetChildren())
```suggestion
	for (GameObject* childSelected : selected->GetChildren())
```

2023-08-24 22:46 UTC, markmeliaa commented on Source/DataModels/Scene/Scene.cpp
> +	for (auto childSelected : selected->GetChildren())
Pablo ignora mis requests.

2023-08-24 22:58 UTC, markmeliaa approved these changes
LGTM now! (La proxima vez acosa a otro, grax).

2023-08-26 15:54 UTC, MacXxs commented
Level1 throws error when pressing play:

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/6d2b4660-8ff4-42a0-968e-089b79ed7aaf)

Try merging again with Graphics-main, once it works well i'll approve the PR.

2023-08-26 16:01 UTC, PaablooCH commented
> Level1 throws error when pressing play:
> 
> ![image](https://user-images.githubusercontent.com/18547655/263474081-6d2b4660-8ff4-42a0-968e-089b79ed7aaf.png)
> 
> Try merging again with Graphics-main, once it works well i'll approve the PR.

Lvl1 doen't have the script Mesh Effect, remember we can not touch lvls ;) to avoid problems with level team, only is implemented in gameplay scene and prefabs

2023-08-26 16:47 UTC, MacXxs commented
> > Level1 throws error when pressing play:
> > ![image](https://user-images.githubusercontent.com/18547655/263474081-6d2b4660-8ff4-42a0-968e-089b79ed7aaf.png)
> > Try merging again with Graphics-main, once it works well i'll approve the PR.
> 
> Lvl1 doen't have the script Mesh Effect, remember we can not touch lvls ;) to avoid problems with level team, only is implemented in gameplay scene and prefabs

In the Graphics-main branch level1 is playable, and this PR is a branch from Graphics-main, so the same level should be playable.

2023-08-26 16:51 UTC, MacXxs approved these changes

2023-08-26 18:28 UTC, merged