feat[Filesystem]: Video Component for UI Canvas
Horizons-Games/Axolotl-Engine pull request #655
Opened 2023-08-20 11:03 UTC by ericdacal

Video Component for UI that can be include in Canvas gameobject. Component includes flip and loop.

2023-08-21 08:00 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			response = avcodec_send_packet(videoCodecCtx, avPacket);
What's the difference between `response` and `error`? They seem to be used very similarly.

2023-08-21 08:02 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +				// LOG_ERROR("Failed to decode frame: %s.", libav_err2str(response));
If you want to, you can still add this information in the log.
```suggestion
				LOG_ERROR("Failed to decode frame: {}", libav_err2str(response));
```

2023-08-21 08:02 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		uint8_t* dest[4] = { frameData, nullptr, nullptr, nullptr };
Do we need to free this pointer or is it handled by the lib?

2023-08-21 08:03 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	ComponentTransform2D* transform = GetOwner()->GetComponentInternal<ComponentTransform2D>();
Again, I'd check the transform, log if not found.

2023-08-21 08:03 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	if (av_seek_frame(formatCtx, videoStreamIndex, -1, 0) >= 0)
Empty if block.

2023-08-21 08:05 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	bool GetRotateVertical();
In general, getters for booleans use verbs like "is" or "can" instead of "get"
```suggestion
	bool IsLooping();
	void SetCanBeRotate(bool canRotate);
	bool CanBeRotate();
	void SetRotateVertical(bool rotateVertical);
	bool CanRotateVertical();
```

2023-08-21 08:07 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	SwsContext* scalerCtx = nullptr;
None of these pointers are freed. I assume this is all handled by the lib, but pointing it out just in case.

2023-08-21 08:07 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.h
> +
Extra line break :P

2023-08-21 08:09 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	this->video = video;
Make sure reference count is increased. We're creating a copy anyway when assign it, so it makes no difference in performance.
```suggestion
inline void ComponentVideo::SetVideo(std::shared_ptr<ResourceVideo> video)
{
	this->video = std::move(video);
```

2023-08-21 08:11 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +			newComponent = std::make_unique<ComponentVideo>(*static_cast<ComponentVideo*>(component));
Have you checked that a shallow copy is enought? I worry that two components can't share the same `frameData`, especially if we properly free the memory.

2023-08-21 08:14 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			video = resourceImage;
Use move instead of copy, since it's more efficient.
```suggestion
			video = std::move(resourceImage);
```

2023-08-21 08:15 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceVideo.cpp
Since I assume this PR is intended to be a proper first version of this feature, I don't think the Resource should be empty.

2023-08-21 08:17 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentVideo.cpp
> +	//DrawEnableAndDeleteComponent();
```suggestion
	DrawEnableAndDeleteComponent();
```

2023-08-21 08:18 UTC, gerard-queralt commented on Source/FileSystem/ModuleResources.cpp
> +#include "AxoLog.h"
Not needed, since it's in the pch.

2023-08-21 08:25 UTC, gerard-queralt commented on Source/Modules/ModuleUI.cpp
> +			video->ReadVideoFrame();
Won't this make it so the video plays even if the game is not running in the engine?

2023-08-21 08:29 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			Init();
Nevermind, forgot that Components don't have an Init so the engine won't call it. However, it is still called twice from within the code (and can be called endlessly for all we know, since the method is public), so the question stands.

2023-09-04 16:40 UTC, gerard-queralt approved these changes

2023-09-15 08:32 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	if (extension != ".avi")
Done

2023-09-15 08:33 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			video = resourceImage;
Done

2023-09-15 08:34 UTC, ericdacal commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentVideo.cpp
> +	//DrawEnableAndDeleteComponent();
Done

2023-09-15 08:41 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	glGenTextures(1, &frameTexture);
It seems that can I have two videos in a scene at same time, then I suposse that this works. It is based in ImageComponent.
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/16444893/09c1c630-ca1d-46e4-b81d-47d72d98960d)

2023-09-15 08:47 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		ComponentTransform2D* transform = GetOwner()->GetComponentInternal<ComponentTransform2D>();
I've included this check:
`c++
if (!GetOwner()->HasComponent<ComponentTransform2D>())
{
	throw ComponentNotFoundException("Owner does not have ComponentTrasnform2D");
}`

2023-09-15 08:50 UTC, ericdacal commented on Source/DataModels/Resources/ResourceVideo.cpp
I change this, now I copy the video to Lib, to can be play in Game also. Videos is an special case, because we don't convert the video in to Binary Extension because we make stream directly from the packets of video formats(avi, mp4 and mov).

2023-09-15 08:53 UTC, ericdacal commented on Source/FileSystem/ModuleResources.cpp
> +#include "AxoLog.h"
Done

2023-09-15 08:56 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	if (program)
Done

2023-09-15 09:55 UTC, ericdacal commented on Source/Modules/ModuleUI.cpp
> +			video->ReadVideoFrame();
Now there are options of Play and Pause video.

2023-09-15 09:56 UTC, ericdacal commented
> Aside from the comments, one general question. Is the video able to be paused? Mainly asking because I intend to finish the pause PR this week (#499), and it'd be a great help if this was already doable.

Now there are options of Play and Pause video.

2023-09-20 04:04 UTC, AuxPort66 commented on Source/DataModels/Scene/Scene.cpp
> +			//... [Your existing slider code]
???

2023-09-21 11:22 UTC, ericdacal commented on Source/DataModels/Scene/Scene.cpp
> +			//... [Your existing slider code]
Slide came to life again!

2023-09-22 02:04 UTC, AuxPort66 commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	glGenTextures(1, &frameTexture);
I didn't see this question until now. ComponentImage doesn't do the Set of the texture buffer in the component. The base of all the components that render is that they share the texture buffer if they have the same texture. That's why resource Load exists.

2023-09-28 00:37 UTC, AuxPort66 approved these changes
👍

2023-09-29 11:44 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		ComponentTransform2D* transform = GetOwner()->GetComponentInternal<ComponentTransform2D>();
Not sure if this is the right approach. Someone would need to catch the exception, which is a weird thing in this context, otherwise the app would crash. Do you think it would be an issue to log an error and abort the method with a return statement? If you can do that, you'd need to either deactivate the program or activate after the check.

2023-09-29 11:47 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceVideo.cpp
Please add this to GameBuilder, the whole release should be doable from there. You can check how the Scenes folder are added to the Lib.

2023-09-29 11:50 UTC, gerard-queralt commented on Source/Modules/ModuleUI.cpp
> +			video->ReadVideoFrame();
Thanks, but that wasn't the question. Can you check that the video does not play while in the Engine and not in Play mode? Or that if it does it is the intended behavior.

2023-09-29 12:05 UTC, ericdacal commented on Source/Modules/ModuleUI.cpp
> +			video->ReadVideoFrame();
Actually we include a new option PlayWhenStart, that Play the video when is Play mode. In other hand I think that is better to can play in Engine mode, to previsualize that all is correct and can for example use the Vertital Rotation option.

2023-09-29 21:57 UTC, AuxPort66 approved these changes

2023-09-30 12:40 UTC, Vlukkee approved these changes
Thanks!

2023-10-01 01:16 UTC, gerard-queralt commented on Source/Modules/ModuleUI.cpp
> +			video->ReadVideoFrame();
Perfect, just to confirm it was intended to work this way 👍

2023-10-01 01:46 UTC, gerard-queralt requested changes
Requesting changes because I'm almost sure there are memory leaks. Please also take a look at the comments from my review in August, some of them still stand and I consider them important, like [this one](https://github.com/Horizons-Games/Axolotl-Engine/pull/655#discussion_r1341266872).

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	bool GetLoop();
This and the other getters can be `const`.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	bool isPlayAtStart();
```suggestion
	bool IsPlayed();
	bool IsPlayAtStart();
```
Also, I have no idea what "is played" means. Whether it's done playing? I think we can find a better name.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		frameData = new uint8_t[video->GetFrameWidth() * video->GetFrameHeight() * 4];
Unless I'm missing it, we're not freeing this memory -> memory leak. I'd suggest using a unique pointer, but whatever you prefer.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		throw ComponentNotFoundException("Owner does not have ComponentTrasnform2D");
As I said in the other comment, this is almost certainly going to cause a crash because no one is catching the exception. Just check if the transform is null and return if it is. Make sure to do so before all the other calls that require a closing one, like `program->Activate()` that requires you to call `program->Deactivate()`.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	if (canvas)
Should we log a warning/error in the else? Don't think this is expected.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	else program->BindUniformInt("hasDiffuse", 0);
```suggestion
	else
	{
		program->BindUniformInt("hasDiffuse", 0);
	}
```

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	std::string assetPath = "";
This looks unused.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	{
Empty if, probably forgot something.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +}
Why not inline these?

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +			newComponent = std::make_unique<ComponentVideo>(*static_cast<ComponentVideo*>(component));
I see you've implemented a copy constructor.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/GameObject/GameObject.cpp
> +
Don't think we need this.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceVideo.h
> +	AVFrame* avFrame = nullptr;
This looks like is managed by the lib, but can you verify that it is? Just to make sure we're not leaking anything.

2023-10-01 01:46 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.h
> +	std::vector<ComponentVideo*> sceneVideos;
Is this used? Doesn't look like UI is reading it. Haven't checked all the code so might have missed it. If it's not used please remove it, last thing we need is more vectors of components going around :P

2023-10-01 01:46 UTC, gerard-queralt commented on Source/FileSystem/ModuleResources.h
> +		}
```suggestion
		std::string libExtension = type == ResourceType::Video ? extension : GENERAL_BINARY_EXTENSION;
```

2023-10-01 01:46 UTC, gerard-queralt commented on Source/FileSystem/ModuleResources.h
> +		}
Same here, if you agree with the previous suggestion.

2023-10-01 01:50 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			Init();
Pretty sure this is no longer relevant, we don't seem to initialize explicitly anymore. Can you confirm that's the case?

2023-10-04 16:53 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +{
I think no because this is manage in ResourceVideo. But I include in this destructor the manage of the member frameData and scalerCtx.
`c++
ComponentVideo::~ComponentVideo()
{
	if (frameData)
	{
		delete[] frameData;
		frameData = nullptr;
	}

	if (scalerCtx)
	{
		sws_freeContext(scalerCtx);
		scalerCtx = nullptr;
	}
}
`

2023-10-04 17:06 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		if (canvas)
Video cannot be create outside of a Canvas, but can be move outside. I include a ERROR_LOG for this case.

2023-10-04 17:10 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		else program->BindUniformInt("hasDiffuse", 0);
Done

2023-10-04 17:13 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			Init();
Now that change, the Init is done inside the VideorResource not in the Component.

2023-10-04 17:14 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.h
> +
Removed line

2023-10-04 17:34 UTC, ericdacal commented on Source/FileSystem/ModuleResources.h
> +		}
Done

2023-10-04 17:34 UTC, ericdacal commented on Source/FileSystem/ModuleResources.h
> +		}
Done

2023-10-04 17:39 UTC, ericdacal commented on Source/DataModels/Scene/Scene.h
> +	std::vector<ComponentVideo*> sceneVideos;
Yes, is use to initialize the VideoComponent in ModuleScene.

```c++
void ModuleScene::InitVideoComponents()
{
	for (ComponentVideo* componentVideo : loadedScene->GetSceneVideos())
	{
		if (componentVideo->GetOwner()->IsActive() && componentVideo->GetPlayAtStart())
		{
			componentVideo->Play();
		}
	}
}
```

2023-10-04 17:47 UTC, ericdacal commented on Source/DataModels/Resources/ResourceVideo.h
> +	AVFrame* avFrame = nullptr;
I check and that variable has to be manage, I do this in Destructor:
```c++
void ResourceVideo::InternalUnload()
{
	glDeleteTextures(1, &glFrameBuffer);
	glFrameBuffer = 0;
	if (formatCtx)
	{
		avformat_close_input(&formatCtx);
	}
	if (videoCodecCtx)
	{
		avcodec_close(videoCodecCtx);
		av_free(videoCodecCtx);
	}
	if (avPacket)
	{
		av_packet_unref(avPacket);
		av_packet_free(&avPacket);
	}
	if (avFrame)
	{
		av_frame_free(&avFrame);
	}
}
```

2023-10-05 08:30 UTC, ericdacal commented on Source/DataModels/Resources/ResourceVideo.cpp
Done

2023-10-05 11:04 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	frameData = new uint8_t[frameWidth * frameHeight * 4];
frameData now is delete in the Destructor

2023-10-05 11:11 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	bool GetRotateVertical();
Done

2023-10-05 22:43 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	initialized = true;
Now is manage for VideoResource and I delete this variable

2023-10-05 22:43 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		int response = -1;
It doesn't exist now

2023-10-05 22:45 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		int error = 0;
I change the name for result

2023-10-05 22:49 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +}
Done

2023-10-06 13:42 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +				// LOG_ERROR("Failed to decode frame: %s.", libav_err2str(response));
It is a deprecated function libav_err2str.

2023-10-06 13:43 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	SwsContext* scalerCtx = nullptr;
Now is manage and delete in VideoResource

2023-10-06 13:44 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	this->video = video;
Done

2023-10-06 13:45 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	std::string assetPath = "";
Removed

2023-10-06 13:54 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	bool resourceExists = !path.empty() && App->GetModule<ModuleFileSystem>()->Exists(path.c_str());
Maybe it is not necessary, that is done because also is done in ComponentImage

2023-10-06 14:02 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	{
This line restart the video if fails go inside the if. I include now a LOG_ERROR that tell the user that there is a fail in the restart.

2023-10-06 14:05 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +			response = avcodec_send_packet(videoCodecCtx, avPacket);
Is the same but one for packets and the other to avlib, I change the name of error to be more clarify.

2023-10-06 14:12 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	ComponentTransform2D* transform = GetOwner()->GetComponentInternal<ComponentTransform2D>();
I include a log if not found the transform

2023-10-06 14:25 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		uint8_t* dest[4] = { frameData, nullptr, nullptr, nullptr };
dest is define in stack and do not need to be remove, and frameData now is delete in the Destructor

2023-10-06 17:27 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +{
It wasn't when I added the comment. Now everything seems to be getting freed, thanks!

2023-10-06 17:28 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	bool resourceExists = !path.empty() && App->GetModule<ModuleFileSystem>()->Exists(path.c_str());
Would like to know why but not that important I guess.

2023-10-06 17:30 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		int response = -1;
It still does. Not a big deal, just wondering if there's something I'm no reading correctly.

2023-10-06 17:32 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +	ComponentTransform2D* transform = GetOwner()->GetComponentInternal<ComponentTransform2D>();
Just a tip: the formatter automatically calls GetName on GameObjects, so no need to do it yourself 😉

2023-10-06 17:35 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		frameData = new uint8_t[video->GetFrameWidth() * video->GetFrameHeight() * 4];
Now it's deleted in the destructor, but if we had allocated memory before reaching this line you'll leak it. Make sure to delete before allocating new memory.

2023-10-06 17:36 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceVideo.h
> +	AVFrame* avFrame = nullptr;
Awesome, thank you!

2023-10-06 22:46 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		throw ComponentNotFoundException("Owner does not have ComponentTrasnform2D");
Finally, I change this for that:
```c++
if (!GetOwner()->HasComponent<ComponentTransform2D>())
{
  LOG_ERROR("Owner does not have ComponentTrasnform2D");
  return;
}
```

2023-10-06 23:05 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.cpp
> +		frameData = new uint8_t[video->GetFrameWidth() * video->GetFrameHeight() * 4];
I add a delete of frameData in each Draw:

```c++
if (video)
{
video->Load();

if (frameData)
{
	delete[] frameData;
	frameData = nullptr;
}


  frameData = new uint8_t[video->GetFrameWidth() * video->GetFrameHeight() * 4];
  memset(frameData, 0, video->GetFrameWidth() * video->GetFrameHeight() * 4);
  ReadVideoFrame();
}
```

2023-10-06 23:14 UTC, ericdacal commented on Source/DataModels/Components/UI/ComponentVideo.h
> +	bool GetLoop();
Done

2023-10-07 23:15 UTC, gerard-queralt approved these changes

2023-10-08 10:34 UTC, Vlukkee approved these changes

2023-10-08 21:50 UTC, MacXxs commented
Looking great Eric! Just one thing.
When playing a video is constantly printing this in the console. Shouldn't it be only printed once?

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/4b315f71-236c-41fa-9968-b6e34a5b86c3)

2023-10-09 17:30 UTC, ericdacal commented
> Looking great Eric! Just one thing. When playing a video is constantly printing this in the console. Shouldn't it be only printed once?
> 
> ![image](https://user-images.githubusercontent.com/18547655/273475629-4b315f71-236c-41fa-9968-b6e34a5b86c3.png)
> 
> A part from that, why isn't the video_test.avi showing the option to be rotated? Is it because of the format?

This is a debug log that I can remove, about opening_previw.avi, yes I the avi format can not be rotate, but .mp4 and .mov yes.

2023-10-09 17:37 UTC, merged