feat: Debug Camera Frustum utilities
Horizons-Games/Axolotl-Engine pull request #667
Opened 2023-08-29 14:23 UTC by OriolSors

- Fixed the Frustum position and orientation. Now you can move scene Camera objects and Frustum gets updated.
- You can select the frustum to use and cull the objects outside it.
- The frustum selected to use is also drawn if you check it.
- Only one frustum can be selected. If none of them are checked, the Engine Camera frustum will be the one selected.

2023-08-29 14:28 UTC, Dedado3000 submitted a review, later dismissed

2023-08-29 14:34 UTC, MacXxs commented
Hi Oriol, thanks for the changes!! 
I've found a bug though, if you have the frustum window opened while loading a scene the engine crashes:
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/c06a9830-0989-4f86-8bd4-45cb278b7dd6)

Gonna keep looking for any possible bugs

2023-08-29 14:35 UTC, MacXxs requested changes
The bug i commented just now 👀

2023-08-29 14:49 UTC, MacXxs commented
I've found another issue, the transform for the camera isn't updated with its parent's until the parent transform is modified.
![20b7b671b6850768efc485395101826d](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/430992b4-0f35-4988-a748-faeab4a1dac3)

2023-08-29 15:04 UTC, MacXxs commented
Also, maybe we should have the capacity to modify the near and far planes for the added camera. By default is using the ones from the engine camera?

2023-08-29 15:06 UTC, MacXxs commented
> > Hi Oriol, thanks for the changes!! I've found a bug though, if you have the frustum window opened while loading a scene the engine crashes: ![image](https://user-images.githubusercontent.com/18547655/264056398-c06a9830-0989-4f86-8bd4-45cb278b7dd6.png)
> > Gonna keep looking for any possible bugs
> 
> Oh, does this happen before the changes? Can you check it?

Tried it in another branch and it does not happen!

2023-08-29 15:08 UTC, OriolSors commented
> I've found another issue, the transform for the camera isn't updated with its parent's until the parent transform is modified. ![20b7b671b6850768efc485395101826d](https://user-images.githubusercontent.com/18547655/264060790-430992b4-0f35-4988-a748-faeab4a1dac3.gif)

I'm not sure but I think it's not an issue with the parent, but the frustum doesn't get updated until ontransformchanged is called. I can check it if it's an inconvenience

2023-08-29 16:28 UTC, MacXxs commented
> > > > Hi Oriol, thanks for the changes!! I've found a bug though, if you have the frustum window opened while loading a scene the engine crashes: ![image](https://user-images.githubusercontent.com/18547655/264056398-c06a9830-0989-4f86-8bd4-45cb278b7dd6.png)
> > > > Gonna keep looking for any possible bugs
> > > 
> > > 
> > > Oh, does this happen before the changes? Can you check it?
> > 
> > 
> > Tried it in another branch and it does not happen!
> 
> I have replicated it in develop... first time you load is not the problem. The problem appears when loading a scene once you have a scene loaded and the frustum window opened. So; I'm opening an issue

To me it happened loading a scene directly with the window opened, without having loaded one previously

2023-08-29 16:43 UTC, OriolSors commented
> Also, maybe we should have the capacity to modify the near and far planes for the added camera. By default is using the ones from the engine camera?

Done!

2023-08-29 17:47 UTC, AuxPort66 approved these changes

2023-08-30 10:02 UTC, Dedado3000 approved these changes

2023-08-30 10:09 UTC, merged