Game programming switch characters
Horizons-Games/Axolotl-Engine pull request #708
Opened 2023-09-11 19:09 UTC by Piterga12

Created the SwitchPlayerManagerScript, it should be added to the gameObject Managers in the scene.

In the scene ChangeBetweenCharacters you can test it.
Just press the key C or the Down D-pad in the controller and the player will change.

https://github.com/Horizons-Games/Axolotl-Engine/assets/80328187/d48371f3-5739-4d4f-a9a3-c4d1a2ee90d5

2023-09-12 02:38 UTC, AuxPort66 requested changes

2023-09-12 02:38 UTC, AuxPort66 commented on Game/Scripts/PlayerJumpScript.h
> +	bool isChangingPlayer;
Instead of putting this bool here and in PlayerMove, you should probably put it in PlayerManager and the rest refer to PlayerManager. Because right now you have a bug that allows you to attack when you're switching, so we need to add it there as well, and we need to add it to any player script, so it seems like something to me that should go in PlayerManager.

Or even, a better option for me at least, in ModulePlayer, modulePlayer has the active player, all these scripts should use ModulePlayer instead of having a gameObject Player and we should change the player in ModulePlayer with switchScript, if we put it there it will be easier to limit because all the scripts have access to the module. You can change the ModulePlayer player by calling ComponentPlayer->SetActualPlayer(true) on the new ActualPlayer, I can show you this on discord.

Apart of this, I like the animation and the first part seems to work well with any camera. The problem is that we don't get to the same place, this change can be executed in the middle of combat, so we need to put the second player in the same place. And it doesn't work properly in the level because we can have a rigid in the middle and then the character collides.

2023-09-12 10:31 UTC, markmeliaa requested changes
Looks good so far, altough this will need some adjustments. Also keep in mind that character swapping will not be available when starting the story right away, it will only be available once meeting Allura, so we will need some kind of blocker or checker that avoids the character swapping from triggering until Allura is rescued.

2023-09-12 10:31 UTC, markmeliaa commented on Game/Scripts/PlayerJumpScript.h
> +	bool isChangingPlayer;
> Instead of putting this bool here and in PlayerMove, you should probably put it in PlayerManager and the rest refer to PlayerManager. Because right now you have a bug that allows you to attack when you're switching, so we need to add it there as well, and we need to add it to any player script, so it seems like something to me that should go in PlayerManager.
>
> Or even, a better option for me at least, in ModulePlayer, modulePlayer has the active player, all these scripts should use ModulePlayer instead of having a gameObject Player and we should change the player in ModulePlayer with switchScript, if we put it there it will be easier to limit because all the scripts have access to the module. You can change the ModulePlayer player by calling ComponentPlayer->SetActualPlayer(true) on the new ActualPlayer, I can show you this on discord.

Agreed! `ModulePlayer` is in charge of controlling which is the active player at any time, so, as Sara says, using that Module would be a better approach.

> Apart of this, I like the animation and the first part seems to work well with any camera. The problem is that we don't get to the same place, this change can be executed in the middle of combat, so we need to put the second player in the same place. And it doesn't work properly in the level because we can have a rigid in the middle and then the character collides.

Yes, the new appearing character should fall in the same position as in which the other character left, because, if not, we will have positioning issues in various parts of the levels. Also try to adjust better the jump animation because with different heights of camera it does not look as good (try with the level ones, they are higher than the one you are using).
For the collision part, when a character is changing, we could disable its `RigidBody`, so if anything was in the middle of the character and the camera, the character will not collide with it, and the same for the appearing character, keep its `RigidBody` disabled until it arrives the right position in the level (or it gets near that position).

2023-09-12 10:31 UTC, markmeliaa commented on Game/Scripts/SwitchPlayerManagerScript.h
> +	std::vector<GameObject*> players;
Using a vector to store what we know will be only two players seems a bit overkill to me, maybe using two `GameObject` fields seems more intuitive?

2023-09-12 10:31 UTC, markmeliaa commented on Game/Scripts/SwitchPlayerManagerScript.h
> +}
We don't do `inline`s in gameplay scripts, move these two functions to the source file please.

2023-09-12 10:31 UTC, markmeliaa commented on Game/Scripts/SwicthPlayerManagerScript.cpp
> +		if (input->GetKey(SDL_SCANCODE_C) != KeyState::IDLE)
Idk if the `TAB` key is being used elsewhere, but the selected key to perform the chracter swapping in the GDD was the `TAB` key, not the C key.

2023-09-12 10:33 UTC, markmeliaa commented on Game/Scripts/PlayerJumpScript.h
> +	bool isChangingPlayer;
> Instead of putting this bool here and in PlayerMove, you should probably put it in PlayerManager and the rest refer to PlayerManager. Because right now you have a bug that allows you to attack when you're switching, so we need to add it there as well, and we need to add it to any player script, so it seems like something to me that should go in PlayerManager.
>
>Or even, a better option for me at least, in ModulePlayer, modulePlayer has the active player, all these scripts should use ModulePlayer instead of having a gameObject Player and we should change the player in ModulePlayer with switchScript, if we put it there it will be easier to limit because all the scripts have access to the module. You can change the ModulePlayer player by calling ComponentPlayer->SetActualPlayer(true) on the new ActualPlayer, I can show you this on discord.

Agreed! ModulePlayer is in charge of controlling which is the active player at any time, so, as Sara says, using that Module would be a better approach.

>Apart of this, I like the animation and the first part seems to work well with any camera. The problem is that we don't get to the same place, this change can be executed in the middle of combat, so we need to put the second player in the same place. And it doesn't work properly in the level because we can have a rigid in the middle and then the character collides.

Yes, the new appearing character should fall in the same position as in which the other character left, because, if not, we will have positioning issues in various parts of the levels. Also try to adjust better the jump animation because with different heights of camera it does not look as good (try with the level ones, they are higher than the one you are using).
For the collision part, when a character is changing, we could disable its RigidBody, so if anything was in the middle of the character and the camera, the character will not collide with it, and the same for the appearing character, keep its RigidBody disabled until it arrives the right position in the level (or it gets near that position).

2023-09-12 11:02 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentPlayerInput.cpp
> +	{ SDL_CONTROLLER_BUTTON_DPAD_DOWN, SDL_SCANCODE_C },
If you end up changing the key to swap characters, remember to change it here too.

2023-09-12 11:02 UTC, gerard-queralt commented on Source/DataModels/Components/ComponentRigidBody.cpp
> +		rigidBody->setMassProps(0, { 0, 0, 0 }); // To review: is this necessary here?
Maybe change this for an AXO_TODO

2023-09-12 11:02 UTC, gerard-queralt commented on Game/Scripts/SwitchPlayerManagerScript.h
> +	void IsChangingCurrentPlayer();
This sounds like a getter, maybe use other verbs like "Check" or "Handle"? Not great with naming myself so it's likely there are better options.

2023-09-12 14:19 UTC, Piterga12 commented on Game/Scripts/SwicthPlayerManagerScript.cpp
> +		if (input->GetKey(SDL_SCANCODE_C) != KeyState::IDLE)
Yeah, i thought so too, that the TAB button would be better, but it is being used for the combo on ComboManager

2023-09-12 15:53 UTC, markmeliaa commented on Game/Scripts/SwitchPlayerManagerScript.h
> +	std::vector<GameObject*> players;
We could keep having an index (player 0 and player 1), what seems completely off to me is having a vector for only 2 objects, it's like doing a switch for only two cases. It's just a matter of "feel", not something that breaks the engine or that hinders performance, so the ultimate decision lies on the owner of the code imo.

2023-09-12 15:54 UTC, markmeliaa commented on Game/Scripts/SwicthPlayerManagerScript.cpp
> +		if (input->GetKey(SDL_SCANCODE_C) != KeyState::IDLE)
Whoops, that's true, nvm them!

2023-09-12 16:14 UTC, Piterga12 commented on Game/Scripts/CameraControllerScript.cpp
> +			components->OnTransformChanged();
True, it is done atomatically already

2023-09-12 16:20 UTC, Piterga12 commented on Game/Scripts/SwitchPlayerManagerScript.h
> +	std::vector<GameObject*> players;
I get the point of view, i will just see which option repeats less code and use that one really, and add a condition as well to check if the second player is empty (or if the size of the vector is only 0 and not 1) so that you cannot change characters having only one, as rigth now, it does the changing animation and the new player is the player0 again

2023-09-17 19:25 UTC, Piterga12 commented
New Updates to the Switch Characters:

-New switching animation
-Cannot switch players while jumping
-Cannot move, attack or jump while switching characters

+Refactored: The enemies get the current Player from ModulePlayer

+To test it you can use the scene Level 1 (i used a copy of Bix prefab but left theJumpAttack particles active on him so that you can tell it is two different players) or in the scene ChangeBetweenCharacters

+To add the functionality to a different scene, we just need to add the switchPlayerManagerScript to the gameObject managers in the scene, put the particles gameObject as a child of the gameObject managers (the particles switchPlayerParticles is a placeHolder), and finally add to the script switchPlayerManagerScript the second player gameObject and the particles gameObject)


https://github.com/Horizons-Games/Axolotl-Engine/assets/80328187/d82f5f59-ff32-4d06-8c1f-13b827ba9125

2023-09-18 11:49 UTC, markmeliaa requested changes
Haven't look at the code yet, but I had some issues while trying the branch (I tried everything in the `ChangeBetweenCharacters` scene).

- First, when changing characters in that scene, the characters did not jumped behind the camera but rather stayed in place, was that intended because there are not enough cameras in that scene?
- Second, while changing between characters, in one of the changes from Allura to Allura2, Allura suddenly got stuck in the fall animation (I was not jumping or anything, I was just pressing C several times), I could move around and everything but the animator got stuck in that animation and did not change to any other:
<img width="738" alt="Captura de pantalla 2023-09-18 133944" src="https://github.com/Horizons-Games/Axolotl-Engine/assets/82601780/89f01d30-700a-49cb-8d9a-60b35e11c578">
- Third, when the enemy attacked me, it had `nullptr` as its target and the engine broke, was that intended because there are some things left to set up or is it a real mistake? This was the state of the call stack when the engine broke:
<img width="1113" alt="Captura de pantalla 2023-09-18 134137" src="https://github.com/Horizons-Games/Axolotl-Engine/assets/82601780/02730af1-4cea-4b1c-927b-fa2a660e2b9a">


- Finally, when changing to the second Allura, the prefab bullet was showing everytime.

2023-09-18 11:56 UTC, markmeliaa commented
Aside from the feedback, why did you decide to change the base branch from `game-programming` to `develop`, did anything happen?

2023-09-18 13:08 UTC, Piterga12 commented
> Aside from the feedback, why did you decide to change the base branch from `game-programming` to `develop`, did anything happen?

Well just that game-programming isn't up to date with develop (the release Sara did) wether my branch is (as i needed to test it with the latest level 1), so if i do the pr to game-programming, it appears like i have changes hundreds of things so it would make it harder to see what i have actually changed.
If we update game-programming i could perfectly focus the pr there

2023-09-18 13:11 UTC, markmeliaa commented
> If we update game-programming i could perfectly focus the pr there

`game-programming` is updated with `develop` since yesterday night.

2023-09-18 13:12 UTC, Piterga12 commented
> Haven't look at the code yet, but I had some issues while trying the branch (I tried everything in the `ChangeBetweenCharacters` scene).
> 
> * First, when changing characters in that scene, the characters did not jumped behind the camera but rather stayed in place, was that intended because there are not enough cameras in that scene?
> * Second, while changing between characters, in one of the changes from Allura to Allura2, Allura suddenly got stuck in the fall animation (I was not jumping or anything, I was just pressing C several times), I could move around and everything but the animator got stuck in that animation and did not change to any other:
> 
> <img alt="Captura de pantalla 2023-09-18 133944" width="738" src="https://user-images.githubusercontent.com/82601780/268634244-89f01d30-700a-49cb-8d9a-60b35e11c578.png"> - Third, when the enemy attacked me, it had `nullptr` as its target and the engine broke, was that intended because there are some things left to set up or is it a real mistake? This was the state of the call stack when the engine broke: <img alt="Captura de pantalla 2023-09-18 134137" width="1113" src="https://user-images.githubusercontent.com/82601780/268634801-02730af1-4cea-4b1c-927b-fa2a660e2b9a.png">
> * Finally, when changing to the second Allura, the prefab bullet was showing everytime.

Regarding the change animation, i talked with sara and we decided it would be better like this so that we dont have issues with cameras and stuff.
I will take a look into the getting stuck in the falling animation.
I think i may have forgotten to update the current player on that enemy, i will take a look.
And yeah, i left it activated so that i could differenciate them easily (as i did with bix in level1 leaving some particles active), but it shouldn't matter as it is only an example

2023-09-23 01:09 UTC, Piterga12 commented
Now The Switch Characters has the Allura healthbar (and the health system works with it)
You can test the changes on ChangeBetweenPlayers scene or in Level_1_ALFA_ChangePlayers (in this scene i imported another scene into it to add Allura to it, but that import makes that the textures work a bit weird, so dont mind that.

2023-09-24 11:07 UTC, markmeliaa commented
Seems like there are some conflicts 👀

2023-09-24 11:26 UTC, Piterga12 commented
> Seems like there are some conflicts 👀

Done!

2023-09-24 11:53 UTC, markmeliaa reviewed
Haven't tested thoroughly the functionality, but the down D pad is not working to swap between characters with a Switch Controller, I had to use the C key of the keyboard.
Also, Bix animator gets stuck in the jump falling animation sometimes when swapping to her in the level 1.

2023-09-24 12:42 UTC, Piterga12 commented
> Haven't tested thoroughly the functionality, but the down D pad is not working to swap between characters with a Switch Controller, I had to use the C key of the keyboard. Also, Bix animator gets stuck in the jump falling animation sometimes when swapping to her in the level 1.

The input now works, but i couldnt reproduce that Bix gets stuck in the falling animation, but i think that might get solved with Marc's pr

2023-09-26 10:37 UTC, diegusmejia117 requested changes
Tested, it works nicely in general, but the seems to be another bug when you make a jump attack, you don't get stuck in the animation but you can't move or do any other action until you swap characters again.

2023-09-27 04:39 UTC, AuxPort66 commented
So that I can put the VFX in easily, the VisualEffect trigger should be when you actually swap the characters, not when you press C. Otherwise it's going to appear on the ground and I won't be able to cover the switch well. I see the rest well.

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/93783740/a2e50f7e-a92a-4fff-b14a-cb5759e254a3)

2023-09-27 13:35 UTC, Piterga12 commented
> So that I can put the VFX in easily, the VisualEffect trigger should be when you actually swap the characters, not when you press C. Otherwise it's going to appear on the ground and I won't be able to cover the switch well. I see the rest well.
> 
> ![image](https://user-images.githubusercontent.com/93783740/270861048-a2e50f7e-a92a-4fff-b14a-cb5759e254a3.png)

Done!

2023-09-28 20:32 UTC, AuxPort66 approved these changes

2023-09-29 09:38 UTC, MarcGonzalezMoratona commented
conflicts 👀

2023-09-29 09:39 UTC, MarcGonzalezMoratona commented on Game/Assets/ParticleSystem/SwitchCharactersParticles.particle.meta
> +{
do we need to add this meta file?

2023-09-29 09:40 UTC, MarcGonzalezMoratona commented
Hi @Piterga12, are the meta files of particles and images needed?

2023-09-29 09:42 UTC, MarcGonzalezMoratona commented on Source/Engine.vcxproj.filters
> +    <ClCompile Include="..\Game\Scripts\ParticleBillboardAsistance.cpp">
```suggestion
    <ClCompile Include="..\Game\Scripts\ParticleBillboardAssistance.cpp">
```

2023-09-29 09:43 UTC, MarcGonzalezMoratona commented on Source/Engine.vcxproj.filters
> +    <ClCompile Include="..\Game\Scripts\ParticleBillboardAsistance.cpp">
typo 👀

2023-09-29 09:43 UTC, MarcGonzalezMoratona commented on Source/Engine.vcxproj.filters
> +    <ClInclude Include="..\Game\Scripts\ParticleBillboardAsistance.h">
```suggestion
    <ClInclude Include="..\Game\Scripts\ParticleBillboardAssistance.h">
```

2023-09-29 09:47 UTC, MarcGonzalezMoratona commented on Game/Scripts/UITrigger.cpp
> +	setPlayer = App->GetModule<ModulePlayer>()->GetPlayer();
why did you remove 'setPlayer' from the initializer list? I think that right now, this variable is receiving a default value in the class constructor, which is then overwritten in the 'start' method

2023-09-29 10:10 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerJumpScript.h
> +	bool isChangingPlayer;
@Piterga12 why was this resolved? Did you fix it?

2023-09-29 10:12 UTC, MarcGonzalezMoratona commented on Game/Scripts/ParticleBillboardAsistance.h
> +class ParticleBillboardAsistance : public Script
```suggestion
class ParticleBillboardAssistance : public Script
```
don't forget to modify the file name

2023-09-29 10:25 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerManagerScript.cpp
> +void PlayerManagerScript::ForcingJump(bool forcedJump)
```suggestion
void PlayerManagerScript::TriggerJump(bool forcedJump)
```
just a matter of personal preference, but don't you find this name easier to understand?

2023-09-29 10:34 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.h
> +	GameObject* playerHealthBar;
```suggestion
	GameObject* currentPlayerHealthBar;
```
like this I find it easier to understand

2023-09-29 10:36 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.h
> +	float3 positionPlayer;
```suggestion
	float3 playerPosition;
```
looks like you were using "playerWhatever" in all the rest of the code. So just for consistency purposes, keep it the same way

2023-09-29 10:37 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +	if (healthSystemClassBix->GetCurrentHealth()!= componentSliderPlayerBack->GetCurrentValue()
```suggestion
	if (healthSystemClassBix->GetCurrentHealth() != componentSliderPlayerBack->GetCurrentValue()
```

2023-09-29 10:39 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
>  		player->SetMouse(true);
```suggestion
		player->SetMouse(menuIsOpen);
```
you can put this outside of the if-else block and you will have one less line in your code 😄

2023-09-29 10:41 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +void UIGameManager::ModifyBixSliderHealthValue()
you could probably make everything in a single method for both players if you pass the healthSystemClass and the sliders by parameters to the method. And you will avoid code duplication

2023-09-29 10:42 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +SwitchPlayerManagerScript::SwitchPlayerManagerScript() : Script(), camera(nullptr), input(nullptr), isSwitchAvailable(true), changingPlayerTime{ 800.f, 1800.f},
```suggestion
SwitchPlayerManagerScript::SwitchPlayerManagerScript() : Script(), camera(nullptr), input(nullptr), isSwitchAvailable(true), changingPlayerTime{800.f, 1800.f},
```

2023-09-29 10:43 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +	currentPlayer = App->GetModule<ModulePlayer>()->GetPlayer();
you can store the App->GetModule<ModulePlayer>() in a variable

2023-09-29 10:45 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +		if(isSwitchingHealthBars)
```suggestion
		if (isSwitchingHealthBars)
```

2023-09-29 10:46 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +			float t = (changePlayerTimer.Read() - changingPlayerTime[0]) / 1000;
```suggestion
			float t = (changePlayerTimer.Read() - changingPlayerTime[0]) / 1000;
```
probably `t` is not the best name you could give to that variable

2023-09-29 10:47 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +				Lerp(playerHealthBar->GetComponent<ComponentTransform2D>()->GetPosition().x, secondHealthBarPosition.x, t),
you can store this in a variable `playerHealthBar->GetComponent<ComponentTransform2D>`

2023-09-29 10:47 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +				Lerp(playerHealthBar->GetComponent<ComponentTransform2D>()->GetPosition().x, secondHealthBarPosition.x, t),
same for the second player

2023-09-29 10:48 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +	Scene* loadScene = App->GetModule<ModuleScene>()->GetLoadedScene();
you can store this in a variable `App->GetModule<ModuleScene>()`
or even this `App->GetModule<ModuleScene>()->GetLoadedScene()`

2023-09-29 10:49 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +		App->GetModule<ModuleScene>()->GetLoadedScene()->DestroyGameObject(actualSwitchPlayersParticles);
```suggestion
		loadScene->DestroyGameObject(actualSwitchPlayersParticles);
```

2023-09-29 10:50 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +	actualSwitchPlayersParticles->GetComponent<ComponentTransform>()->SetGlobalPosition(float3 (currentPlayer->GetComponent<ComponentTransform>()->GetGlobalPosition().x,
you can store this in variables
`currentPlayer->GetComponent<ComponentTransform>()`
`actualSwitchPlayersParticles->GetComponent<ComponentTransform>()
`

2023-09-29 10:54 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +void SwitchPlayerManagerScript::CheckChangeCurrentPlayer()
What does this method check? Maybe the name is not descriptive or I don't understand it. Can you explain me what this does? Are you preparing here everything to make a player switch?

2023-09-29 10:56 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +		playerHealthBar->GetComponent<ComponentTransform2D>()->SetPosition(secondHealthBarPosition);
let's store this in a variable `playerHealthBar->GetComponent<ComponentTransform2D>()`

2023-09-29 10:56 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +		playerHealthBar->GetComponent<ComponentTransform2D>()->SetPosition(secondHealthBarPosition);
same for the second player

2023-09-29 10:57 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +GameObject* SwitchPlayerManagerScript::GetSecondPlayer()
this can be const!

2023-09-29 10:57 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +GameObject* SwitchPlayerManagerScript::GetSecondPlayer()
```suggestion
GameObject* SwitchPlayerManagerScript::GetSecondPlayer() const
```

2023-09-29 10:58 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +	currentHealthBarPosition = playerHealthBar->GetComponent<ComponentTransform2D>()->GetPosition();
`playerHealthBar->GetComponent<ComponentTransform2D>()` you can store this in a variable

2023-09-29 10:58 UTC, MarcGonzalezMoratona commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +	currentHealthBarPosition = playerHealthBar->GetComponent<ComponentTransform2D>()->GetPosition();
same for the second player

2023-09-29 10:59 UTC, MarcGonzalezMoratona reviewed
Thank you for your work Peter! The functionality looks great. I left comments to improve code readability. I hope it helps!

2023-09-29 11:16 UTC, Piterga12 commented
> conflicts 👀

Done

2023-09-29 11:19 UTC, Piterga12 commented on Game/Assets/ParticleSystem/SwitchCharactersParticles.particle.meta
> +{
Yeah, we do, we are only supposed to add the meta files when it is a new file (like if it is a new texture, particles, etc...)

2023-09-29 14:47 UTC, Piterga12 commented on Game/Scripts/SwitchPlayerManagerScript.cpp
> +void SwitchPlayerManagerScript::CheckChangeCurrentPlayer()
This is for when the trigger at the end of level 1 is added, so basically when Allura joins we will allow the switch characters, as otherwise it would be activated since the start of level 1 (right now it is, as we still dont have the trigger done)

2023-09-30 21:43 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerJumpScript.cpp
> +void PlayerJumpScript::ChangingCurrentPlayer()
maybe this should be called `ToggleIsChangingPlayer`  or something similar

2023-10-01 01:39 UTC, Piterga12 commented
You can test it on Level1_changeplayers

2023-10-02 13:44 UTC, markmeliaa commented on Game/Scripts/SeekBehaviourScript.cpp
> +		targetTransform = target->GetComponent<ComponentTransform>();
`GetComponent` is too costly of a function to have inside an `Update`, was this the only possible solution that you found to apply this functionality?

2023-10-02 13:50 UTC, markmeliaa commented on Game/Scripts/PlayerAttackScript.h
> +	void PlayWeaponSounds();
Remember const-correctness.

2023-10-02 15:02 UTC, markmeliaa requested changes
Hey! Trying out the functionality of the switch characters, when I swap to Allura, her attack seems to be broken, bullets do not behave as they should, any idea why?

https://github.com/Horizons-Games/Axolotl-Engine/assets/82601780/3b03da42-0260-4252-8a0d-d48310dcf5f1

2023-10-05 10:09 UTC, markmeliaa commented on Game/Scripts/FinalBossScript.cpp
> +#include "Application.h"
Already included

2023-10-05 11:08 UTC, Piterga12 commented on Game/Scripts/FinalBossScript.cpp
> +#include "Application.h"
Done! Thanks for noticing

2023-10-05 14:12 UTC, markmeliaa approved these changes

2023-10-05 15:40 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerManagerScript.cpp
> +		owner->GetComponent<ComponentRigidBody>()->GetRigidBody()->setLinearVelocity(btVector3(0.f, 0.f, 0.f));
you can extract the btVector3 in a variable with default value 0,0,0 and the only change the value if !paused (you can do the same with less code and cleaner). After the if, you set the linear velocity with your variable

2023-10-05 15:40 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerManagerScript.h
> +#include "Bullet\LinearMath\btVector3.h"
I saw other places that use btVector3 without this include. check if you can remove it

2023-10-05 15:41 UTC, diegusmejia117 approved these changes

2023-10-05 15:41 UTC, MarcGonzalezMoratona commented on Game/Scripts/PowerUpsManagerScript.cpp
> +	if (player != App->GetModule<ModulePlayer>()->GetPlayer())
you can extract this in a variable App->GetModule<ModulePlayer>()->GetPlayer()

2023-10-05 15:42 UTC, MarcGonzalezMoratona commented on Game/Scripts/ElevatorCore.cpp
> +	if (currentPlayer != App->GetModule<ModulePlayer>()->GetPlayer())
you can extract this in a variable App->GetModule<ModulePlayer>()->GetPlayer()

2023-10-05 15:42 UTC, Piterga12 commented on Game/Scripts/PlayerManagerScript.h
> +#include "Bullet\LinearMath\btVector3.h"
Already checked this, both includes are necessary

2023-10-05 15:45 UTC, MarcGonzalezMoratona commented on Game/Scripts/FinalBossScript.cpp
> +		target = App->GetModule<ModulePlayer>()->GetPlayer();
you can extract this in a variable App->GetModule<ModulePlayer>()->GetPlayer()

2023-10-05 15:45 UTC, MarcGonzalezMoratona commented on Game/Scripts/SeekBehaviourScript.cpp
> +	if (target != App->GetModule<ModulePlayer>()->GetPlayer())
you can extract this in a variable App->GetModule<ModulePlayer>()->GetPlayer()

2023-10-05 15:52 UTC, MarcGonzalezMoratona submitted a review, later dismissed

2023-10-05 16:20 UTC, Piterga12 commented on Game/Scripts/PowerUpsManagerScript.cpp
> +	if (player != App->GetModule<ModulePlayer>()->GetPlayer())
Unluckily can't as if the player changes, the variable would have the old player

2023-10-05 16:43 UTC, Dedado3000 approved these changes

2023-10-05 16:43 UTC, MarcGonzalezMoratona approved these changes

2023-10-05 19:30 UTC, merged