UI/hud/Combo system
Horizons-Games/Axolotl-Engine pull request #752
Opened 2023-09-25 08:08 UTC by csandra24

2023-09-29 09:21 UTC, MarcGonzalezMoratona commented on Game/Scripts/BixAttackScript.cpp
> +	if(true)
I don't know which is the logic that we want to have here, but probably it should be something different

2023-09-29 09:22 UTC, MarcGonzalezMoratona commented on Game/Scripts/ComboManager.cpp
> +		if (uiComboManager)
do we need this if?

2023-09-29 09:22 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.h
> +	bool alphaActivated;
```suggestion
	bool alphaEnabled;
```

2023-09-29 09:22 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.h
> +	GameObject* shinnyButton;
```suggestion
	GameObject* shinyButton;
```

2023-09-29 09:22 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.h
> +	GameObject* shinnyButton2;
```suggestion
	GameObject* shinyButton2;
```

2023-09-29 09:23 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.h
> +	GameObject* shinnyButton1;
probably we can give this buttons a name more related to their functionality, not just a number

2023-09-29 09:23 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.h
> +	GameObject* shinnyButton2;
probably we can give this buttons a name more related to their functionality, not just a number

2023-09-29 09:25 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +	transparency = noFillBar->GetComponent<ComponentImage>()->GetColor().w/255;
are you sure you should divide by 255? or is it 256 because the range is from 0 to 255?

2023-09-29 09:25 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +			//los borra
```suggestion
```

2023-09-29 09:28 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +			if (transparency <= 0.5)
```suggestion
			if (transparency <= 0.5f)
```

2023-09-29 09:28 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +				transparency = 0.5;
```suggestion
				transparency = 0.5f;
```

2023-09-29 09:28 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +			if (transparency <= 1.0)
```suggestion
			if (transparency <= 1.0f)
```

2023-09-29 09:28 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +				transparency = 1.0;
```suggestion
				transparency = 1.0f;
```

2023-09-29 09:28 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +		noFillBar->GetComponent<ComponentImage>()->SetColor(float4(1, 1, 1, transparency));
```suggestion
		noFillBar->GetComponent<ComponentImage>()->SetColor(float4(1.0f, 1.0f, 1.0f, transparency));
```

2023-09-29 09:29 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIComboManager.cpp
> +		comboBar->GetFill()->GetComponent<ComponentImage>()->SetColor(float4(1, 1, 1, 1));
I know it's not related to this PR but prefer using 1.0f instead of 1 if the values are floats. It improves readability

2023-09-29 09:32 UTC, MarcGonzalezMoratona requested changes
Thank you for your work Sandra! I think we should delete the meta files before we are able to merge this into develop. I also left some comments to improve the logic and readability of the code

2023-10-03 19:21 UTC, markmeliaa commented
I'm taking over this pr, tomorrow morning I'll adress your comments @MarcGonzalezMoratona and check that everything works correctly. For now the conflicts are fixed and the trial scene is updated with all our current functionality.

2023-10-04 12:02 UTC, markmeliaa commented on Game/Scripts/BixAttackScript.cpp
> +	if(true)
This script was outdated and currently removed after the merge with develop.

2023-10-04 12:04 UTC, markmeliaa commented on Game/Scripts/ComboManager.cpp
> +		if (uiComboManager)
We didn't, as we have our `assert` at the beginning of the script.

2023-10-04 12:48 UTC, markmeliaa commented on Game/Scripts/UIComboManager.cpp
> +	transparency = noFillBar->GetComponent<ComponentImage>()->GetColor().w/255;
That line seemed to do nothing, because `w` was already a float between `0.0f` and `1.0f`, no need to normalize it, so I deleted that value. 
Regardless, to answer your question, it is correct to divide between 255 because what I understood she was trying to do is to normalize the `w` value, and to do that you have to divide for the hightest value of `w` so `w` ends in an interval between 0 and 1, it doesn't matter if the range is [0, 255] or [1, 255]. If you divided it for 265 then the normalization could never be 1, because 255 (its highest value) divided by 256 (your suggestion) results in 0,996.

2023-10-07 17:12 UTC, AuxPort66 commented on Game/Scripts/UIComboManager.cpp
> +	if (!clearCombo)
This change doesn't have into account the if in the 87 that doesn't depend on clearCombo

2023-10-07 17:30 UTC, markmeliaa commented on Game/Scripts/UIComboManager.cpp
> +	if (!clearCombo)
Mb, saw it wrong, I'll check it asap.

2023-10-07 17:52 UTC, markmeliaa commented on Game/Scripts/UIComboManager.cpp
> +	if (!clearCombo)
Done!

2023-10-09 20:30 UTC, diegusmejia117 approved these changes

2023-10-09 22:45 UTC, Dedado3000 approved these changes

2023-10-09 23:46 UTC, merged