feat: Light culling
Horizons-Games/Axolotl-Engine pull request #755
Opened 2023-09-26 16:46 UTC by MacXxs

This PR implements light culling into the engine, optimizing lighting so it does not take a toll to performance and only renders visible lights.

|Without light culling|With light culling|
|----|----|
|![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/d5c31166-cdfc-4de9-9798-517907dfabc6)|![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/6b0ccd76-f8d1-487c-90ff-0dd9086d58b6)|

In the shown image there is an increase in performance of 30 fps (enabling ALL lights in the scene)

2023-09-26 20:29 UTC, PaablooCH requested changes
Found 1 error and other minor things

2023-09-26 20:29 UTC, PaablooCH commented on Source/DataModels/Render/LightPass.h
> +#include <map>
this is inside the stdAfx, is necessary?

2023-09-26 20:29 UTC, PaablooCH commented on Source/Shaders/metallic_fragment.glsl
removing light calculation from this fragment, and the specular one also, makes that the transparent objects don't receive light (transparents are not in gBuffer textures)

|Develop|this PR|
|----|----|
| ![ezgif com-video-to-gif (1)](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/4ac60a38-75a4-40dd-a6ad-47d54177bf2a)  | ![ezgif com-video-to-gif (2)](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/e13a8037-25da-42d4-9177-9c1dc283f6cd)

2023-09-26 21:12 UTC, MacXxs commented on Source/Shaders/metallic_fragment.glsl
What we spoke in discord

2023-09-26 21:14 UTC, MacXxs commented on Source/DataModels/Components/ComponentAreaLight.cpp
> +#include "Modules/ModuleDebugDraw.h"
Removed it from the ifndef 'cause i need it in engine mode

2023-09-26 21:15 UTC, MacXxs commented on Source/DataModels/Components/ComponentAreaLight.cpp
> +	if (transform->IsDrawBoundingBoxes())
'Cause I only want to paint the bboxes in engine mode

2023-09-26 21:15 UTC, MacXxs commented on Source/DataModels/Components/ComponentPointLight.cpp
> +#include "Modules/ModuleDebugDraw.h"
As stated before

2023-09-26 21:16 UTC, MacXxs commented on Source/DataModels/Components/ComponentSpotLight.cpp
> +#include "Modules/ModuleDebugDraw.h"
same

2023-09-26 21:29 UTC, MacXxs commented on Source/DataModels/Render/LightPass.h
> +#include <map>
We cannot include it in the .h, it should only be included in .cpp, if you test it you will see it crashes.

2023-09-26 23:52 UTC, PaablooCH commented on Source/DataModels/Components/ComponentAreaLight.cpp
> +	if (transform->IsDrawBoundingBoxes())
my bad, I thought it was inside the destructor

2023-09-27 08:17 UTC, AlexisDieu approved these changes

2023-09-27 09:04 UTC, PaablooCH approved these changes

2023-09-27 12:31 UTC, merged