fix: dash integration fixes
Horizons-Games/Axolotl-Engine pull request #758
Opened 2023-09-27 10:50 UTC by MarcGonzalezMoratona

Improved the integration between the dash and attack animations.
Fix Allura's mass and gravity in gameplayTrial scene for Allura.
Fix Bix's state machine after a double jump, sometimes got stuck in double jump state
Add preInput to dash during jump or attack
Fix state machine to allow transitions between Dash and sorrounding states

2023-09-27 11:39 UTC, markmeliaa reviewed
Everything alright? Why did the other pr got closed, did anything happen?

2023-09-27 11:41 UTC, MarcGonzalezMoratona commented
> Everything alright? Why did the other pr got closed, did anything happen?

I have a problem with the pipeline, it doesn't pass because of a FALLING variable. I don't see why this is happening. Everything compiles locally. I was testing if there was something cached, but it is still not working...

2023-09-27 11:42 UTC, MarcGonzalezMoratona commented
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/80526953/1c47029a-92af-4f87-a1a5-d040bfe44280)

2023-09-27 11:49 UTC, markmeliaa commented
> I have a problem with the pipeline, it doesn't pass because of a FALLING variable. I don't see why this is happening. Everything compiles locally. I was testing if there was something cached, but it is still not working...

Have you compiled and run either DebugGame or ReleaseGame locally? It seems to be those two who are making the pipeline fail.

2023-09-27 11:56 UTC, MarcGonzalezMoratona commented
> > I have a problem with the pipeline, it doesn't pass because of a FALLING variable. I don't see why this is happening. Everything compiles locally. I was testing if there was something cached, but it is still not working...
> 
> Have you compiled and run either DebugGame or ReleaseGame locally? It seems to be those two who are making the pipeline fail.



> > I have a problem with the pipeline, it doesn't pass because of a FALLING variable. I don't see why this is happening. Everything compiles locally. I was testing if there was something cached, but it is still not working...
> 
> Have you compiled and run either DebugGame or ReleaseGame locally? It seems to be those two who are making the pipeline fail.

I was not expecting this to fail in game mode, but I'll make a build to check if there's something wrong

2023-09-27 12:17 UTC, MarcGonzalezMoratona commented
@markmeliaa the build works in releaseGame

2023-09-27 15:12 UTC, MarcGonzalezMoratona commented
> So `FALLING` is not being used anywhere and it compiles well locally, but if you delete the `FALLING` state the pipeline does not compile Game builds, is that what's happening?

Yes, that's exactly the problem and I don't understand it.

2023-09-27 23:53 UTC, MarcGonzalezMoratona commented
@AuxPort66 @DADSILVER @diegusmejia117 @markmeliaa @Piterga12 this is ready to be tested!

2023-09-28 11:06 UTC, markmeliaa reviewed
A couple comments before trying the functionality:

2023-09-28 11:14 UTC, markmeliaa commented
Regarding functionality, I can shoot with Allura while doing the roll, that should not be possible.
And if I dash in the air, it gets stored until I hit the floor and then the dash happens, that's weird because it feels as you can "store" a dash, which should not be possible.

2023-09-28 12:41 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerAttackScript.cpp
> +void PlayerAttackScript::AttackAfterDash()
this has been created because we need the attack to wait until the dash animation finishes, we can not attack during a dash

2023-09-28 14:01 UTC, DADSILVER requested changes
Good job, but a few things about the gameplay.

After testing the gameplay, the dash store feels really bad. You can attack 20 times and forget that you pressed the dash button and after all this attack the dash will be executed. This happened too with the jump.

About dash: feels good not to have "cd" with Bix look awesome, but with Allura, if you dash 4 times in a row sometimes the animation doesn't work or the move is done and the roll is in the site.

About Jump: All seems good except that you are falling and jumping with the coyote time the animation of the first jump didn't show.

This feedback is for gameplay. I will read the code now.

2023-09-28 14:02 UTC, MarcGonzalezMoratona commented
> Good job, but a few things about the gameplay.
> 
> After testing the gameplay, the dash store feels really bad. You can attack 20 times and forget that you pressed the dash button and after all this attack the dash will be executed. This happened too with the jump.
> 
> About dash: feels good not to have "cd" with Bix look awesome, but with Allura, if you dash 4 times in a row sometimes the animation doesn't work or the move is done and the roll is in the site.
> 
> About Jump: All seems good except that you are falling and jumping with the coyote time the animation of the first jump didn't show.
> 
> This feedback is for gameplay. I will read the code now.

Thanks for the feedback David! I'll take a look at what you asked and let you know when it's fixed!

2023-09-28 15:18 UTC, MarcGonzalezMoratona commented
> Good job, but a few things about the gameplay.
> 
> After testing the gameplay, the dash store feels really bad. You can attack 20 times and forget that you pressed the dash button and after all this attack the dash will be executed. This happened too with the jump.
> 
> About dash: feels good not to have "cd" with Bix look awesome, but with Allura, if you dash 4 times in a row sometimes the animation doesn't work or the move is done and the roll is in the site.
> 
> About Jump: All seems good except that you are falling and jumping with the coyote time the animation of the first jump didn't show.
> 
> This feedback is for gameplay. I will read the code now.

About the dash: Right now the cooldown is set to 0.1, after merging the PR we can modify the value of Allura to 0.2 or more (0.2 is what I found is the minimum value to avoid animation problems. Probably the cooldown should be higher also on Bix, not because of the animations, but for the mechanics. The game is probably too easy if you can dash whenever you want during a combat. If you don't mind, I'll skip the cooldown values for this PR, and we can address this topic later

2023-09-28 16:17 UTC, MarcGonzalezMoratona commented on Game/Scripts/PlayerAttackScript.cpp
> +void PlayerAttackScript::AttackAfterDash()
I tested this method and I see that it is not working as expected, so I removed it

2023-09-28 18:55 UTC, markmeliaa commented
Thanks for fixing my last comments, I tried the game again and, instead of not attacking during a dash, what I wanted is that, while the dash/roll animation is being performed, attacking should be disabled (bc it feels weird that Allura shoots a bullet while finishing the das). And why did you add back that you could dash during attacks? We already addressed that it felt weird in #748.

2023-09-28 19:00 UTC, MarcGonzalezMoratona commented
> Thanks for fixing my last comments, I tried the game again and, instead of not attacking during a dash, what I wanted is that, while the dash/roll animation is being performed, attacking should be disabled (bc it feels weird that Allura shoots a bullet while finishing the das). And why did you add back that you could dash during attacks? We already addressed that it felt weird in #748.

There's different people asking for different requirements. Please, can we meet?

2023-09-28 19:29 UTC, markmeliaa commented
> There's different people asking for different requirements. Please, can we meet?

Who's asking for different requirements?

2023-09-28 19:48 UTC, MarcGonzalezMoratona commented
> Thanks for fixing my last comments, I tried the game again and, instead of not attacking during a dash, what I wanted is that, while the dash/roll animation is being performed, attacking should be disabled (bc it feels weird that Allura shoots a bullet while finishing the das). And why did you add back that you could dash during attacks? We already addressed that it felt weird in #748.

It should be done as you asked me right now! Let me know if there's something else we need to change

2023-09-29 10:48 UTC, markmeliaa commented
what I wanted is that, while the dash/roll animation is being performed, attacking should be disabled (bc it feels weird that Allura shoots a bullet while finishing the dash). 

This is not yet fixed, the `DASHING` state of `PlayerActions` shouldn't be changed until its animation finished, because now Allura starts shooting bullets while its roll animation is finishing and that looks weird.

2023-09-29 11:22 UTC, MarcGonzalezMoratona commented
> > what I wanted is that, while the dash/roll animation is being performed, attacking should be disabled (bc it feels weird that Allura shoots a bullet while finishing the dash).
> 
> This is not yet fixed, the `DASHING` state of `PlayerActions` shouldn't be changed until its animation finished, because now Allura starts shooting bullets while its roll animation is finishing and that looks weird.

Nice catch Mark! It should be fixed now

2023-09-29 12:16 UTC, markmeliaa submitted a review, later dismissed
LGTM now!

2023-09-30 17:49 UTC, Piterga12 approved these changes
Good job!

2023-09-30 18:07 UTC, markmeliaa approved these changes

2023-09-30 18:18 UTC, DADSILVER approved these changes

2023-09-30 18:21 UTC, merged