feat<text>: add text with freety lib
Horizons-Games/Axolotl-Engine pull request #763
Opened 2023-09-28 14:45 UTC by elbuho12Jesus

I created a UI tool that works with the `Canvas`, this is used to add 2D text from different sources, please tell me if you need any changes.

2023-10-01 21:45 UTC, gerard-queralt requested changes
Main things that I think can be improved:
- Coding style: make sure your code follows our programming guidelines. I shared a link in one of my comments on how you can reformat the contents of your files.
- Pass by reference: most of your methods create unnecessary copies, be it in the parameters or in loops. Tried to keep an eye out for them, but please take another look yourself to see that I didn't miss any.
- Unnecessary access to raw pointers: whenever you want to access the memory managed by a unique or shared pointer using the member access operator `->`, you're first accessing the raw pointer by calling `get`. This is not needed, which you can see in the[ documentation](https://en.cppreference.com/w/cpp/memory/shared_ptr/operator*). I didn't point out every single instance of this, please check on your own and correct it.
- Commented-out code: there's a lot of commented out code. Either remove it or add an AXO_TODO so it gets addressed (hopefully).
- Memory leaks: there are a couple of leaks in the importer.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +	for (c = text.begin(); c != text.end(); c++)
Wouldn't it be easier to use a [range loop](https://en.cppreference.com/w/cpp/language/range-for)? Up to you though.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +								 { (xpos + w) / 48.0, (ypos + h) / 48.0, 0.0f, 1.0f }
Make sure to add `f` at the end of these "floats" (which are now doubles) to avoid compiler warnings.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +		}
1. Why use a `while` loop? You're never changing the value of `err` as far as I can tell
2. If it's an error, why log it as info?
```suggestion
		GLenum err = glGetError();
		if (err != GL_NO_ERROR)
		{
			std::string error;
			switch (err)
			{
				case GL_INVALID_OPERATION:
					error = "INVALID OPERATION";
					break;
				case GL_INVALID_ENUM:
					error = "INVALID ENUM";
					break;
				case GL_INVALID_VALUE:
					error = "INVALID VALUE";
					break;
				case GL_OUT_OF_MEMORY:
					error = "OUT OF MEMORY";
					break;
				case GL_INVALID_FRAMEBUFFER_OPERATION:
					error = "INVALID FRAMEBUFFER OPERATION";
					break;
				default:
					error = "UNKNOWN ERROR";
					break;
			}
			LOG_ERROR("OpenGL error while binding the texture in ComponentText2D owned by {}; error: {}", GetOwner(), error);
		}
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +		/*for (int i=0;i<6;i++)
Remove commented out code, here and elsewhere, if it's not needed. If it is, add an AXO_TODO to address the reason why it's commented out.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +		x += (ch.Advance >> 6) * scale; // bitshift by 6 to get value in pixels (2^6 = 64 (divide amount of 1/64th pixels by 64 to get amount of pixels))
Is there not another way to do this? Always weary when seeing bit operations... Also, if you follow my comment to prevent copying Characters by getting them as references, make sure it doesn't screw with this. Can't remember off the top of my head if the bit-shift operator will modify the memeber.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +std::vector<std::shared_ptr<ResourceFont>> ComponentText2D::getFonts()
I see it's used to select a font, but I still think the component is doing too many things at once.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +	currentFont.get()->LoadCharacter();
We're computing all possible fonts when we already know which one we want, and exposing a public member method in the process... I think a better approach would be to create a helper class that exposes a method like:
```c++
std::shared_ptr<ResourceFont> RequestFont(Font requestedFont);
```
Where `Font` is an enum class representing all the available font's in the engine (in your current code a script could call `SetCharacters` with any value and cause an aout-of-bounds read on the vector). You might even be able to memoize the resources vector after the first call, thought that might cause some issues if we want new fonts to be added at runtime. For an example of a helper class, you can take a look at `GameBuilder` or `SceneLoader`.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +void ComponentText2D::Update()
Remove the empty overload and don't inherit from `Updatable` if your component does not update. It will take up memory in the Scene member vectors.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +	if (FT_Init_FreeType(&ft))
We are initializing and shutting down the library each time we import a font? That feels like a very unnecessary and costly thing to do. Why not make `ModuleUI` take care of this?

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +bool ResourceFont::ImportFont(std::string nameFount)
```suggestion
bool ResourceFont::ImportFont(const std::string& nameFount)
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +	std::string font_name = nameFount;
Do we need to create a copy of the string here? If we do, disregard my previous comment: pass the string by copy to the method and get rid of this `font_name` (which should be fontName).

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +		/*ENGINE_LOG("ERROR::FREETYPE: Failed to load font_name");*/
Put the logs back in, but make them more accurate instead of copy-pasting the same message. We didn't fail to load a font, the user passed us an empty string.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +	else
Unnecessary else, we're returning in the if block.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +				LOG_INFO("ERROR::FREETYTPE: Failed to load Glyph");
Not info, either warning or error.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +			storeFont.push_back(store);
```suggestion
			storeFont.emplace_back(
				c,
				face->glyph->bitmap.width,
				face->glyph->bitmap.rows,
				face->glyph->bitmap_left,
				face->glyph->bitmap_top,
				static_cast<unsigned int>(face->glyph->advance.x),
				sizeBuffer,
				pixel);
```
Or some variation of that.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +	bool ResourceFont::LoadCharacter()
```suggestion
bool ResourceFont::LoadCharacter()
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +		for (StoreFontInPixels store : storeFont)
```suggestion
		for (const StoreFontInPixels& store : storeFont)
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +			characters.insert(std::pair<char, Character>(store.symbol, character));
```suggestion
			characters.insert(std::pair<char, Character>(store.symbol, std::move(character)));
```
Or construct it in-place, up to you.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +	std::map<char, Character> ResourceFont::GetCharacters()
```suggestion
std::map<char, Character> ResourceFont::GetCharacters()
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.cpp
> +	bool ResourceFont::IsCharacterEmpty()
```suggestion
bool ResourceFont::IsCharacterEmpty()
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.h
> +	std::vector<StoreFontInPixels> storeFont;
Better to make the member private and use getters and setters, as per the C++ standard.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Resources/ResourceFont.h
> +	bool IsCharacterEmpty();
```suggestion
	bool IsCharacterEmpty() const;
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Scene/Scene.cpp
> +			// sceneInteractableComponents.push_back(gameObject->CreateComponent<ComponentText2D>());
```suggestion
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentText2D.cpp
> +	for (std::shared_ptr<ResourceFont> i : componentText2D->getFonts())
```suggestion
	for (const std::shared_ptr<ResourceFont>& resource : componentText2D->getFonts())
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentText2D.cpp
> +		items+=i.get()->GetFileName();
```suggestion
		items += i->GetFileName();
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentText2D.cpp
> +		items += '\0';
Shouldn't this be a line break?
```suggestion
		items += '\n';
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentText2D.h
> +	char str1[128];
Use better names, please.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/FileSystem/Importers/FontImporter.cpp
> +	char* buffer{};
Never deleted, memory leak.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/FileSystem/Importers/FontImporter.cpp
> +	if (resource.get()->ImportFont(filePath)) {
```suggestion
	if (resource->ImportFont(filePath))
	{		
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/FileSystem/Importers/FontImporter.cpp
> +		int header2[2] = { it.left, it.top };
Better name.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/FileSystem/Importers/FontImporter.cpp
> +	char* cursor = new char[size];
This leaks.

2023-10-01 21:45 UTC, gerard-queralt commented on Source/FileSystem/Importers/FontImporter.cpp
> +	for (StoreFontInPixels it : resource.get()->storeFont)
```suggestion
	for (const StoreFontInPixels& it : resource->storeFont)
```

2023-10-01 21:45 UTC, gerard-queralt commented on Source/Shaders/text_fragment.glsl
Talk to the graphics team to make sure both shaders are needed, maybe we can reuse some.

2023-10-05 11:39 UTC, elbuho12Jesus commented on Source/DataModels/Components/UI/ComponentText2D.cpp
> +	if (resourceExists)
I check that the source exist in the folder Assets, but maybe I should do it another way.

2023-11-16 11:19 UTC, elbuho12Jesus commented
I finished with the requirements, could you check if this is ready to use?

2023-11-16 11:19 UTC, closed without merging