Gameprogramming/tutorials
Horizons-Games/Axolotl-Engine pull request #773
Opened 2023-10-03 21:57 UTC by diegusmejia117

Feature:

TutorialSystem script to control tutorial UI, being managed by a custom script (CombatSystem), this script can be easily replicated for other tutorials.

-TutorialSystem needs an array of images(with the script UIDisplacementControl) in scene to work, while CombatTutorial needs to be a component of a GameObject with a trigger si its OnCollisionEnter works.

2023-10-06 16:02 UTC, DADSILVER submitted a review, later dismissed
Good job, but I can't test any of the levels.  __LEVEL1_ALFA_TutorialTest doesn't work and Gameplay_TrialAllura_Tutorial doesn't see in my screen. 

There are other things to fix in the code:

2023-10-06 18:43 UTC, markmeliaa commented on Game/Scripts/UIImageDisplacementControl.h
Add them to the source files instead of the header files, Diego please.

2023-10-07 09:00 UTC, diegusmejia117 commented on Game/Scripts/UIImageDisplacementControl.h
yeah this code is Ale's but changed it to adapt to the rules.

2023-10-07 09:00 UTC, diegusmejia117 commented on Game/Scripts/EnemyDeathScript.cpp
debug feature i didnt delete, sorry

2023-10-07 09:01 UTC, diegusmejia117 commented on Game/Scripts/CombatTutorial.cpp
> +	userControllable = true;
true, deleted them and added to constructor

2023-10-07 09:01 UTC, diegusmejia117 commented on Game/Scripts/CombatTutorial.cpp
fixed

2023-10-07 09:01 UTC, diegusmejia117 commented on Game/Scripts/TutorialSystem.cpp
> +	REGISTER_FIELD(userControllable, bool);
also debug feature forgot to erase.

2023-10-07 09:01 UTC, diegusmejia117 commented on Game/Scripts/TutorialSystem.cpp
erased comments

2023-10-07 09:04 UTC, diegusmejia117 commented
Currently testing for @DADSILVER comment about it not working in triallAllura_Tutorial, it doesnt work in level tutorial as it has a problem that i think is fixed by Marc's PR.

2023-10-08 14:26 UTC, markmeliaa requested changes
Hey! I'm having some problems with the tutorial, if I press the heavy attack button all the way through the tutorial (once the attacks begin to be explained), it skips all the explanations without having to do the actual attacks.
Ideally, when an attack is explained, it should wait for the player to perform the attack and only when that attack is performed, the tutorial should carry on, but performing the heavy normal attack (not even a finisher), skips through all the attack explanations.

(Tested it in the Allura trial, the level 1 tutorial trial scene breaks before loading).

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +		if (tutorialUI->GetTutorialCurrentState() == int(tutorialUI->GetNumControllableState()))
```suggestion
		if (tutorialUI->GetTutorialCurrentState() == static_cast<int>(tutorialUI->GetNumControllableState()))
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.75
```suggestion
	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.75f 
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +		&& dummyHealthSystem->GetCurrentHealth() > dummyHealthSystem->GetMaxHealth() * 0.50 && !nextStateActive)
```suggestion
		&& dummyHealthSystem->GetCurrentHealth() > dummyHealthSystem->GetMaxHealth() * 0.50f && !nextStateActive)
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.50
```suggestion
	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.50f 
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +		&& dummyHealthSystem->GetCurrentHealth() > dummyHealthSystem->GetMaxHealth() * 0.25 && nextStateActive)
```suggestion
		&& dummyHealthSystem->GetCurrentHealth() > dummyHealthSystem->GetMaxHealth() * 0.25f && nextStateActive)
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.75
If you don't add an `f` at the end of a decimal number, they get treated as `double` instead of `float`, and a warning is raised.

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.25
```suggestion
	else if (dummyHealthSystem->GetCurrentHealth() <= dummyHealthSystem->GetMaxHealth() * 0.25f 
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +		&& dummyHealthSystem->GetCurrentHealth() > 0 && !nextStateActive)
```suggestion
		&& dummyHealthSystem->GetCurrentHealth() > 0.0f && !nextStateActive)
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +	else if (dummyHealthSystem->GetCurrentHealth() <= 0 && nextStateActive)
```suggestion
	else if (dummyHealthSystem->GetCurrentHealth() <= 0.0f && nextStateActive)
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/CombatTutorial.cpp
> +	if (tutorialFinished && !nextStateActive && finalWaitTime <= 0)
```suggestion
	if (tutorialFinished && !nextStateActive && finalWaitTime <= 0.0f)
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/TutorialSystem.cpp
> +	isWaiting = false;
Variables that do not depend on other objects can be initalized in the constructor using `isWaiting (false)`

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/TutorialSystem.cpp
> +	}
```suggestion
	if (isWaiting)
	{
		stateWaitTime-= deltaTime;
		if (stateWaitTime <= 0)
	        {
		     isWaiting = false;
		     stateWaitTime = totalStateWaitTime;
		     DeployUI();
	        }
	}
```

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/TutorialSystem.cpp
> +	}
The second `if` statement depends on the first one, it has no sense to check if `stateWaitTime` is less than 0 if `isWaiting` was not set to true.

2023-10-08 14:26 UTC, markmeliaa commented on Game/Scripts/UIImageDisplacementControl.h
> +	bool moving = false;
Why did you decide to remove the is in this two variables?

2023-10-08 14:28 UTC, markmeliaa commented
And conflicts 👀

2023-10-08 15:01 UTC, diegusmejia117 commented on Game/Scripts/UIImageDisplacementControl.h
> +	bool moving = false;
this a change  david made, in serach of better bool correctness. so i am not certain what of two ways is the most correct one.

2023-10-08 15:02 UTC, diegusmejia117 commented on Game/Scripts/TutorialSystem.cpp
> +	isWaiting = false;
yeah missed it, thanks for pointing it out

2023-10-08 15:25 UTC, markmeliaa commented on Game/Scripts/UIImageDisplacementControl.h
> +	bool moving = false;
Preferably, when naming booleans, naming then `isJumping`, `isAttacking`, `isMoving` is better than just `jumping`, `attacking` or `moving`, but it's fine, we don't have any programming rule against that and it wasn't your change, so that's okay!

2023-10-08 15:26 UTC, markmeliaa commented
Heads up! Remember these two https://github.com/Horizons-Games/Axolotl-Engine/pull/773#discussion_r1349702867, https://github.com/Horizons-Games/Axolotl-Engine/pull/773#discussion_r1349702917.

2023-10-08 16:00 UTC, diegusmejia117 commented
Pls do not test the level 1 tutorial it doesn't work, replying to your comment @markmeliaa  yes the way you describe it is the best way, I did it basing it on health for quickness purposes, but I fully intend to change it so it has in mind when the attacks are made, right now I prefer it merged so ta have something to show, and then change it. As right now I am working in some VFX

2023-10-08 20:40 UTC, Dedado3000 commented on Game/Scripts/UIImageDisplacementControl.h
> +	bool moving = false;
true true, i was changing the getters because were named GetIsX and my mind just blowUp and remove the is from variables

2023-10-08 20:42 UTC, markmeliaa commented on Game/Scripts/UIImageDisplacementControl.h
> +	bool moving = false;
Fair enough, nw!

2023-10-08 20:43 UTC, markmeliaa commented
> Heads up! Remember these two https://github.com/Horizons-Games/Axolotl-Engine/pull/773#discussion_r1349702867, https://github.com/Horizons-Games/Axolotl-Engine/pull/773#discussion_r1349702917.

@diegusmejia117 okay! if you fix these two comments you left, I can approve this pr

2023-10-08 21:16 UTC, markmeliaa approved these changes

2023-10-08 21:21 UTC, DADSILVER submitted a review, later dismissed

2023-10-08 21:41 UTC, markmeliaa submitted a review, later dismissed

2023-10-08 21:49 UTC, DADSILVER approved these changes

2023-10-09 08:16 UTC, Dedado3000 approved these changes
I fixed the lightning but all good

2023-10-09 08:42 UTC, diegusmejia117 reviewed
good job, thanks for the lights and the trigger problem

2023-10-09 10:03 UTC, MarcGonzalezMoratona approved these changes

2023-10-09 10:03 UTC, merged