UI Option Menu and minors changes
Horizons-Games/Axolotl-Engine pull request #785
Opened 2023-10-06 21:22 UTC by Vlukkee

To test it you need open Main Menu vs3 and play the scene.

You can only test it with a controller, test it with mouse and keyboard its very tricky.

**OPTIONS MENU**

GAME:
> FPS LIMIT - AUTO - 30 - 60 - 144
VSYNC - OFF - ON
BRIGHTNESS - 0 TO 100
RESOLUTION - AUTO - 720 - 1080 - 2K - 4K
WINDOWS MODE - FULLSCREEN - DESKTOP FULLSCREEN - BORDERLESS -  BORDER

VIDEO
> SHADOWS - ON /OFF
SSAO - ON /OFF
VSM - ON /OFF
BLOOM - ON /OFF

AUDIO
> MASTER - 0 TO 100
MUSIC - 0 TO 100
VFX - 0 TO 100

CONTROLLER
> JUST AN IMG WITH THE CONTROLLER

MINOR CHANGES
- Change the Credits image and button.
- Create a script to show you numbers in real time.
- Modify buttons controller in the UI
- Fix an error in te play pause that make buttons dont work
- Delete old IMG that we dont use anymore

KNOW ERRORS
- Fullscreen dont work proprerly, now is in desktop fullscreen mode.

2023-10-08 13:27 UTC, diegusmejia117 submitted a review, later dismissed

2023-10-08 15:19 UTC, markmeliaa submitted a review, later dismissed
Couple typos and changes to follow the programming rules, but in general a really good job Ale, congrats!!

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIOptionsMenu.h
> +	bool resettButtonIndex;
```suggestion
	bool resetButtonIndex;
```

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIOptionsMenu.cpp
Please, check the lenght of the lines of this script, we have set in our programming rules that the column limit is 120 characters, and there are several lines in this script that are above that limit.

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (actualConfig[(int)Canvas::GAME_CANVAS].options[(int)Button::WINDOWSMODE].actualOption == 0 ||
```suggestion
	if (actualConfig[static_cast<int>(Canvas::GAME_CANVAS)].options[(int)Button::WINDOWSMODE].actualOption == 0 || 
```

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (actualConfig[(int)Canvas::GAME_CANVAS].options[(int)Button::WINDOWSMODE].actualOption == 0 ||
C style casts are not recommended in C++, `static_cast` is overall better for casting (apply this for all the script, there are several C style casts).

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIOptionsMenu.h
> +}
We decided that we won't use `inlines` in game-related scripts, please, move those to the cpp.

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIText.cpp
> +		for (int a=0; a < 3; a++)
Not needed for this pr, but for the future, try to name the variables more accordingly to what they are doing. Reading `a` as a variable gives any possible reader no information of what that it is doing, whereas that `currentComboPosition` would give the reader more information.

Also, that `3` could be turned into a `constexpr` and given a proper name (such as `comboMax`), so it would look less "hard-coded".

So your loop would look like:
```c++
for (int currentComboPosition = 0; currentComboPosition < comboMax; ++currentComboPosition)
```
And this can be extended to any variable, function or class that you create, remember to make your code readable.

P.S. Also remember that a pre-increment is preferably better in `for` loops, as we don't need to store the variable before incrementing its value (++a is better than a++).

2023-10-08 15:19 UTC, markmeliaa commented on Game/Scripts/UIGameManager.cpp
> +debbugModeObject(nullptr), imgMouse(nullptr), imgController(nullptr),inputMethod(true), prevInputMetod(nullptr)
`prevInputMetod` is a `bool`, not a pointer.

2023-10-08 22:49 UTC, Vlukkee commented on Game/Scripts/UIGameManager.h
> +	GameObject* debbugModeObject;
OK, changed. Thanks!

2023-10-08 23:03 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +debbugModeObject(nullptr), imgMouse(nullptr), imgController(nullptr),inputMethod(true), prevInputMetod(nullptr)
I set to true instead of false for the logic part.

2023-10-08 23:04 UTC, Vlukkee commented on Game/Scripts/UIGameManager.h
> +	bool prevInputMetod;
Cahnged. Thanks

2023-10-08 23:07 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	bool resettButtonIndex;
Changed. Thanks!

2023-10-08 23:19 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (actualConfig[(int)Canvas::GAME_CANVAS].options[(int)Button::WINDOWSMODE].actualOption == 0 ||
Nice to know, Tanks! Changed

2023-10-08 23:25 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +}
Changed in this and others.

2023-10-08 23:42 UTC, Vlukkee commented on Game/Scripts/UIText.cpp
> +		for (int a=0; a < 3; a++)
Ok i dont know the pre increment for the loop. Thanks!

I set a variable to get the max number to show and change the "for" variables to get better read

```
int maxNumberToShow = inputPositions.size();

for (int currentNumToShow=0; currentNumToShow < maxNumberToShow; ++currentNumToShow)
```

2023-10-09 00:10 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
Check!

2023-10-09 06:33 UTC, diegusmejia117 submitted a review, later dismissed
Tested it, works as intended

2023-10-09 10:48 UTC, totisama approved these changes
I got an error when I tried to change the "shadows" option to off, before that I had changed some options in the game tab. I've tried to replicate it but I couldn't get the error to show up again. Besides that everything is working nice.

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/32148906/6276d6df-a0c2-493a-a563-68465dd25312)
![image2](https://github.com/Horizons-Games/Axolotl-Engine/assets/32148906/fe89c5cc-2e5a-43d7-882c-d3cb45e4bc57)

2023-10-09 11:15 UTC, MarcGonzalezMoratona requested changes
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/80526953/1b327828-7ee7-491d-b06b-4f272a6fda7a)

2023-10-09 11:15 UTC, MarcGonzalezMoratona commented
> ![image](https://user-images.githubusercontent.com/80526953/273568775-1b327828-7ee7-491d-b06b-4f272a6fda7a.png)

![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/80526953/7fcdf3b8-1d26-4d4e-973e-44bf8e5e53c9)

2023-10-09 11:16 UTC, MarcGonzalezMoratona commented
OptionsConfig.txt is saving things to null and this makes the engine explode
![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/80526953/af4a177e-90e2-4f76-9711-ab5fb32273bf)

2023-10-09 11:21 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	CONTROLL_CANVAS = 3
```suggestion
	CONTROLLER_CANVAS = 3
```

2023-10-09 11:22 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	void ControlEnable();
```suggestion
	void EnableController();
```

2023-10-09 11:23 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	GameObject* controlOptionHover;
```suggestion
	GameObject* controlsOptionHover;
```

2023-10-09 11:23 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	GameObject* controlOptionCanvas;
```suggestion
	GameObject* controlsOptionCanvas;
```

2023-10-09 11:23 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	GameObject* controlOptionButton;
```suggestion
	GameObject* controlsOptionButton;
```

2023-10-09 11:24 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	ComponentButton* controlOptionComponentButton;
```suggestion
	ComponentButton* controlsOptionComponentButton;
```

2023-10-09 11:26 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIText.cpp
> +	timeDiff = currentTime - previusTime;
```suggestion
	timeDiff = currentTime - previousTime;
```

2023-10-09 12:45 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIButtonControl.cpp
> +setUiGameManagerObject(nullptr), UIGameManagerClass(nullptr), isBackButton (false)
```suggestion
setUiGameManagerObject(nullptr), UIGameManagerClass(nullptr), isBackButton(false)
```

2023-10-09 12:46 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIButtonControl.cpp
> +		if (isBackButton != false && input->GetKey(SDL_SCANCODE_E) == KeyState::DOWN)
```suggestion
		if (!isBackButton && input->GetKey(SDL_SCANCODE_E) == KeyState::DOWN)
```

2023-10-09 12:46 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +debugModeObject(nullptr), imgMouse(nullptr), imgController(nullptr),inputMethod(true), prevInputMethod(true)
```suggestion
debugModeObject(nullptr), imgMouse(nullptr), imgController(nullptr), inputMethod(true), prevInputMethod(true)
```

2023-10-09 12:48 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +	input = App->GetModule<ModuleInput>();
could we do this on Start to avoid calling it every frame?

2023-10-09 12:48 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +	// DEBBUG MODE
```suggestion
	// DEBUG MODE
```

2023-10-09 12:48 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +	//IN GAME MENU
```suggestion
	// IN-GAME MENU
```

2023-10-09 12:49 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +	if (currentInputTime == 0.0f && prevInputMethod != inputMethod )
```suggestion
	if (currentInputTime == 0.0f && prevInputMethod != inputMethod)
```

2023-10-09 12:51 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIGameManager.cpp
> +			prevInputMethod = input;
This two lines can be done outside of the if-else block and avoid code duplication
``
prevInputMethod = input;
currentInputTime++;
```

2023-10-09 12:56 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	void IsSizeOptionEnable();
```suggestion
	void IsSizeOptionEnabled();
```

2023-10-09 12:57 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.h
> +	void IsFpsEnable();
```suggestion
	void IsFpsEnabled();
```

2023-10-09 12:59 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIText.cpp
> +	REGISTER_FIELD(numbersIMG, std::vector<GameObject*>);
or numbersImages

2023-10-09 13:08 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +			else // CAMBIA OPCIONES CUANDO NO ES UN SLIDER
```suggestion
			else // CHANGE OPTIONS WHEN IS NOT A SLIDER
```

2023-10-09 13:10 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +void UIOptionsMenu::ApplyChanges(int headerMenuPosition, int actualButton, int newSelectedOption)
```suggestion

void UIOptionsMenu::ApplyChanges(int headerMenuPosition, int actualButton, int newSelectedOption)
```

2023-10-09 13:10 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +		ControlOption();
```suggestion
		ControlsOption();
```

2023-10-09 13:11 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +	for (int a = 0; a < optionsMenu.Size(); a++)
```suggestion
	for (int optionMenuIndex = 0; optionMenuIndex < optionsMenu.Size(); optionMenuIndex ++)
```

2023-10-09 13:12 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +		for (int b = 0; b < canvas.Size(); b++)
```suggestion
		for (int optionButtonIndex = 0; optionButtonIndex < canvas.Size(); optionButtonIndex ++)
```

2023-10-09 13:13 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +	for (int a = 0; a < actualConfig.size(); a++)
please use better variables names. a and b are not descriptive names of what the code is doing

2023-10-09 13:13 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +	for (int a = 0; a < buttonsAndCanvas.size()-1; a++)
same with these variables

2023-10-09 13:15 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (buttonsAndCanvas[header].canvas->GetChildren()[button]->GetChildren()[1]->GetChildren()[option]->
you can delete the if-else block and use

```suggestion
return buttonsAndCanvas[header].canvas->GetChildren()[button]->GetChildren()[1]->GetChildren()[option]->HasComponent<ComponentSlider>();
```

2023-10-09 13:16 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (actualConfig[static_cast<int>(Canvas::GAME_CANVAS)].options[static_cast<int>(Button::WINDOWSMODE)].actualOption == 0 ||
you can extract this in a variable at the beginning of the method and compare it with 0 or 1 to avoid code duplication:

int actualOption = actualConfig[static_cast<int>(Canvas::GAME_CANVAS)].options[static_cast<int>(Button::WINDOWSMODE)].actualOption

2023-10-09 13:17 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +		if (loadFromMainMenu == false)
```suggestion
		if (!loadFromMainMenu)
```

2023-10-09 13:18 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +			//window->SetFullscreen(true); // NOT WORKING PROPRETLY WE NEED FIX IT
```suggestion
			//window->SetFullscreen(true); // NOT WORKING PROPERTLY WE NEED TO FIX IT
```

2023-10-09 13:20 UTC, MarcGonzalezMoratona commented on Game/Scripts/UIOptionsMenu.cpp
> +void UIOptionsMenu::AudioOption(int button, int option)
This is not finished. Are you going to address it on another PR?

2023-10-09 13:22 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +void UIOptionsMenu::AudioOption(int button, int option)
I leave ready all for when the audio team finish add only the code necessary.

2023-10-09 13:24 UTC, MarcGonzalezMoratona commented
Good job Ale! 💪🏼  I found some issues and pointed out things that can be improved. Keep working on it and remember to fix conflicts! 👀

2023-10-09 19:32 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +	// DEBBUG MODE
Done!

2023-10-09 19:33 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +	//IN GAME MENU
Done!

2023-10-09 19:34 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +	// Player input method ture=GAMEPAD false=KEYBOARD
Done!

2023-10-09 19:34 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +	if (currentInputTime == 0.0f && prevInputMethod != inputMethod )
Done!

2023-10-09 19:36 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +			prevInputMethod = input;
Done!

2023-10-09 19:37 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	VFX = 2,
Done!

2023-10-09 19:39 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	GameObject* padTriggersIMG;
Done!

2023-10-09 19:40 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	void IsSizeOptionEnable();
Done!

2023-10-09 19:41 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	void IsFpsEnable();
Done!

2023-10-09 19:42 UTC, Vlukkee commented on Game/Scripts/UIText.cpp
> +	REGISTER_FIELD(numbersIMG, std::vector<GameObject*>);
Done!

2023-10-09 19:42 UTC, Vlukkee commented on Game/Scripts/UIText.cpp
> +	//FpsMetric(deltaTime); NEXT FEATURE WHEN SARA LET ME DO IT
Done

2023-10-09 19:43 UTC, Vlukkee commented on Game/Scripts/UIText.cpp
> +		for (int currentNumToShow=0; currentNumToShow < maxNumberToShow; ++currentNumToShow)
fixed

2023-10-09 20:03 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +			else // CAMBIA OPCIONES CUANDO NO ES UN SLIDER
Done!

2023-10-09 20:03 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +void UIOptionsMenu::ApplyChanges(int headerMenuPosition, int actualButton, int newSelectedOption)
Done!

2023-10-09 20:05 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +		ControlOption();
Done!

2023-10-09 20:07 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +	for (int a = 0; a < optionsMenu.Size(); a++)
Done!

2023-10-09 20:14 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +		for (int b = 0; b < canvas.Size(); b++)
Done!

2023-10-09 20:29 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (actualConfig[static_cast<int>(Canvas::GAME_CANVAS)].options[static_cast<int>(Button::WINDOWSMODE)].actualOption == 0 ||
donde

2023-10-09 20:33 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +			//window->SetFullscreen(true); // NOT WORKING PROPRETLY WE NEED FIX IT
DONE!

2023-10-09 20:33 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +		if (loadFromMainMenu == false)
DONE!

2023-10-09 22:46 UTC, Dedado3000 approved these changes

2023-10-10 00:15 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	CONTROLL_CANVAS = 3
Done!

2023-10-10 00:22 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	void ControlEnable();
I use ControllerMenuMode, because its more accurate. That not enable controls so is when we use the controller in the menu.
The contrapart will be KeyboardMenuMode.

2023-10-10 00:24 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	GameObject* controlOptionHover;
Done

2023-10-10 00:27 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.h
> +	ComponentButton* controlOptionComponentButton;
done

2023-10-10 00:27 UTC, Vlukkee commented on Game/Scripts/UIOptionsMenu.cpp
> +	if (resetButtonIndex == true)
done

2023-10-10 00:29 UTC, Vlukkee commented on Game/Scripts/UIText.cpp
> +	timeDiff = currentTime - previusTime;
Done

2023-10-10 00:29 UTC, Vlukkee commented on Game/Scripts/UIButtonControl.cpp
> +setUiGameManagerObject(nullptr), UIGameManagerClass(nullptr), isBackButton (false)
done

2023-10-10 00:30 UTC, Vlukkee commented on Game/Scripts/UIButtonControl.cpp
> +		if (isBackButton != false && input->GetKey(SDL_SCANCODE_E) == KeyState::DOWN)
done

2023-10-10 00:31 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +debugModeObject(nullptr), imgMouse(nullptr), imgController(nullptr),inputMethod(true), prevInputMethod(true)
donep

2023-10-10 00:32 UTC, Vlukkee commented on Game/Scripts/UIGameManager.cpp
> +	input = App->GetModule<ModuleInput>();
done

2023-10-10 00:36 UTC, Vlukkee commented
> OptionsConfig.txt is saving things to null and this makes the engine explode ![image](https://user-images.githubusercontent.com/80526953/273568915-af4a177e-90e2-4f76-9711-ab5fb32273bf.png)

fixed



> Some files need a name change if possible:
> 
> Remeber to fix the meta files too

Sorry but its too mutch work for now.



> > ![image](https://user-images.githubusercontent.com/80526953/273568775-1b327828-7ee7-491d-b06b-4f272a6fda7a.png)
> 
> ![image](https://user-images.githubusercontent.com/80526953/273568841-7fcdf3b8-1d26-4d4e-973e-44bf8e5e53c9.png)



> I got an error when I tried to change the "shadows" option to off, before that I had changed some options in the game tab. I've tried to replicate it but I couldn't get the error to show up again. Besides that everything is working nice.
> 
> ![image](https://user-images.githubusercontent.com/32148906/273562835-6276d6df-a0c2-493a-a563-68465dd25312.png) ![image2](https://user-images.githubusercontent.com/32148906/273562838-fe89c5cc-2e5a-43d7-882c-d3cb45e4bc57.png)

Its hard to find this but i think is fixed with the json fix

2023-10-10 00:49 UTC, MarcGonzalezMoratona approved these changes
Works well and code looks good. Nice job! thank you for fixing everything I requested!

2023-10-10 00:53 UTC, Piterga12 approved these changes

2023-10-10 01:14 UTC, MarcGonzalezMoratona approved these changes

2023-10-10 01:18 UTC, Piterga12 approved these changes

2023-10-10 01:49 UTC, merged